### ISSUE TITLE
Triyng to swith to an unknow repository

### ISSUE THREAD

**Issue by slvxstar** [pydio/pydio-core#1002]
After enabling guest access, the administrator can not enter administration

**Comment by cdujeu** [comment]
I tested that and did not have any problem. So you enable guest access, then logout (so you're guest), then log in again as admin, and cannot find settings ?
-c

**Comment by slvxstar** [comment]
Yes, the system does not recognize the role of the administrator, as a normal user.
No access to the administration panel.

**Comment by slvxstar** [comment]
Server version: Apache/2.2.22 (Debian)
Server built:   Aug 18 2015 09:50:52
Server's Module Magic Number: 20051115:30
Server loaded:  APR 1.4.6, APR-Util 1.4.1
Compiled using: APR 1.4.6, APR-Util 1.4.1
Architecture:   64-bit
Server MPM:     Prefork
  threaded:     no
    forked:     yes (variable process count)
Server compiled with....
 -D APACHE_MPM_DIR="server/mpm/prefork"
 -D APR_HAS_SENDFILE
 -D APR_HAS_MMAP
 -D APR_HAVE_IPV6 (IPv4-mapped addresses enabled)
 -D APR_USE_SYSVSEM_SERIALIZE
 -D APR_USE_PTHREAD_SERIALIZE
 -D APR_HAS_OTHER_CHILD
 -D AP_HAVE_RELIABLE_PIPED_LOGS
 -D DYNAMIC_MODULE_LIMIT=128
 -D HTTPD_ROOT="/etc/apache2"
 -D SUEXEC_BIN="/usr/lib/apache2/suexec"
 -D DEFAULT_PIDLOG="/var/run/apache2.pid"
 -D DEFAULT_SCOREBOARD="logs/apache_runtime_status"
 -D DEFAULT_LOCKFILE="/var/run/apache2/accept.lock"
 -D DEFAULT_ERRORLOG="logs/error_log"
 -D AP_TYPES_CONFIG_FILE="mime.types"
 -D SERVER_CONFIG_FILE="apache2.conf"


PHP 5.4.45-0+deb7u2 (cli) (built: Oct 17 2015 08:26:31)

**Comment by cdujeu** [comment]
Pydio 6.2 ?

**Comment by cdujeu** [comment]
ok I can reproduce this - stay tuned

**Comment by cdujeu** [comment]
If you can try this patch...

**Comment by slvxstar** [comment]
Thank patch corrected
