### ISSUE TITLE
action.share Update Share pb

### ISSUE THREAD

**Issue by Fabzz007** [pydio/pydio-core#1004]
Hi,

When I try to update a share, to disable the expiration date or limit the number of download, I use the link “change parameters”. I position these two values to 0 and I click the update button, but the changes are not taken into account. If I use values other than 0, it works.

Pydio 6.2.0 fresh install on ubuntu 14 LTS.

Charles answered me : "ha ha that smells the “empty()” php function call. I can reproduce that, could you open a bug on github? Thx"

**Comment by Fabzz007** [comment]
THx Charles, but Using this new class.ShareCenter.php file give an error when i open my WorkSpaces : illegal offset type. This a red message at the bottom of the screen.

**Comment by cdujeu** [comment]
ok I reopen :-)

**Comment by cdujeu** [comment]
Mmmm, no looking at the code, I don't see how it could impact. You just changed the ShareCenter ? Nothing else? did you clear the plugins cache? Maybe restart apache to make sure to clear opcode cache? 
-c

**Comment by cdujeu** [comment]
@Fabzz007 any news on that?

**Comment by Fabzz007** [comment]
Hi! Sorry but i am a dad since yesterday so i Will try monday with service apache2 resart

**Comment by cdujeu** [comment]
Wow ! Congrats!

**Comment by Fabzz007** [comment]
It look good since the 6.2.1 upgrade :-) Thx Charles !
