### ISSUE TITLE
ZIP browsing not working if files in ZIP archives are under a directory

### ISSUE THREAD

**Issue by Ellega** [pydio/pydio-core#1010]
ZIP browsing not working if files in ZIP archives are under a directory

ZIP browsing works if files in ZIP archives are to the root 

no pb with pydio 6.0.8
pb from pydio 6.2.x

**Comment by cdujeu** [comment]
Please more info about your OS, the error, etc.

**Comment by Ellega** [comment]
Windows OS
Apache 2.4.16 x86
php nts 5.6.16
pydio 6.2.1 ssl

tested with: "access.fs" 

If we browse file under a directory from a zip archive we have a blank screen with this error : 

![2015-12-11_120630](https://cloud.githubusercontent.com/assets/3939543/11742370/a93f1a30-9fff-11e5-8fb2-422188c029ac.png)

![2015-12-11_120744](https://cloud.githubusercontent.com/assets/3939543/11744576/c5fc7e8a-a011-11e5-8cde-4e3b0f4c02eb.png)

![2015-12-11_120827](https://cloud.githubusercontent.com/assets/3939543/11744555/9949878e-a011-11e5-857c-450f80f0bac6.png)

**Comment by Ellega** [comment]
I try to help as I can ...

But if you comment this control in "class.fsAccessDriver.php" at line 861 -> line 863 all woks fine:

```
           /* if(!is_readable($path) && !is_writeable($path)){
                    throw new Exception("You are not allowed to access folder " . $path);
                } */ 
```

this contrrol doesn't exist in pydio 6.0.8

**Comment by cdujeu** [comment]
this should have been fixed in 6.2.1 normally. I don't understand if the zip has a specific structure in your examples?

**Comment by Ellega** [comment]
specific structure ?

only archive ZIP named "zip_with_directory_1.zip" what content 1 directory and 3 files like this : 

"zip_with_directory_1.zip"
........ L dossier1
........ ........ L doc1.pdf
........ ........ L doc2.xls
........ ........ L doc3.doc

**Comment by cdujeu** [comment]
Ellega can you test with the current latest (download.pydio.com/pub/core/ci/pydio-latest.zip) ? 
-c

**Comment by Ellega** [comment]
I have use the current latest and clear all cache ....

always same issue, same error and same trick for solve this : 

comment in "class.fsAccessDriver.php" line 865 -> line 867 :

```
           /* if(!is_readable($path) && !is_writeable($path)){
                    throw new Exception("You are not allowed to access folder " . $path);
                } */ 
```

**Comment by cdujeu** [comment]
very probably windows-specific, as it's working ok for me. Will recheck.

**Comment by cdujeu** [comment]
Thx to test this fix!

**Comment by Ellega** [comment]
Works fine now ;-) thx
