### ISSUE TITLE
Wrong visualization in sharing folder window form

### ISSUE THREAD

**Issue by rbrdevs** [pydio/pydio-core#1013]
When I change between Workspaces with different “ENABLE FOLDER SHARING” parameter configuration, I need to reload (F5) the whole page in order to get sharing form displayed as expected.
If I first access to unresticted Workspace I see that when changing to another WS.
http://postimg.org/image/dnzmshen1/
But when I first access to a restricted WS and change to an unresticted one later I always see this
http://postimg.org/image/kneqnfww1/

Charles answer:
Seems like the value must be cached by the ShareCenter instead of reloaded when switching from WS to another.

**Comment by cdujeu** [comment]
Yes exactly. And to fully understand the usecase, you want to enable/disable depending on the workspace using roles, right?

**Comment by rbrdevs** [comment]
Yes, you are right.
Thanks!

Additionally, I wish if I would like to enable/disable plugins using roles (ex. only some users can make use of cart).
