### ISSUE TITLE
PHP Fatal error:  Call to a member function getDataArray() on boolean

### ISSUE THREAD

**Issue by Conver** [pydio/pydio-core#1016]
Unable to save profile data, both from user and admin page.

Getting this in my log:

`PHP Fatal error:  Call to a member function getDataArray() on boolean in /var/www/pydio/plugins/access.ajxp_conf/class.ajxp_confAccessDriver.php on line 900, referer: https://10.0.0.204/settings/data/users`

**Comment by Conver** [comment]
This also applies to when trying to edit ACL for a given user.

**Comment by cdujeu** [comment]
Hi,
This is not a qualified bug, please post in the forum instead, thx! Https://pydio.com/forum/
