### ISSUE TITLE
Uncaught SyntaxError: Unexpected token <

### ISSUE THREAD

**Issue by woei66** [pydio/pydio-core#1024]
I git clone the pydio source code and done the installation.
![1](https://cloud.githubusercontent.com/assets/5770807/11950328/5a284f9a-a8c2-11e5-9cae-bed8e9de58d6.PNG)

Uncaught SyntaxError: Unexpected token <Ajax.Request.onComplete @ VM82:1

My server environment:
linux+php5.6+nginx

**Comment by cdujeu** [comment]
This is not a qualified bug, PLEASE use the forum, thx.
