### ISSUE TITLE
No login with the plugin for joomla with the last version of joomla 

### ISSUE THREAD

**Issue by sydesb** [pydio/pydio-core#1026]
The new version of joomla(3.4.7 or 2.5.999) uses a base64-encoded data container to save session data and the plugin of pydio to login doesn’t work anymore. Joomla doesn’t display error message but it doesn’t work.
The doc from joomla : https://docs.joomla.org/J3.x:Backward_Compatibility_in_Joomla_3.4.7
joomla 2.5.999 is here -> https://github.com/PhilETaylor/Joomla2.5.999

**Comment by cdujeu** [comment]
Hummm... Are you 100% sure the regression is linked to this change? Re-reading the code, we don't access nowhere to the joomla content of global $_SESSION... I don't really see where this could be impacted.

**Comment by sydesb** [comment]
No, i'm not sure. I think the problem is the switch of session. The login to pydio is ok but this prevents the login to joomla. With previous version of joomla, everything worked.
The change on joomla(2.5.999)  are ( it's the same with joomla3 ): 
https://github.com/PhilETaylor/Joomla2.5.999/commit/4c1dac9474cf2723d06e5b993c5409c2576257b3
https://github.com/PhilETaylor/Joomla2.5.999/commit/39b8e092fea20ce4c0873384466331fe3839a4ce
https://github.com/PhilETaylor/Joomla2.5.999/commit/cea6de13e077826866f45b44676761313c78bb8c

if it can help you, I think I can lend you a VPS with joomla and pydio, admin access and ftp access for a few days.

**Comment by cdujeu** [comment]
Can you apply 6ae042923c6d80824586c4f730b542f3536b4ffa (pydio auth.remote plugin) and a37018a4a6f1ab96694b09b0202ed961c63b71ee (pydio joomla plugin) and check that it fixes the issue?

**Comment by sydesb** [comment]
Thank you very much, the login works for joomla and for pydio but  with pydio, my account is no longer an admin. My account is super admin in joomla. Is it possible to reset my pydio account ?
Thank you for your great job !

**Comment by kernig** [comment]
Thanks! Did work for us too.

**Comment by cdujeu** [comment]
was fixed in 6.2.2
