### ISSUE TITLE
Introduce Changelog.md

### ISSUE THREAD

**Issue by szepeviktor** [pydio/pydio-core#1027]
Please consider introducing a strict-formatted changelog file and copying the relevant part to tagged releases.
Also it would be nice to fill out every field on https://github.com/pydio/pydio-core/releases/new

Thank you.

**Comment by cdujeu** [comment]
Please see https://github.com/pydio/pydio-core/blob/develop/core/src/conf/RELEASE_NOTE
We'll split dist / src into 2 different repositories one day.
