### ISSUE TITLE
Can't view "People": Function ldap_sort() is deprecated

### ISSUE THREAD

**Issue by matschi-klickme** [pydio/pydio-core#1031]
Hi! When trying to view the "users" section, i get the message "Function ldap_sort() is deprecated" and the page stays emtpy but shows the correct amount of pages. 
Anything else works but i badly need to set some specific user rights. 

http://imagebin.ca/v/2SR4hbX9BoUz

Logs: 

"Jan 05 18:52:28 SERVER php-cgi[22696]: XXX.XXX.XXX.XX        PydioUSER        class.ldapAuthDriver.php        error l.347        message=Function ldap_sort() is deprecated
Jan 05 18:52:28 SERVER lighttpd[22688]: (mod_fastcgi.c.2520) FastCGI-stderr: [PYDIO] IP 131.130.142.98 | user PydioUser | Error | error l.347 | from class.ldapAuthDriver.php | message=Function ldap_sort() is deprecated"

Setup:
Pydio v 6.2.1
PHP 7.0.1
lighttpd/1.4.39
fcgi	2.4.0-11
Linux 4.3.3-2-ARCH #1 SMP PREEMPT Wed Dec 23 20:09:18 CET 2015 x86_64 GNU/Linux

Thanks for your Attention and hard work!

**Comment by cdujeu** [comment]
Interesting thing, there's a discussion about that in http://www.serverphorums.com/read.php?7,1236740,1237770 but it's actually not marked as deprecated on the official php documentation... We'll have to handle that, in-between you would probably simply comment out the line in plugins/auth.ldap/class.LdapAuthDriver.php at line 347 ... 
Charles

**Comment by matschi-klickme** [comment]
Perfect, thanks!

**Comment by mwehr** [comment]
You could also add "@" before the ldap_sort.
```php
if ($limit != -1) {
  //usort($entries, array($this, "userSortFunction"));
  @ldap_sort($conn[$i], $resourceResult, $this->ldapUserAttr);
}
```

regards,

Mario

**Comment by matschi-klickme** [comment]
Works as well :)

**Comment by cdujeu** [comment]
@c12simple is this commited ? use the @ and close the bug?
