### ISSUE TITLE
6.2.1 - Websocket key ingored.

### ISSUE THREAD

**Issue by dragon2611** [pydio/pydio-core#1037]
Looks like the websocket server is completely ingoring the value set in WS Key

To Reproduce

Set a value of WS Key to anything other than the default
Make a request to the websocket.

Seen in the server log

10.0.xxx.xxx - - [17/Jan/2016:21:07:13 +0000] "GET /pydio-websocket/?get_action=ws_authenticate&key=adminsecretkey HTTP/1.0" 200 111 "-" "Incutio HttpClient v0.9"
10.0.xxx.xxx - - [17/Jan/2016:21:07:21 +0000] "GET /pydio-websocket/?get_action=ws_authenticate&key=adminsecretkey HTTP/1.0" 200 111 "-" "Incutio HttpClient v0.9"

**Comment by cdujeu** [comment]
hi, it's "normal" : for the moment you do have to manually update the key in the ws-server.php file.
