### ISSUE TITLE
SFTP not working, testconnection included

### ISSUE THREAD

**Issue by kernig** [pydio/pydio-core#1045]
Hi,

for unknown reasons, pydio fails to connect to various SFTP server using sftp access driver @Port (22).

Symptomatic : 
Create an Workspace for SFTP environment by using a working SFTP test Server.
e.g test.rebex.net
user: demo
pass: password

I could reproduce exactly the connection shows nothing. Previously we did try to connect to our own sftp capable Server which also didnt work.

How to reproduce:

Create a new Workspace
Add a working SFTP connection
give the sftp workspace access for read/write
try to open the new workspace

Here is a Test environment where u can reproduce the error:

a75792.bplaced.net
user :a75792
pass: a75792

ftp: a75792_n.bplaced.net
user : a75792
pass: a75792

DBuser: a75792
pass: a75792
DB: pydio

pydio
http://a75792.bplaced.net/www/
user: admin
password: administrator

Best Regards,

Kernig

**Comment by kernig** [comment]
Additional Info:

bplaced.net does not contain a PHP SSH Plugin.
Therefore we send soon another Test Environment that have it (to reproduce the error).

**Comment by cdujeu** [comment]
Hello @kernig any news on that? Do you send more info?

**Comment by kernig** [comment]
Hi @cdujeu  we gave up on this and are creating a service which downloads the files via ftp. If you are interested in checking this issue, we can provide access to our server, otherwise this can be closed.
