### ISSUE TITLE
allow direct download for shared folders

### ISSUE THREAD

**Issue by fopina** [pydio/pydio-core#1046]
Direct download (public) links are very useful.

When we share a file publicly we can see the direct download link in the "embbed html" box (I believe it should be highlighted somewhere as well, because it is really useful for `curl`s and so on).

But when we share a folder there's no such box (I guess that box wouldn't make much sense). It'd be useful to be able to use direct download links to files in a public shared folder, so we wouldn't have to share each file individually (and having to maintain a long list of changing URLs - due to the share hash in the `file` param).

Thanks

**Comment by ugocupcic** [comment]
:+1: on that one.

**Comment by cdujeu** [comment]
Added in pydio 7 (still in beta :-) )

**Comment by fopina** [comment]
Awesome!
