### ISSUE TITLE
add setting to disable preview option by default when sharing

### ISSUE THREAD

**Issue by Ellega** [pydio/pydio-core#1047]
I wait this from a long time. Preview must be disable by default for 2 big reason:

- Autodownload or not, depend type file is not good for customers experience
- sharing link works all the time with old navigator version not guaranteed with "preview" enable

Disable "Preview" is not a big deal but our users forget this often.
Sharing is a very important features used with our customers. 

I know forum before github but all of this was already posted :-) :
 - https://pydio.com/forum/f/topic/disable-auto-download-with-preview/
 - https://pydio.com/forum/f/topic/disable-preview-option-when-sharing/

Please close this issue if it not planned at all.
But I would appreciate if you consider this enhancement

**Comment by cdujeu** [comment]
We do consider that.
Still, i would like to have a better detection of wether there is an available previewer, and disable by default only if there is none (to avoid auto-download). But we could also add some admin configs to set these options defaults.
-c

**Comment by cdujeu** [comment]
Now editors are better detected

**Comment by Ellega** [comment]
After a quick test with the latest-pydio (10-Mar-2016 09:53	19M)

The public link seems not working
When I test the generated link there is always an error

message in log : 
`	ERROR	z_temp_ef7a52c279c3	error l.77	class.fsAccessWrapper.php	message=Cannot find repository with id f06f87fbd3cbf035fbe6ee9060f6a405\	` 

the `\` at the end of the id is not normal ...

I know it is Dev version. Some works is needed. But Not sure this is normal at this step.

Just for your information :-)

PS : however it is a nice work. I wait the final release with joy

**Comment by cdujeu** [comment]
>> I guess it's on windows server?

**Comment by Ellega** [comment]
Yes : /
