### ISSUE TITLE
Display are empty when there is more 1 page in "doc file" with editor.imagick from pydio 6.2.2

### ISSUE THREAD

**Issue by Ellega** [pydio/pydio-core#1048]
this PR must be roll back or modified : 
https://github.com/pydio/pydio-core/commit/0409cf447e0cd49fd30d15e76a4173057cf16073#diff-57dedfd7868e3b5cac9792df9b34e2ed

otherwise display are empty when there is more 1 page in "doc file" (doc, xls, ...) with editor.imagick

![image](https://cloud.githubusercontent.com/assets/3939543/12989397/af79df8e-d105-11e5-82fe-e631817d7dca.png)

When there are more 1 page in doc file, the process imagick generate several jpg file with index like this : 

![2016-02-11_211128](https://cloud.githubusercontent.com/assets/3939543/12989253/ebaf77da-d104-11e5-976b-be26328a8356.png)

the test control in "class.IMagickPreviewer.php" line 323 to 325 can't be good in this case.

If there is only one page all works fine ...
In all case comment this PR fixe this display issue

**Comment by c12simple** [comment]
Hi,

Can you replace line 324 by
`if(!(is_file($tmpFileThumb) || is_file(str_replace(".jpg", "-0.jpg", $tmpFileThumb)))){`

**Comment by Ellega** [comment]
Hi,
Works fine. Thx

**Comment by Ellega** [comment]
fixed with https://github.com/pydio/pydio-core/commit/f70618611a350d1d6300eb38b956217eb8d2ca16
