### ISSUE TITLE
OCS: Remote ID must be numeric for compatibility with ownCloud

### ISSUE THREAD

**Issue by LukasReschke** [pydio/pydio-core#1065]
At the moment ownCloud is storing the remote ID [inside a `integer` field in the database](https://github.com/owncloud/core/blob/3adb6ae0f50e1a2beee6be889397ffcf2bf45354/apps/files_sharing/appinfo/database.xml#L25-L31). This means that the unique IDs (e.g. `8CC35C69-4805-3B48-8352-684E94708C86`) generated by Pydio will be cut to the first character and type casted.

The impact on this is that unsharing shares as receive is not properly working. Sharing and accessing shares will be possible, what doesn't work is:

1. Charles shares workspace "Test" from Pydio to Lukas's ownCloud
2. Lukas accepts the share
3. Lukas unshares the share after some time

=> Charles will not be able to see that the workspace has been unshared.

Currently changing the DB scheme on our side is not easily possible since the DB migrations are not yet done scripted but automatically. Thus changing to a string here would be quite a migration nightmare for us _at the moment_.  cc @DeepDiver1975 or do you see a possibility to change this easily?

cc @cdujeu @karlitschek

**Comment by cdujeu** [comment]
ok, keep me posted if it's easily changeable, otherwise we can change that.

**Comment by cdujeu** [comment]
do you actually use the generated id ? how do you make this integer unique without a db sequence?

**Comment by LukasReschke** [comment]
> do you actually use the generated id ? how do you make this integer unique without a db sequence?

It's an autoincremented integer on our side. It is used for actions such as unsharing but in combination to the ID we also check whether the random token is correct.

The reason behind having the integer has some legacy reasons in ownCloud. If we would design that system today we would probably also only use one token instead of two. :-/

**Comment by DeepDiver1975** [comment]
> Currently changing the DB scheme on our side is not easily possible since the DB migrations are not yet done scripted but automatically. Thus changing to a string here would be quite a migration nightmare for us at the moment. cc @DeepDiver1975 or do you see a possibility to change this easily?

we should address the database migration topic in the next release - not that easy
