### ISSUE TITLE
USER_SHARED_USERS_LIMIT is not working

### ISSUE THREAD

**Issue by abhdas** [pydio/pydio-core#1069]
I want to limit the number of users can be added to share a folder as workspace. I created a group and apply the plugin parameter "USER_SHARED_USERS_LIMIT" with a value of 10. But still the group user can add the shared users more than the limit (10). Is it a bug or I am doing something wrong?

**Comment by cdujeu** [comment]
Hi, please use the forum instead of gh to ask questions, thx.
