### ISSUE TITLE
ldap AD group integration

### ISSUE THREAD

**Issue by abhdas** [pydio/pydio-core#1070]
I setup an **AD Authentication** integration and allow a specific **memberof (group1)** to pydio **group_path**. Group's (group1) users are imported successfully and total user listing is 3 when choose **'User listing'** as **'Master Only'**. I used 'DB Storage' as secondary instance. Then I created a **user(user1)** under the group (group1) from pydio interface (as admin).  Then if I choose 'User listing' option from secondary instance as 'Both' then only 2 LDAP AD  users (instead of 3) and DB User ('user1') is showing.

**Comment by cdujeu** [comment]
Forum, thx.
