### ISSUE TITLE
Downloading files and/or dir from command line

### ISSUE THREAD

**Issue by rgarrigue** [pydio/pydio-core#1071]
Hi guys

This is a feature request as discussed in [this forum post](https://pydio.com/forum/f/topic/allow-direct-download-link-for-password-protected-share-with-htaccess-prompt/#post-98814).

I'm gonna summarize it with the exemple from my the post

> The thing I’ld like to be able to do is retrieve a file in a single command line, either giving the share url, or giving file url+login+password, or file url + certificate, pydio providing the api or the “if cli client then redirection to ddl”.

Thanks & regards

**Comment by cdujeu** [comment]
Now doable with curl + webdav, for both standard and shared files.

**Comment by rgarrigue** [comment]
Thanks !
