### ISSUE TITLE
Scroll does not work in Chrome.

### ISSUE THREAD

**Issue by atticusgrey** [pydio/pydio-core#1073]
Hello everyone,

It's been posted in the forum but seemed to of been abandoned. [I didn't post it but it is found here.](https://pydio.com/forum/f/topic/scrolling-doesnt-work-in-chrome/) Let me copy the gist of it here.

> I’m having the same problem on two windows 10 computers myself. Chrome 48.0.2564.116 m (64-bit) on both. Both with and without extensions. It does scroll in Firefox. I’m using a Logitech g502 mouse, but it does not scroll with any other generic usb mouse either. And then only sometimes am I able to scroll using the sidebar If there was an issue made somewhere else I’ll be glad to head over there too.

> Also, I don’t know if it might be related or not, but mousing over some menus, mostly when in settings, the mouse cursor seems to change to ibeam like I’m highlighting it instead of just selecting it. Screenshot here.

If I can include any more info feel free to let me know.

Thanks!

**Comment by cdujeu** [comment]
we'll try (again) to reproduce that)

**Comment by sagaru** [comment]
Works fine for me with the same chrome version. Maybe can you show us via teamviewer session?

**Comment by atticusgrey** [comment]
What are some details you're looking for? I can make a simple gif to show what it's doing.

**Comment by cdujeu** [comment]
A remote session could really interesting to really feel what's happening, and eventually use the chrome developer tools to see where things are going wrong. You can pm on team (at) pyd (dot) io
Thx

**Comment by atticusgrey** [comment]
Hello Guys,

I'll be glad to do a teamviewer session if you want to let me know when and
how you guys would like to do it.

On Fri, Mar 11, 2016 at 7:32 AM Charles du Jeu <notifications@github.com>
wrote:

> A remote session could really interesting to really feel what's happening,
> and eventually use the chrome developer tools to see where things are going
> wrong. You can pm on team (at) pyd (dot) io
> Thx
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pydio/pydio-core/issues/1073#issuecomment-195416391>.
>
-- 

Thanks!

-Nick

**Comment by cdujeu** [comment]
@atticusgrey please send us a direct email to the address i've put before :-)

**Comment by cdujeu** [comment]
Definitely a conflict with a Chrome Extension. @atticusgrey will try to find the problematic one and we'll see if we can either find a fix or at least advertise the problem.

**Comment by atticusgrey** [comment]
Thanks for helping me troubleshoot that Charles. I found the problem with Imagus, a commonly used extension that opens a photo simply by hovering over it. It is not allowing Pydio to scroll.
