### ISSUE TITLE
scrolling issue in left panel with pydio 6.3.1

### ISSUE THREAD

**Issue by Ellega** [pydio/pydio-core#1081]
![2016-03-14_104805](https://cloud.githubusercontent.com/assets/3939543/13740833/1b44ae52-e9d3-11e5-93ac-4d9cda8c8119.png)

**Comment by cdujeu** [comment]
@Ellega can you split this in two separate issues ? First = scrolling issue in left panel, Second = Action.cart adaptation

**Comment by Ellega** [comment]
done
