### ISSUE TITLE
Zoho editor can't record file xls, ppt (pydio 6.3.1)

### ISSUE THREAD

**Issue by Ellega** [pydio/pydio-core#1093]
For kill any doubt : 

Tested without and with my PR https://github.com/pydio/pydio-core/pull/1091 and https://github.com/pydio/pydio-core/pull/1092 with file without special character (accent, ...)

**Comment by cdujeu** [comment]
Mmmmm, you KNOW that this part is always a bit tricky to setup :-) : are you assuming here that it's 6.3.1 specific or not ? If not 100% sure I close and we treat that in the forum first.

**Comment by Ellega** [comment]
Indeed I make a mistaske in my external url for Z-Agent on my server test local. 

From a repository, Recording  works fine now. 
From a public minisite, recording works well.

But from a single file sharing, recording not working
Zoho says "file correctly recorded"
but it is not true on Pydio side if you re-open this file.

**Comment by cdujeu** [comment]
Working for me. 
My scenario : 
> Share a file with a specific user
> Login as this user, I can see the file in my "Shared Files" workspace
> Edit file, save, close Zoho
> Re-open file, the modifs are there.
Same scenario for you?

**Comment by Ellega** [comment]
not same scenario. But your's is more logic :-)
tested your's. I confirm this works with doc, docx.

however recording from repo or shared repo don't works with xls, ppt ...

**for file xls there is always this message :**

![2016-03-26_084116](https://cloud.githubusercontent.com/assets/3939543/14059054/e575f04a-f334-11e5-97a9-ccad9d64ef58.png)

**for file ppt zoho stay on this message :** 

![2016-03-26_093618](https://cloud.githubusercontent.com/assets/3939543/14059074/6d6aae86-f336-11e5-8ded-4babdfa0a2ba.png)

I'll let you decide what you want. Close or not this issue ...
it is for help. 
it is not used in my business. 
zoho can help for personal use
but it is not usable in business seriously :-)

**Comment by cdujeu** [comment]
Could there be an issue with your api key ? I can open and save XLSX without any issue. 
I do have a problem opening a PPTX.

**Comment by Ellega** [comment]
api key ? ok I wiil check that ...

no problem in my side for open pptx

You can try this sample file here : 
https://oit.utk.edu/instructional/strategies/toolkit/Anonymous%20Assets/sample%20PowerPoint%20presentation.pptx

Works fine 

![2016-03-27_222612](https://cloud.githubusercontent.com/assets/3939543/14067711/40c7642e-f46b-11e5-8994-230e0a16d04e.png)

**Comment by cdujeu** [comment]
Well closing that one for now. Pptx should be working since I merged your PR.

**Comment by Nanomani** [comment]
for clore completely this story.
if your server is external with a public certificate, URL Agent must be accessible and set with `http` not `https` in all case. Works perfectly now.
