### ISSUE TITLE
Cannot create public link if Password is configured as mandatory by admin

### ISSUE THREAD

**Issue by mwehr** [pydio/pydio-core#1095]
Hi,

Just testing around with the develop branch. If I open the sharing dialog for a folder the first tab only shows a check box with "Enable Public Link". and "This file is not currently accessible"....
It seems that in the ShareDialog.js around line 733
```PHP
render: function render() {

            var publicLinkPanes;
            if (this.props.linkData) {
                publicLinkPanes = [React.createElement(PublicLinkField, {
                    showMailer: this.props.showMailer,
                    linkData: this.props.linkData,
                    shareModel: this.props.shareModel,
                    editAllowed: this.props.authorizations.editable_hash,
                    key: "public-link"
                }), React.createElement(PublicLinkPermissions, {
                    linkData: this.props.linkData,
```
"this.props.linkData" is undefined. 
The repository is a meta mount CIFS share.

regards

Mario

**Comment by cdujeu** [comment]
Did you actually try to check this checkbox?

**Comment by cdujeu** [comment]
If the folder is not shared initially, it's normal that there is no linkData

**Comment by mwehr** [comment]
If I check the checkbox, a warning shows up that a password is need :-)
"Please set a password and make sure it's long enough!"
I've set passwords mandatory.
There is no way to set password, etc right now.

**Comment by cdujeu** [comment]
Did you configure something to force password on every public link?

**Comment by mwehr** [comment]
Yes I've set Password mandatory for public links.

**Comment by mwehr** [comment]
The fun thing is even if i disable password mandatory in public links the message:
"Please set a password and make sure it's long enough!"
is disabled.
Caches are cleared, server restarted.

**Comment by cdujeu** [comment]
yep working on that, it's a bug.
Additionally, even if password is set at first share, it's still possible to reset password at update, even if it's mandatory, to be fixed as well.

**Comment by mwehr** [comment]
thumbs up
