### ISSUE TITLE
Accessing a public link on unmounted CIFS mount fails 

### ISSUE THREAD

**Issue by mwehr** [pydio/pydio-core#1097]
Accessing a public link on a currently unmounted CIFS mount fails with:
"No repository found for active User"

**Comment by cdujeu** [comment]
Is it new to 6.3.1?

**Comment by mwehr** [comment]
I think this was working in Pydio 6.2, or I'm wrong ?

**Comment by mwehr** [comment]
It looks like there is some kind of race condition between mount and unmount calls.

**Comment by cdujeu** [comment]
is it linked to #1098  ?

**Comment by mwehr** [comment]
Jup, ,.. commit (1a044c88591c4a5462a52884ec0fd860398baf3b) fixes the problem.
