### ISSUE TITLE
Problem with shared workspace.

### ISSUE THREAD

**Issue by mwehr** [pydio/pydio-core#1098]
Occurs in latest Pydio from develop branch.
A invited user can first access a shared workspace from a meta.mount. After switching to another workspace the shared workspace gets unmounted and after switching back the remount fails.

to reproduce:
meta.mount CIFS
configured with: remove mount point on unmount
User A:
meta.mount CIFS

User B:
meta.mount CIFS

User A creates a shared workspace from a folder of his meta mount

Login with User B. Access the shared workspace from User A and then switch to another workspace.
Now the shared workspace from user A gets unmounted. Then switch back to the shared workspace from user A. Now an error message "Can't find base path for repository" is display.

**Comment by mwehr** [comment]
It looks like there is some kind of race condition between mount and unmount calls in the meta.mount/class.FilesystemMounter
It seems unmount runs between the presence check of the mount directory and the mount execution

**Comment by cdujeu** [comment]
mario, just to make sure, can you verify whether it was working on 6.2.2 or not? Nothing specific changed on that side recently.

**Comment by mwehr** [comment]
Yes it was working just fine on 6.2.2
I noticed that a change beween the work spaces unmounts the currently not visible worspace. I could be wrong but I did't notice this behavior on 6.2.2?

**Comment by mwehr** [comment]
ok,.. i think i've fond it,..no race condition :-)
It seems that a shared workspace does not inherit the config from its parent. In this paticular situation the shared workspace is missing the "create" key which breaks the mount because of the missing mount folder.

**Comment by cdujeu** [comment]
no actually, we should pass this directly at the shared workspace creation, we may have broken something i will check.

**Comment by cdujeu** [comment]
@mwehr can you check the commit?

**Comment by mwehr** [comment]
Jup, great,.. commit (1a044c88591c4a5462a52884ec0fd860398baf3b) fixes the problem.
thx!
