### ISSUE TITLE
Deletion of shared folder (workspace) silently fails

### ISSUE THREAD

**Issue by mwehr** [pydio/pydio-core#1099]
Trying to remove a shared folder (workspace) silently fails.
It seems there is a problem with the transmitted hash value and the object_id value use in ajxp_simple_store. 

see class.ShareStore.php 
line 406 -> loadShare() 
line 180 ->simpleStoreGet()

**Comment by cdujeu** [comment]
Hi mario, are you working on 6.3.1 on or on latest code ? I commited something on that topic yesterday

**Comment by mwehr** [comment]
I'm working on latest from develop branch.

**Comment by mwehr** [comment]
I did some more investigations and reset my db.
It look looks like the problem is in class.ShareStore.php
Line : 417
```PHP
if($repo != null){
  $element = $share["REPOSITORY"];
  $this->testUserCanEditShare($repo->getOwner(), $repo->options);
  $res = ConfService::deleteRepository($element);
  if ($res == -1) {
    throw new Exception($mess[427]);
   }
}

$element already has set the right repo id. but the 
$element = $share["REPOSITORY"]
call resets $lelement to null.
