### ISSUE TITLE
Public Link from a single file under subpath fails in minisite 

### ISSUE THREAD

**Issue by mwehr** [pydio/pydio-core#1100]
Creating a public link from a file under a subpath seems missing the subpath component.
Occurs in develop branch

**Comment by cdujeu** [comment]
do you mean you create a public link when already inside a minisite?

**Comment by mwehr** [comment]
no I just created a minisite from one single file which is located in a subpath:
folder_1 -> folder_2 -> shared_file

**Comment by cdujeu** [comment]
I cannot reproduce that one, working perfectly for me. 
Are you on a specific workspace ?

**Comment by mwehr** [comment]
The workspace is a CIFS meta mount

**Comment by cdujeu** [comment]
can you just check with a standard workspace (fs only) ? same issue?

**Comment by mwehr** [comment]
It works if I disable xsend-file.
I will test a standard workspace asap.

**Comment by mwehr** [comment]
I think I I've found the Problem.
In /access.fs/class.fsAccessDriver.php
line:1480
```PHP
if ($this->getFilteredOption("USE_XSENDFILE", $this->repository) && AJXP_MetaStreamWrapper::actualRepositoryWrapperClass($this->repository->getId()) ==   "fsAccessWrapper") {
  if(!$realfileSystem) $filePathOrData = fsAccessWrapper::getRealFSReference($filePathOrData);
  $filePathOrData = str_replace("\\", "/", $filePathOrData);
  $server_name = $_SERVER["SERVER_SOFTWARE"];
```
it seems that the static getRealFSReference call should be used from AJXP_MetaStreamWrapper.

**Comment by ghecquet** [comment]
Thanks very much,  It works fine when using the AJXP_MetaStreamWrapper.

I've changed the XACCELREDIRECT handler too as it was doing the same thing
