### ISSUE TITLE
Drag and Drop on Default repo ("my file", "Common") is not authorised (pydio 6.3.1)

### ISSUE THREAD

**Issue by Ellega** [pydio/pydio-core#1105]
Drag and Drop on Default repo ("my file", "Common") is not authorized (pydio 6.3.1).

Drag and Drop on new repo (FS, FTP) works fine.
Menu "Transfert" on default repo works fine.

- Tested after 6.2.2 updated to 6.3.1
- Then tested after 6.2.2 updated to 6.3.1 + pydio-latest  (22-Mar-2016 15:35)

Always the same bug.

![2016-03-22_163652](https://cloud.githubusercontent.com/assets/3939543/13957927/7e46d206-f04e-11e5-81ae-f5f162e9d04e.png)

**Comment by cdujeu** [comment]
Hi Ellega, nice spot, I JUST fixed that :-) not even commited yet.
