### ISSUE TITLE
Delete a file must delete also the associed  file in "cache / imagick_xxxx"

### ISSUE THREAD

**Issue by Nanomani** [pydio/pydio-core#1108]
Delete a file must delete also the associed files in "cache / imagick_xxx".
otherwise if you upload a new file with the same name + same extension, thumbmail, preview and full preview are not updated. Pydio uses the first thumbmail, preview and full preview files generated.

**Comment by cdujeu** [comment]
There is already of hook for that normally.

**Comment by cdujeu** [comment]
but not working, i can confirm

**Comment by cdujeu** [comment]
no, my bad : working for me.

**Comment by cdujeu** [comment]
I delete a PDF, then reupload another file with the same name, the thumb is correct.

**Comment by Ellega** [comment]
ok I have no many time
view that on ppt file
I test on more files ASAP

**Comment by Ellega** [comment]
I confirm this works with .pdf .jpg not with .doc .docx .xls .xlsx .ppt .pptx

**Comment by cdujeu** [comment]
Ah, so that would be unoconv related.

**Comment by Nanomani** [comment]
no success :(
files in imagick_full not deleted

**Comment by cdujeu** [comment]
ok, i'll digg that.

**Comment by cdujeu** [comment]
Ok, that one should be working (replace whole function, and remove my previous suggestion as well).
```

    public function deleteImagickCache($oldNode, $newNode = null, $copy = false)
    {
        if($oldNode == null) return;
        $oldFile = $oldNode->getUrl();
        // Should remove imagick cache file
        if(!$this->handleMime($oldFile)) return;
        if ($newNode == null || $copy == false) {

            // Main Thumb
            LocalCache::clearItem("imagick_thumb", $oldFile);

            // Unoconv small PDF
            $thumbCache = LocalCache::getItem("imagick_thumb", $oldFile, false);
            $unoFile = pathinfo($thumbCache->getId(), PATHINFO_DIRNAME).DIRECTORY_SEPARATOR.pathinfo($thumbCache->getId(), PATHINFO_FILENAME)."_unoconv.pdf";
            if(file_exists($unoFile)){
                unlink($unoFile);
            }

            $cache = LocalCache::getItem("imagick_full", $oldFile, false);
            // Unoconv full pdf
            $unoFile = pathinfo($cache->getId(), PATHINFO_DIRNAME).DIRECTORY_SEPARATOR.pathinfo($cache->getId(), PATHINFO_FILENAME)."_unoconv.pdf";
            if(file_exists($unoFile)){
                unlink($unoFile);
            }
            $prefix = str_replace(".".pathinfo($cache->getId(), PATHINFO_EXTENSION), "", $cache->getId());
            // Additional Extracted pages
            $files = $this->listExtractedJpg($oldFile, $prefix);
            $cacheDir = (defined('AJXP_SHARED_CACHE_DIR')?AJXP_SHARED_CACHE_DIR:AJXP_CACHE_DIR)."/imagick_full";
            foreach ($files as $file) {
                if(is_file($cacheDir."/".$file["file"])) {
                    unlink($cacheDir."/".$file["file"]);
                }
            }
        }
    }

```

Plus another fix to make sure there is no browser-side caching by sending a random seed in the url. Commit to come.

**Comment by Nanomani** [comment]
I must replace "LocalCache" by "AJXP_Cache" otherwise I have an error in log php 

> PHP Fatal error:  Class 'LocalCache' not found> 

So files in imagick_full and imagick_thumb are correctly deleted

but other fix to make sure there is no browser-side caching seems not working
I need to clean browser cache to actualise the good full preview

**Comment by cdujeu** [comment]
Can you try to get the JS part of this commit ? https://github.com/pydio/pydio-core/commit/58a3c7a18c974737d1a61dd584d2478c1306e822
The LocalCache / AJXP_Cache is indeed a naming issue because the new branch has a full reorganisation of classes, namespaces, etc.. But basically with AJXP_Cache you should be good to go indeed.

**Comment by Nanomani** [comment]
All is good this time. :-) 
thx
