### ISSUE TITLE
There is no way for change Share label (pydio 6.3.1)

### ISSUE THREAD

**Issue by Ellega** [pydio/pydio-core#1111]
Share description can be changed but not the label. 

By default pydio takes the file name for the label.
If you change the file name, the label doesn't change
There is no way for doing that.

![2016-03-24_122716](https://cloud.githubusercontent.com/assets/3939543/14015803/fe61a0ce-f1bb-11e5-907f-c96a006e59d7.png)

![2016-03-24_122820](https://cloud.githubusercontent.com/assets/3939543/14015804/fe622cce-f1bb-11e5-9f45-61f564de229d.png)

![2016-03-24_122835](https://cloud.githubusercontent.com/assets/3939543/14015805/fe629556-f1bb-11e5-8ca8-d0b81597fab8.png)

**Comment by cdujeu** [comment]
Mmm, indeed, we had removed that for the sake of user-friendliness (avoid having tooo many fields). But that should auto-update if filename change. Would that be ok for you?

**Comment by Ellega** [comment]
perfect :-)
