### ISSUE TITLE
Colour uploading progress bar not the same if firefox or chrome (pydio 6.3.1)

### ISSUE THREAD

**Issue by Ellega** [pydio/pydio-core#1112]
Colour uploading progress bar not the same if firefox or chrome (pydio 6.3.1)

not a big deal. But the red colour with Chrome sends the feeling to user there is a pb in uploading.

tested with the latest firefox and latest chrome without extension.

**With Chrome**

![2016-03-24_145238](https://cloud.githubusercontent.com/assets/3939543/14019224/fb9efee8-f1d1-11e5-8df5-01ecc500e807.png)

**With Firefox**

![2016-03-24_145430](https://cloud.githubusercontent.com/assets/3939543/14019230/ff3c4d94-f1d1-11e5-842a-060dfdf741c9.png)

**Comment by cdujeu** [comment]
... 
the idea is that we can now customize this color using CSS, via a nice SVG hack that actually does not work in FF / IE. 
Still, it's an interesting remark that the color conveys the wrong message. Should be green then...
