### ISSUE TITLE
No auto update displayed file list after upload in Minisite if accent in path shared folder (pydio 6.3.1)

### ISSUE THREAD

**Issue by Ellega** [pydio/pydio-core#1113]
No auto update displayed file list after upload in Minisite if accent in path shared folder

**Comment by Ellega** [comment]
Something seems break minisite in particular situation.
I can't reproduce this every time.
I repost new issue if needed when I have more precise info.

**Comment by Ellega** [comment]
error message in pydio log : 

`error l.510	class.ChangesTracker.php	message=stat(): stat failed for pydio://admin@1/path/my file`

**Comment by cdujeu** [comment]
i can't reproduce that one either. Maybe it's linked to #1116 ?

**Comment by Ellega** [comment]
I think so ...

**Comment by Ellega** [comment]
I confirm linked to #1116
