### ISSUE TITLE
Username with accented characters are unable to authenticate

### ISSUE THREAD

**Issue by scarmic** [pydio/pydio-core#1115]
Hello everybody.
I'm having an issue with the Pydio Community 6.2.2 and Active Directory external authentication.
Some usernames have accented characters (è, ò, etc..);
I verified and both os and php language are set into UTF-8.
**Users are unable to authenticate**. In the log files seems that those chars are truncated by the auth plugin.
For example: salomè —> salom

Any ideas?

Thanks!

**Comment by cdujeu** [comment]
Hi, 
Currently in Pydio only email characters are supported for user logins. No way to change these users id's in the ldap ? 
-c

**Comment by scarmic** [comment]
Thank you Charles,
I never read of such limitation. So now I'll change AD users id's. Maybe it will be a future enhancement for Pydio?

**Comment by cdujeu** [comment]
Maybe yes! We should definitely update the doc. Closing for now.
