### ISSUE TITLE
Pb minisite with metasyncable (function updateNodesIndex) if shared folder with accent (pydio 6.3.1) 

### ISSUE THREAD

**Issue by Ellega** [pydio/pydio-core#1116]
error message in pydio log : 

`error l.510	class.ChangesTracker.php	message=stat(): stat failed for pydio://admin@1/path/my file`

Edit 1 : the file is correctly uploaded but there is this : 

![2016-03-24_153824](https://cloud.githubusercontent.com/assets/3939543/14023015/baa7ee16-f1e2-11e5-844d-886967de796a.png)

**Comment by Ellega** [comment]
I m prettry sure that all of this is indroduced with a new commit wtih latest-pydio.
I need time I don't have for more serious invetigation ....

**Comment by cdujeu** [comment]
I can't reproduce that one.

**Comment by Ellega** [comment]
After a very quick search. It is a specific bug with Win OS.

in `class.ChangesTracker.php` line 510 ` $stat = stat($newNode->getUrl());`

`$newNode->getUrl()` send value with mixed charset type like this : 

`pydio://admin@1/Ã©tÃ©/Annonce dégats des eaux-1.docx`

file charset is correct but not the path

**Comment by cdujeu** [comment]
@Ellega i still cannot reproduce that one, can you just check that it was not linked to the previous issues by recreating a new folder / new share / new scenario ? 
-c

**Comment by Ellega** [comment]
Arf ! 

tested on new clean install with latest-pydio (27-Mar-2016 19:02) with new folder / new share
nothing more. Always the same bug with command `stat($newNode->getUrl());` line 510. 

Sample question . Are you tested with IIS ? :-)

**Comment by cdujeu** [comment]
of course :-) otherwise there are no encoding issues. will retest

**Comment by cdujeu** [comment]
still working with a clean install, I create a minisite on folder /Répertoire, then access this and upload files with or without accents and all is working. IIS of course. Do you have a correct collation of your DB ? Pydio encoding value set to .. ?

**Comment by Ellega** [comment]
Sorry to take your percious time
I doubt why if I have a mistake in charset global config (db, pydio) can be bug only in aparticular part 
But No body is perfect. :-)
I recheck all my config.... (collation  db : utf8_unicode_ci)

My scenario
 - clean new install
 - in repo "my files" create a new root folder with accent "été" 
 - share folder "été" (public link type)  
 - upload file (with or not accent)

use Chrome (not firefox who not displayed error message, you only see the autorefresh is not) 

But I continue to investage...

**Comment by cdujeu** [comment]
Mmm, yes I do the same. IIS. MySQL same collation. 
Do you actually set a charset in pydio? via conf/bootstrap_conf.php ? 
No problem with my time. I really want that we release 6.4.0 on wednesday, so it's time to fix everything!

**Comment by Ellega** [comment]
Apache (2.4.18 x86) not IIS + php 5.6.19 . But must make no difference...
(class COM is disable in setting command line php for me)

Windows-1252 in `encoding.php`
uncomment `define("AJXP_LOCALE", "");` in bootstrap_conf.php

in doubt I have tried many other config without success.

**Comment by cdujeu** [comment]
hum, similar setup, except iis instead of apache. BTW, do you use apache on windows in prod??? 
That said, can you do a last test with a 6.2.2 on that same setup ? I still can't reproduce that....

**Comment by Ellega** [comment]
Yep, Apache in Prod. Server test have strictly the same config that server prod.
And yes too for test on 6.2.2 and more older. I have always this bug ... O_o
This was never detect because our politic is to disable minisite on folder sharing.  

I know where is the root of the problem for "ministe"
If I upload the same file in same folder directly from FS repo $node is correctly build with correct encoded value. Not from the minisite .

**AJXP_Node Object if upload from REPO**

![2016-03-29_111239](https://cloud.githubusercontent.com/assets/3939543/14103359/0afeb866-f5a0-11e5-8a2a-c96dd6a3ac4c.png)

**AJXP_Node Object if upload from MINISITE**

![2016-03-29_111213](https://cloud.githubusercontent.com/assets/3939543/14103363/0c8f58b6-f5a0-11e5-9de9-e83d8dd9ec9e.png)

Just to need to know why and where for minisite this value is not correctly encoded from the beginnig
All value seems correct in DB. It is a specific "pb" for minisite for me.

don't worry. Not a problem for now. I will take time to track this in my side. 
Not the first time, I need to PR a `SystemTextEncoding`  here or there :-)
just need more time. But it is not so easy for me :-)

**Comment by cdujeu** [comment]
Let's put that for following bugfixes release then :-)

**Comment by Ellega** [comment]
fix this issue : 

in `class.ShareCenter.php` line 975
(private function findMirrorNodesInShares)

replace 

`$relative = substr($currentRoot, strlen($parentRoot));`

by

`$relative = SystemTextEncoding::toStorageEncoding(substr($currentRoot, strlen($parentRoot)));`

PR ?

**Comment by cdujeu** [comment]
ok, i'll test it and add it "in extremis" :-)
