### ISSUE TITLE
PowerFS in conjunction with xsendfile deletes file to early

### ISSUE THREAD

**Issue by mwehr** [pydio/pydio-core#1117]
If enabled PowerFS feature is use in conjunction with xsendfile the file is removed to early.
The current code uses script a shutdown hook to unlink the archive file at script end.  With xsendfile enabled the upload process is handover to Apache and so the script exists and removes the generated archive file to early.

A quick fix would be to check the usage of the xsendfile and don't register the shutdown hook?
class.PowerFSController.php
line:86
```PHP
case "postcompress_download":
  $archive = AJXP_Utils::getAjxpTmpDir().DIRECTORY_SEPARATOR.$httpVars["ope_id"]."_".AJXP_Utils::sanitize(AJXP_Utils::decodeSecureMagic($httpVars["archive_name"]), AJXP_SANITIZE_FILENAME);
  $fsDriver = AJXP_PluginsService::getInstance()->getUniqueActivePluginForType("access");
  if (is_file($archive)) {
    if (!isset($fsDriver->driverConf['USE_XSENDFILE'])){
      register_shutdown_function("unlink", $archive);
    }
    $fsDriver->readFile($archive, "force-download", $httpVars["archive_name"], false, null, true);
    } else {
      echo("<script>alert('Cannot find archive! Is ZIP correctly installed?');</script>");
     }
break;
```
hmm,.. just found the topic in the [forum](https://pydio.com/forum/f/topic/action-powerfs-bug-postcompress_downloads-fails-when-xsendfile-enabled/)

**Comment by ghecquet** [comment]
It will be available in next release
