### ISSUE TITLE
Purge old feed data

### ISSUE THREAD

**Issue by mwehr** [pydio/pydio-core#1118]
Hi,

Are there any site effects if we periodically purge old feed items to keep the database size small?
For example:
Purge all items ajxp_feed if they are more than 25 items per user and if they are older than 14days....
```SQL
select * from ajxp_feed as feed, 
(select user_id from ajxp_feed group by user_id Having count(*) > 25) as del_feed
where feed.user_id = del_feed.user_id and edate < (current - 14d)
```

regards

Mario

**Comment by cdujeu** [comment]
Hi Mario, 
No there should not be any side effect.
-c
