### ISSUE TITLE
Mail Digest, one user selects plain text, all get plain text

### ISSUE THREAD

**Issue by anatomism** [pydio/pydio-core#1121]
Testing the Mail Queue, which works well if triggered directly from Linux CRON (i.e. not use the built in scheduler, which still requires some work)

If one user selects 'No' to Get HTML emails under their user preferences, it seems everyone gets a plain text email. Tried with 3 different users, repeatable bug.

Tom

**Comment by cdujeu** [comment]
Hi Tom, 
Thanks for reporting. Just to make sure, are you using the latest dev code or the 6.3.1 ?
-c

**Comment by anatomism** [comment]
6.2.2 core, with certain 'modules' of the latest dev

Core.mailer
Phpmailerlite
Scheduler

Above 3 were from dev as of 25/03

Tom
