### ISSUE TITLE
Fixes disabling of dashboard form elements when set to editable false

### ISSUE THREAD

**Issue by mwehr** [pydio/pydio-core#1124]
Hi,

This fixes disabling of dashboard form fields if they have set 'editable' = false in the manifest.xml
In class.FormManager.js the 'editable' key isn't used.
Add at line 78 
```javascript
if (param.get('editable')) {
  var disabled = ! JSON.parse(param.get('editable'));
}
```

regards 

Mario

**Comment by cdujeu** [comment]
hey mario!
do you have an example of parameter where this can be easily verified?
thx
-c

**Comment by mwehr** [comment]
Jup,.. set editabled='false' for the 'USER_DISPLAY_NAME' and 'email' keys in core.conf.
The corresponding form fields in the dashboard should be disabled.
