### ISSUE TITLE
enable shared public link on folder with accent do nothing if repo FTP

### ISSUE THREAD

**Issue by Ellega** [pydio/pydio-core#1125]
enable shared public link on folder with accent do nothing if repo FTP

 - create repo ftp
 - create folder with accent
 - share this folder with public link type
 - click on "enable public link" do nothing (page stay inchanged)

![2016-03-28_184532](https://cloud.githubusercontent.com/assets/3939543/14083359/8a315296-f515-11e5-84b3-adebfa675e9a.png)

**Comment by cdujeu** [comment]
Working for me, but only if **I set the encoding parameter of the workspace** (to UTF-8 in my case).

**Comment by Ellega** [comment]
Indeed. I confirm. Thx
