### ISSUE TITLE
Fixes sorting of groups by string

### ISSUE THREAD

**Issue by mwehr** [pydio/pydio-core#1126]
Hi,

I've 2 custom groups
Root
Tester
Currently the two groups are not sorted correctly because the AJXP_GRP_ test fails.
The following should fix the sorting of groups by string. 
The class.AbstractAjxpUser.php the orderRoles function should be changed:
at Line 558:
```PHP
if(strpos($r2, "AJXP_USR_") === 0) return -1;
  // Two groups, sort by string, will magically keep group hierarchy
  if(strpos($r1, "AJXP_GRP_") === false && strpos($r2, "AJXP_GRP_") === false) {  
    return strcmp($r1,$r2);
}
```

regards,

Mario

**Comment by cdujeu** [comment]
hi mario
too late for that one. Let's put in on 6.4.1
