### ISSUE TITLE
Remote shares & Permissions issues

### ISSUE THREAD

**Issue by ghecquet** [pydio/pydio-core#1129]
By default, a folder that has been shared remotely does not give 'write' permission to the end user.

However, when the end user writes in the directory, there is no error message being triggered.

**Comment by cdujeu** [comment]
Recheck whole federated sharing scenario in p7

**Comment by cdujeu** [comment]
1/ Access.webdav driver does not read permissions from server (see PydioStreamWrapper::stream_stat() method, we build 777 permissions by default).
2/ Rename silently fails - When @ is removed in FSAccessDriver call, throws in fact another error: VM3286:1 Argument 1 passed to GuzzleHttp\Command\AbstractClient::execute() must implement interface GuzzleHttp\Command\CommandInterface, null given, called in /Users/charles/Sources/pydio-core/core/src/plugins/core.access/src/Stream/Stream.php on line 534 and defined
3/ Upload / Mkdir does not fail either, sends back the notification of a new folder created even if it's false (disappear when reloading list).

**Comment by cdujeu** [comment]
We have to both implement ACL's in Server and be able to read them in the webdav driver.
