### ISSUE TITLE
REST api standards & functionalities

### ISSUE THREAD

**Issue by AresAndy** [pydio/pydio-core#1131]
Many API functions need to be redesigned so that they all follow just one standard over the three available: 
1) JSON object as POST-DATA
2) Encoded JSON as http(s) query parameter
3) Usual query parameters

Other functions do absolutely nothing, like user_update_role, create_repository.. (They usually return a SUCCESS xml response, but nothing actually happened).
Moreover, the share function needs to be able to share something as a workspace, currently it only creates minisite links (public or private, doesn't matter)

**Comment by cdujeu** [comment]
Hi @AresAndy 
Would you have any skills / motivation to contribute on that?

**Comment by AresAndy** [comment]
Hi @cdujeu,
I could give an hand somewhere, I guess. The problem is that my job takes plenty of time away from me. I don't know if doing Pydio for a living is a plausible option, but if it is, my answer tends towards a "yes".. As a community member only, is pretty much a "Sorry, I don't have enough time on my hands".. I just can note down some wishes/troubles I found and report them at random times..

**Comment by cdujeu** [comment]
This is a work-in-progress, we are working on api/v2/, following more standards.

**Comment by cdujeu** [comment]
Api v2 now officially published

**Comment by cdujeu** [comment]
@AresAndy FYI
https://pydio.com/en/docs/references/api/v2

**Comment by AresAndy** [comment]
@cdujeu Thanks for the news. Unfortunately changed job and I'm not working with web services anymore, so I can't check out the patch. 
Best regards, 
AresAndy

**Comment by cdujeu** [comment]
no worries, just informing :-)
