### ISSUE TITLE
unknow parsing error on update event on a non-indexed folder

### ISSUE THREAD

**Issue by Nanomani** [pydio/pydio-core#1132]
unknow parsing error on update event on a non-indexed folder

scenario : 
 - create an folder in "my file" folder from outside pydio (ex explorer windows)
 - rename || copy || rename || delete this folder, pydio displayed "unknow parsing error"

if you index folder before action all works fine.
if you create folder from pydio ui all works fine.
tested with accent and without accent in folder name.

clearly not an encoded issue this time :-)
more a problem in index process for this folder never indexed.

![2016-04-14_185959](https://cloud.githubusercontent.com/assets/3939543/14536728/27c8503e-0274-11e6-8a4f-a30be7fdab34.png)

In log : 
	

> ERROR	admin	updateNodesIndex	meta.syncable	There was an update event on a non-indexed folder (/dossier1/dossier2), relaunching a recursive indexation!	

same bug with 6.2.2 and 6.4.0

edit 1 :  

process "index" seems correct. A new correct entry is added in table "index" for folder nerver indexed
issue must be in related action to index process

**Comment by cdujeu** [comment]
@Nanomani could you retest on 6.5.1 ? no error for me now.
thx.

**Comment by Nanomani** [comment]
Yes, fixed. Thx
