### ISSUE TITLE
if entries in the table "ajxp_feed", the synthesis info for "repo" in welcome page is not displayed (pydio 6.4.0)

### ISSUE THREAD

**Issue by Nanomani** [pydio/pydio-core#1133]
if there are entries in the table ajxp_feed, the synthesis info for "repo" in welcome page is not displayed.

![2016-03-31_152328](https://cloud.githubusercontent.com/assets/3939543/14177101/ffa2b402-f754-11e5-9461-214ef88005af.png)

scenario : 

 - new clean install 
       => synthesis info for each "repos" in welcome page is displayed

 - make an new event on file (upload , delete, ..) 
       => synthesis info for the "repo" where there is a new event is NOT displayed

 - delete ALL entries in the table ajxp_feed related to this repo
       => synthesis info for this "repos" in welcome page is re-displayed

![2016-03-31_152438](https://cloud.githubusercontent.com/assets/3939543/14177107/0566031c-f755-11e5-9b23-5af1a6a39dce.png)

**Comment by cdujeu** [comment]
Windows server?

**Comment by Nanomani** [comment]
Yep. Apache on Windows.
But you already know :-)

**Comment by cdujeu** [comment]
Still active?

**Comment by Nanomani** [comment]
Still active?
After upgrade 64.2 to 6.5.1 ?

If yes I can't test nothing after that.
I have a beautiful "Oups, cannot find this page!"
No login, nothing was displayed, just that

Of course I have : 
Clean cache in pydio 
Clean cache in Web browser

To be sure I have
Deleted core licence pluging
Deleted custom.gui_customize 

Read information in your newletter "BETA PROGRAM STARTING TODAY"
checked .htaccess
checked if update script was applied

From a clean install 6.5.1 works
Not tested in detail. 

My need is to validate an upgrade for our production server

So, like you write I will wait to have your green fire to post in github and the first experience from other people before polute you. :-)

**Comment by cdujeu** [comment]
can you connect to gitter? did you get the invite on your gmail ?

**Comment by Nanomani** [comment]
Yep I receive your invitation.

But when I click on button "Join ... chat"

I have this :





2016-09-21 10:55 GMT+02:00 Charles du Jeu <notifications@github.com>:

**Comment by Nanomani** [comment]
I can say it is fixed now

 - Commun works well
 - all news FS repo works well

there is just a little bug  for repo "my file" : 
- the brick for "number of sharing" is never displayed !!!
- the brick for "the last modification" is grey. must be bleue :-)

for all others repo  
 - the brick for "number of sharing" is always grey
 - the brick for "the last modification" is always bleue

**Comment by cdujeu** [comment]
in fact it's not a bug, but a feature ;-)
The number of users displayed is the number of users that are allowed to access this workspace. And by definition, the "My Files" ws is only accessible to "you", that's why we don't display this brick. And then the colors are not linked to a brick type, but just distributed "next color to the next brick"... That's why...
