### ISSUE TITLE
Delete file type "video" is not possible

### ISSUE THREAD

**Issue by Nanomani** [pydio/pydio-core#1134]
Delete file type "video" is not possible

error message : 
"process can't acces to this files because it is open by another process"

![2016-03-31_153136](https://cloud.githubusercontent.com/assets/3939543/14177333/14a911b0-f756-11e5-9cc9-5ca46d5f9a55.png)

same issue with 6.2.2 and 6.4.0

**Comment by cdujeu** [comment]
maybe an iis issue, i cannot reproduce that on *nix

**Comment by Nanomani** [comment]
Yes, After a very quick search I see some code for kill process for *nix.
Perhaps something to adapted for Win OS. Not sure
sorry to post all these observations as a potato sack.
I will try to contribute more when I have time ...

**Comment by cdujeu** [comment]
"I see some code for kill process for *nix." ? no way. we do a simple delete exactly like any other file.

**Comment by Nanomani** [comment]
Ok ok. 
perhaps add a new control for Win OS.
if Win OS => stop preview in right panel before "delete"  ...

**Comment by Nanomani** [comment]
after have tested that 1000x on 2 servers.
this works perfectly today without any change on these servers.
