### ISSUE TITLE
AWS S3 broken since 6.4.? Argument #1 is not an array

### ISSUE THREAD

**Issue by kingfisher77** [pydio/pydio-core#1135]
Since upgrade to Version 6.4 our workspace to AWS S3 ist not working anymore (see below from apache error-log). Could we change something on our side to bring it back to work or should we rollback to the previous version until fixed?

[Thu Mar 31 18:25:38.361783 2016] [:error] [pid 15751] [client 999.999.999.999:45596] [PYDIO] IP 999.999.999.999| user name@tld.domain | Error | error l.47 | from class.ShareMetaManager.php | message=array_merge_recursive(): Argument #1 is not an array, referer: https://pydio.tld.domain/ws-s3-storage

[Thu Mar 31 18:25:38.552616 2016] [:error] [pid 15751] [client 999.999.999.999:45596] PHP Fatal error:  Access to undeclared static property: s3AccessWrapper::$crtZip in PATHTO/htdocs/pydio-core/plugins/access.s3/class.s3AccessWrapper.php on line 152, referer: https://pydio.tld.domain/ws-s3-storage

[Thu Mar 31 18:25:42.139767 2016] [:error] [pid 15751] [client 999.999.999.999:45596] PHP Fatal error:  Cannot redeclare AjaXplorer_autoload() (previously declared in :101) in PATHTO/htdocs/pydio-core/conf/bootstrap_context.php on line 126, referer: https://pydio.tld.domain/ws-s3-storage

**Comment by cdujeu** [comment]
Please post in the forum until the bug is fully qualified, thanks
