### ISSUE TITLE
Link send to the external emailer must be more clean (pydio 6.4.0)

### ISSUE THREAD

**Issue by Nanomani** [pydio/pydio-core#1138]
Link send to the external emailer must be more clean.
(Tested with Outlook)

Works fine with 6.2.2

**If File Public Link**

![e9d28864-f7fe-11e5-8556-df1272c7e3e5](https://cloud.githubusercontent.com/assets/3939543/16444554/d5b08ff4-3dde-11e6-8de1-1e4879b640dd.png)

**If Workspace Link**

![7cc10b5e-f800-11e5-8f2f-ec623af26c7a](https://cloud.githubusercontent.com/assets/3939543/16444568/e518ca38-3dde-11e6-9930-7f6b4cbec7b3.png)

**If Folder Public Link**

![5233b2fa-f801-11e5-8992-e4ee0b13d622](https://cloud.githubusercontent.com/assets/3939543/16444573/eb70316e-3dde-11e6-9b41-9a5e27362cdb.png)

**Comment by cdujeu** [comment]
Hi @Nanomani can you be more specific about what the actual problem is? File instead of Folder?

**Comment by Nanomani** [comment]
yep for file instead of folder for public folder. But this is not a big deal. :-)

The big reason of this post is the HTML code displayed in mail.

`<a href=xxx>link</a>`

Before the mail displayed only link without code

**Comment by cdujeu** [comment]
mm, it's really strange, it was the same text when we were sending before. If you still have a working sample (email sent w. 6.2.2), could you post the "source" of both messages (working / not working) ? 
-c

**Comment by Nanomani** [comment]
latest-pydio 07/07/2016 tested without success.

**code source pydio 6.2.2 works**

![2016-07-08_104635](https://cloud.githubusercontent.com/assets/3939543/16682223/a64a1f56-44f9-11e6-9ce9-6ff8ea58e91c.png)

`<html xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:w="urn:schemas-microsoft-com:office:word" xmlns:m="http://schemas.microsoft.com/office/2004/12/omml" xmlns="http://www.w3.org/TR/REC-html40"><head><meta http-equiv=Content-Type content="text/html; charset=utf-8"><meta name=Generator content="Microsoft Word 15 (filtered medium)"><style></style></head><body lang=FR link=blue vlink=purple><div class=WordSection1><p><span style='font-family:"Calibri",sans-serif'><a href="http://localhost/pydio-core-6.2.2/data/public/a80f50">http://localhost/pydio-core-6.2.2/data/public/a80f50</a></span> <o:p></o:p></p></div></body></html>`

**code source pydio 6.4.2 don't works**

![2016-07-08_104704](https://cloud.githubusercontent.com/assets/3939543/16682227/b43d4264-44f9-11e6-8126-655afb769d0e.png)

`<html xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:w="urn:schemas-microsoft-com:office:word" xmlns:m="http://schemas.microsoft.com/office/2004/12/omml" xmlns="http://www.w3.org/TR/REC-html40"><head><meta http-equiv=Content-Type content="text/html; charset=utf-8"><meta name=Generator content="Microsoft Word 15 (filtered medium)"><style></style></head><body lang=FR link=blue vlink=purple><div class=WordSection1><p><span style='font-family:"Calibri",sans-serif'>Un utilisateur de Pydio 6.4.2 a partagé un fichier avec vous</span> <o:p></o:p></p><p><span style='font-family:"Calibri",sans-serif'>&nbsp;&lt;a href=&quot;<a href="http://localhost/pydio-core-6.4.2/data/public/99883b">http://localhost/pydio-core-6.4.2/data/public/99883b</a>&quot;&gt;<a href="http://localhost/pydio-core-6.4.2/data/public/99883b">http://localhost/pydio-core-6.4.2/data/public/99883b</a>&lt;/a&gt;</span><o:p></o:p></p></div></body></html>`

**Comment by cdujeu** [comment]
did you switch from phpmailer-lite to phpmailer maybe? This part did not change...

**Comment by Nanomani** [comment]
@cdujeu 
Nope. I have makes 2 new clean install for 6.2.2 and 6.4.2 with only the minimal and same settings on both, nothing special on my side.

**Comment by cdujeu** [comment]
and in the 6.2.2 you don't have "Un utilisateur... a partagé avec vous" ?

**Comment by Nanomani** [comment]
no.

Same scenario for 6.2.2 and 6.4.2:
 - new clean install with db
 - php command line enable
 - external emailer enable (in my case Outlook 2016)
 - 1 new file "test.jpg" upload in "my files" repo
 - public link sharing on "test.jpg" + invitation
 
With pydio 6.2.2 I have in source code this : 

`<a href="http://localhost/pydio-core-6.2.2/data/public/a80f50">http://localhost/pydio-core-6.2.2/data/public/a80f50</a>`

With pydio 6.2.2 I have in source code this : 

`<a href="http://localhost/pydio-core-6.4.2/data/public/99883b">http://localhost/pydio-core-6.4.2/data/public/99883b</a>&quot;&gt;<a href="http://localhost/pydio-core-6.4.2/data/public/99883b">http://localhost/pydio-core-6.4.2/data/public/99883b</a>`

**Comment by cdujeu** [comment]
aaaaah, ok sorry this is what I misread from the beginning : "external emailer enable" !!! 
That should make things easier to debug now. 
Will keep you posted.

**Comment by cdujeu** [comment]
ok building a pydio-latest right now (see download.pydio.com/pub/core/ci/), please wait for the build. Hopefully should fix the issue, tell me.

**Comment by Nanomani** [comment]
Sorry, I have always the same pb.
Tested with the pydio-latest (19/07/2016 - 10h09)

**Email received :** 

![2016-07-19_121711](https://cloud.githubusercontent.com/assets/3939543/16946767/8828c544-4dab-11e6-932a-4a551a8c32f0.png)

**code source (_body_ part only) :** 

`<body lang=FR link=blue vlink=purple><div class=WordSection1><p><span style='font-family:"Calibri",sans-serif'>Un utilisateur de Pydio a partagé un fichier avec vous &lt;a href=&quot;<a href="https://pydio.local.com/data/public/dbc091">https://pydio.local.com/data/public/dbc091</a>&quot;&gt;<a href="https://pydio.local.com/data/public/dbc091">https://pydio.local.com/data/public/dbc091</a>&lt;/a&gt;</span><o:p></o:p></p></div></body>`

**Comment by 7omate** [comment]
Which encoding are you using for the Mailer?

**Comment by Nanomani** [comment]
Unicode (UTF-8)

![2016-07-21_155044](https://cloud.githubusercontent.com/assets/3939543/17025149/f52169b6-4f5a-11e6-8bd9-d12fce540f69.png)

**Comment by Nanomani** [comment]
I think the issue is the code send to the emailer : 

**Actually** 

`<body lang=FR link=blue vlink=purple><div class=WordSection1><p><span style='font-family:"Calibri",sans-serif'>Un utilisateur de Pydio a partagé un fichier avec vous &lt;a href=&quot;<a href="https://pydio.local.com/data/public/dbc091">https://pydio.local.com/data/public/dbc091</a>&quot;&gt;<a href="https://pydio.local.com/data/public/dbc091">https://pydio.local.com/data/public/dbc091</a>&lt;/a&gt;</span><o:p></o:p></p></div></body>`

**must be more simple like that :** 

`<body lang=FR link=blue vlink=purple><div class=WordSection1><p><span style='font-family:"Calibri",sans-serif'>Un utilisateur de Pydio a partagé un fichier avec vous <a href="https://pydio.local.com/data/public/dbc091">https://pydio.local.com/data/public/dbc091</a></span><o:p></o:p></p></div></body>`

**Comment by Nanomani** [comment]
Is it possible to keep this issue open ?

**Comment by cdujeu** [comment]
yes. sorry, won't be in the 6.4.2.
FYI the "WordSection1" stuff is by no mean added by Pydio.
Charles

**Comment by Nanomani** [comment]
tested with pydio-latest 6.5.1 22-Sep-2016 16:05

always the same thing :(

![2016-09-22_162158](https://cloud.githubusercontent.com/assets/3939543/18751899/f940360a-80e0-11e6-88d8-d3f963e1da1a.jpg)

**Comment by Nanomani** [comment]
Any idea ? Thx
