### ISSUE TITLE
session_write_close(): Session callback expects true/false return value

### ISSUE THREAD

**Issue by stahlgmbh** [pydio/pydio-core#1139]
on a fresh install on PHP 7.0.5 a parse_error appears on the welcome screen because of the following error:
session_write_close(): Session callback expects true/false return value

**Comment by cdujeu** [comment]
can you disable the E_WARNING error_reporting in php?

**Comment by stahlgmbh** [comment]
I could fix it by modifiying pydio/plugins/sec.session/class.PydioSessionHandler.php

and by adding a return keyword before the parent::close();

public function close(){
      return parent::close();
}

**Comment by stahlgmbh** [comment]
I wanted to submit a pull request, but couldn't find this file in the repository.

**Comment by cdujeu** [comment]
i'll commit that, thx

**Comment by cdujeu** [comment]
commited, will be in next release.
