### ISSUE TITLE
if you enable sharing for workspace only it is not possible to create workspace sharing (pydio 6.4.0)

### ISSUE THREAD

**Issue by Nanomani** [pydio/pydio-core#1143]
if you enable sharing for workspace only it is not possible to create a workspace sharing.

scenario : 
- enable sharing only for workspace in settings
- create a new workspace sharing on root folder in repo "my file"
- save

There is a message "Cannot find share for node name_folder"
The sharing is not create

back to settings and enable for both workspace and minisite.
Workspace sharing works fine
no issue with 6.2.2

**Comment by cdujeu** [comment]
Same scenario if you disable Public Links on Files.

**Comment by Nanomani** [comment]
yes same issue with file.
