### ISSUE TITLE
WebDAV :Error 500 when accessing root dir of an smb workspace.

### ISSUE THREAD

**Issue by Fabzz007** [pydio/pydio-core#1149]
Hi, Charles ask me to open this issue here : [https://pydio.com/forum/f/topic/webdav-access-to-smb-workspace/]

When I try to connect to the root directory of my smb workspace with WebDAV, I have an error : 500. If I go to a sub directory it’s ok. The pb exist with pydio 6.0.8 and with a fresh install of 6.2.0. The problem still exist on 6.4.0. Not tested in 6.2.1 and 6.2.2 form me.

For exemple dir1 is an smb workspace :
Accessing to the workspace https://mypydio.domain.local/ws-dir1 : OK
Accessing to https://mypydio.domain.local/shares : ok (i see all my workspace smb et fs)
Accessing to https://mypydio.domain.local/Share/dir1 : error 500
Accessing to https://mypydio.domain.local/Share/dir1/sub-dir : ok

No problem with accessing to the root folder of FS workspace with webdav.

This is the Workaround TRAN gived to me :
add the following code in Pydio_path/plugins/access.smb/smb.php (insert into between line 65 and 66

```
list ($pu['share'], $pu['path']) = (preg_match ('/^([^\/]+)\/(.*)/', $path, $regs))
          ? array ($regs[1], preg_replace ('/\//', '\\', $regs[2]))
          : array ($path, '');

//add this line
if (empty($pu["path"]) && preg_match('/\/$/', $url)) $pu["path"] = "/";
// -----------
        $pu['type'] = $pu['path'] ? 'path' : ($pu['share'] ? 'share' : ($pu['host'] ? 'host' : '**error**'));
```

**Comment by cdujeu** [comment]
@c12simple do we add that in the code or not?

**Comment by JohnstonJ** [comment]
I also have this problem; the same workaround seemed to help.  This is on Pydio 6.4.1.

**Comment by c12simple** [comment]
Fixed
https://github.com/pydio/pydio-core/commit/0e000ffcd195b854aef5e6d91f6547e566aca5bc
