### ISSUE TITLE
CacheDriver doesn't work with APCu extension on php7

### ISSUE THREAD

**Issue by josh4trunks** [pydio/pydio-core#1157]
The APCu extension for php7 no longer includes the backwards compatible extension naming of "apc". I noticed then when testing a cronjob from the commandline.

I was able to get this in `plugins/cache.doctrine/class.DoctrineCacheDriver.php`
by changing...
`define('APC_EXTENSION_LOADED', extension_loaded('apc'));`
`$this->cacheDriver = new Cache\ApcCache();`
to...
`define('APC_EXTENSION_LOADED', extension_loaded('apcu'));`
`$this->cacheDriver = new Cache\ApcuCache();`

Ideally we have an additional option for apcu as a caching driver, or add some additonal logic in this file to figure out which driver to use.

**Comment by ghecquet** [comment]
Thanks for that !

I've added a change so that apcu or apc is supported based on what extension is available.

It'll be available in next version

**Comment by josh4trunks** [comment]
wow, that was quick. thanks!

**Comment by boriel** [comment]
This fix should also be in the file `./core/tests/test.PHP_APC.php` line 36, to read:

` if (extension_loaded('apc') || extension_loaded('apcu')) {`
