### ISSUE TITLE
Next execution time for a task schedule triggered via Tasks scheduler plugin scheduled for periodic interval is incorrect.

### ISSUE THREAD

**Issue by sagaru** [pydio/pydio-core#1165]
when we schedule a task using _Tasks scheduler_ plugin, scheduled for a periodic interval (for every x minutes), the next execution time is incorrect.

![scheduler](https://cloud.githubusercontent.com/assets/6860643/14453637/53cafa72-0096-11e6-9a5d-4a4ee1eca082.PNG)

Reason seems to be the special characters in the schedule field which are not handled yet.

**Comment by cdujeu** [comment]
Can't reproduce that, working for me.
