### ISSUE TITLE
File share download number limit

### ISSUE THREAD

**Issue by killpowa** [pydio/pydio-core#1167]
Right now i noticed that the limit applies to the number of "clicks" on the download button. This is a problem though because anyone could click it a lot of times randomly. It doesn't represent the correct number of download so.
I would suggest to base the download number on the instances(users) maybe based on IP/cookies/sessions. So if one user downloads it 10000 times it counts just as one. When the user closes the browser or after some time(like 5 min) it counts as another download, even for the same user.
What do you think?

**Comment by cdujeu** [comment]
Hi, 
As indicated in our readme, please first post to the forum before opening issues in gh, thx ! 
-c
