### ISSUE TITLE
Blank screen when logging in with udevil enabled

### ISSUE THREAD

**Issue by robdk63** [pydio/pydio-core#1169]
When using meta.mount with udevil enabled, the inital screen after login will be blank. This is due to udevil outputting a status message which causes a Javascript error.
The fix is to alter the two lines in /usr/share/pydio/plugins/meta.mount/class.FilesystemMounter.php
from
$udevil = "udevil ";
to 
$udevil = "udevil --quiet ";

Robert

**Comment by cdujeu** [comment]
@c12simple can you validate that?

**Comment by c12simple** [comment]
Can you send me a screenshot ? what kind of output  message
and please tell me the environment you are testing 
to tran@pydio.com

**Comment by c12simple** [comment]
@robdk63 . could you please verify
https://github.com/pydio/pydio-core/commit/529d233b6393dd6804e433990ab20ade40ccf743

**Comment by cdujeu** [comment]
ok should be fixed in "namespaces" branch
