### ISSUE TITLE
Admin enable notifications for users

### ISSUE THREAD

**Issue by anatomism** [pydio/pydio-core#1173]
A feature that would be gladly welcome is being able to enable email digest notifications for all users workspaces. 

When you share a folder with a user, you can enable notifications, but if you add them to a workspace through the Admin->People panel, it seems you cannot (enable notifications). I have to instruct them how to do it individually and it's a bit arkward

Thanks

**Comment by cdujeu** [comment]
Hi @anatomism 
We are looking into this feature request. I'm a bit worried about the very high number of alerts / emails it may generate if e.g. you have a workspace accessible to all users (e.g. 200) of the platform, any move / change on this workspace will generate 200 alerts ... Not sure it's really a good idea. Or it should in that case generate an alert but without corresponding email, which will be more complicated to implement. 
What do you think?
Charles

**Comment by anatomism** [comment]
Hi Charles

I only ever set my users on notify if the file has been modified or a new
file uploaded, that's just what's useful for me

All I really want is email notification of new files and deleted files. Not
moved files as that is of no real benefit to me. I'd love the option of not
notifying about deleted files as if I were uploading a new set of drawings
I would delete the old and upload the new. That generates a lot of email
traffic. If there were a pop up at the end of the uploads saying 'would you
like to notify people about this upload yes/no' I think that would work well

Thanks

On 1 Jul 2016, at 08:46, Charles du Jeu <notifications@github.com> wrote:

Hi @anatomism <https://github.com/anatomism>
We are looking into this feature request. I'm a bit worried about the very
high number of alerts / emails it may generate if e.g. you have a workspace
accessible to all users (e.g. 200) of the platform, any move / change on
this workspace will generate 200 alerts ... Not sure it's really a good
idea. Or it should in that case generate an alert but without corresponding
email, which will be more complicated to implement.
What do you think?
Charles

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/pydio/pydio-core/issues/1173#issuecomment-229879790>,
or mute the thread
<https://github.com/notifications/unsubscribe/AInI27ZIWZy9KcJaTF4gfXAtsA2oMOGhks5qRMXjgaJpZM4IY3UG>
.

**Comment by cdujeu** [comment]
Hi, it's not there yet, but you now have all the tools to automatize that in Pydio 7

## Principle
New in Pydio 7
 - Ability for a user to watch a whole workspace, by right clicking the root folder and selecting Watch.... action. This triggers the "toggle_watch" action.
 - Better command line with the new option "-i" to "impersonate" a user : you can trigger a command with your admin user and impersonate another user.
 - This "impersonate" can even take special values "*" or "**/*" to apply the command to all users of the current admin group or all users of all groups respectively. 

With those features, you could now trigger a command line to register a watch for all users on a given workspace. That script could be run on a regular basis to make sure all new users have the watch, or manually after each user creation. 

## Command Samples

The "toggle_watch" action takes the following parameters : 
- watch_action : [watch_read|watch_change|watch_both|watch_stop] to monitor consultation, modifications, both or stop monitoring
- file : the path to the file or folder to watch. For full workspace, use "/".

Here are some sample below, assuming the admin user is admin/password and an existing user is "user". Let's say the workspace to watch is "my-workspace".

#### Enable watch for modifications for admin
 
    $ php cmd.php -u=admin -p=password -r=my-workspace -a=toggle_watch --watch_action=watch_change --file=/

#### Enable watch for modifications for user "user"

    $ php cmd.php -u=admin -p=password -r=my-workspace -a=toggle_watch -i=user --watch_action=watch_change --file=/

#### Enable watch for modifications for all users that can access this workspace

    $ php cmd.php -u=admin -p=password -r=my-workspace -a=toggle_watch -i=**/* --watch_action=watch_change --file=/

#### Stop all watches for user "user"

    $ php cmd.php -u=admin -p=password -r=my-workspace -a=toggle_watch -i=user --watch_action=watch_stop --file=/

I think this gives a good solution for this request.
