### ISSUE TITLE
Sendmail parameters are not fully compliant

### ISSUE THREAD

**Issue by faelnor** [pydio/pydio-core#1174]
When using a sendmail-compatible clone such as mini_sendmail (for mailing from inside a chroot), sending an email silently fails and leads to an instanciation error because the -f additional option is passed with a space before the address that follows. Indeed, the flags of sendmail should be passed without blank character (see manpage).

The fix is the simplest thing ever, just remove the space before %s at line 585 of class.phpmailer-lite.php

**Comment by ad-m** [comment]
Do you can prepare pull request?

**Comment by cdujeu** [comment]
hi, just going back on this. I can't find anything in the man page about "no space" after -f. Can you just point me to the right resource?
