### ISSUE TITLE
User email address incorrect leads to Notification Digest failure

### ISSUE THREAD

**Issue by anatomism** [pydio/pydio-core#1176]
I have Notification Digests enabled on a Sendmail via SSMTP which normally works well. 

A user entered their email address wrong (valid syntax, just missing letter from name) who was added to a workgroup notification - this then silently failed and no further emails were sent (even on other workgroups).

I accessed the table within the database and there were nearly 3,000 entries stacked up - I cleared these, corrected the email address and all is now working again. This user action can break an entire install

**Comment by cdujeu** [comment]
ok we'll have a look at that, thanks!

**Comment by anatomism** [comment]
To follow up - I did again with another workgroup and it did the same - no obvious errors in email addresses, however there were 3 pages of 500 entries (phpmyadmin) - could it be that php has reached so kind of processing limit?

Suggest ignoring deletions as one per line and just concentrating on new files upload to reduce the number of entries?

**Comment by cdujeu** [comment]
we are still working on that. we will greatly improve the performances of the consume_mail_queue action.
