### ISSUE TITLE
Can't choose the destination page when moving an element

### ISSUE THREAD

**Issue by Rohirrim03** [pydio/pydio-core#1179]
When a repository is paginated (for example if there’s 3 pages) and if we want to move an element by selecting it and clicking “Move”, the destination can only be a folder that is located in the first page. 
It’s written “Destination (1/3)” but there is no way to reach the 2 other pages.
![screen bug pydio](https://cloud.githubusercontent.com/assets/19585757/15567151/f9db67de-2324-11e6-848f-e1a916deada6.png)

**Comment by notJerome** [comment]
Hi, I have the same problem with pagination.
Any idea for fixing this bug ?
Thanks for your responses.

**Comment by notJerome** [comment]
Thanks you.

**Comment by Rohirrim03** [comment]
Thanks !
