### ISSUE TITLE
Shared single zip files can not be downloaded

### ISSUE THREAD

**Issue by kluckow** [pydio/pydio-core#1180]
Related topic:
[https://pydio.com/forum/f/topic/download-button-not-working/](https://pydio.com/forum/f/topic/download-button-not-working/)

**Comment by Inglebard** [comment]
Hi,
I also encoutered this error. Seems to be related to "open_basedir".

If you comment "open_basedir" does it work ?

**Comment by cdujeu** [comment]
hi again
I still cannot reproduce that. 
Do you have php open_basedir active?
