### ISSUE TITLE
Impossible to use scrollbars in Settings

### ISSUE THREAD

**Issue by JohnstonJ** [pydio/pydio-core#1181]
I did a clean install of Pydio Enterprise 6.4.1 onto Ubuntu 14.04 from the Pydio-provided repositories.  I am experiencing the following difficulty on both Chrome 51.0.2704.79 and Internet Explorer 11.

My screen has only limited height and there are many Settings categories.  Therefore, a vertical scrollbar is shown.  However, if I attempt to point to the scrollbar, the entire Settings list collapses.  So it's impossible to use this list using solely the mouse pointer and mouse buttons.  As a workaround I was luckily able to scroll the list using my laptop's Lenovo TouchPad scroll gesture (which emulates a mouse wheel).  See attached screenshot for illustration.

As improvements, I propose:

1.  Fix the bug where the category list disappears when you point to the scrollbar, this is a serious usability problem of Settings.

2.  Even after you fix this bug in the easiest way, it's not ergonomic if there's no delay.  For example, if the user moves mouse past the scrollbar by even a couple of pixels, the categories might disappear immediately.  There should be a delay between when the mouse moves outside of the category list and when the category list collapses (for example, a half second).  That way, if the user overshoots the scrollbar when pointing, they have a moment of time to fix the error.  (For example, Visual Studio acts this way if one of the side panels is set to auto-hide and the mouse temporarily exits the panel).

![image](https://cloud.githubusercontent.com/assets/13113915/15808792/792bc634-2b70-11e6-81b2-95c696b99a77.png)

**Comment by cdujeu** [comment]
hi
yep i agree. we'll look into this.

**Comment by cdujeu** [comment]
fixed
