### ISSUE TITLE
Default workspaces are indicated as not syncable

### ISSUE THREAD

**Issue by JohnstonJ** [pydio/pydio-core#1182]
According to https://github.com/pydio/pydio-doc-admin-guide/blob/v6/getting-started/checking-sync.md#workspace-configuration, (1) it's necessary to enable "Syncable Workspace" setting in the `meta.syncable` plugin, (2) this should be enabled by default for the default workspaces.

I installed Pydio Enterprise 6.4.1 onto Ubuntu 14.04 via the Pydio-provided apt-get repositories.  I found that the setting is not enabled by default:

```
$ cat /etc/pydio/bootstrap_repositories.php
$REPOSITORIES[1] = array(
<snip>
            "meta.syncable"     => array(),
```

So it looks like the plugin is being loaded by default, but the "Syncable Workspace" option is not being explicitly set.  This then shows up in the user interface as follows:

![image](https://cloud.githubusercontent.com/assets/13113915/15811649/8734911e-2b9a-11e6-8acc-15098eeba7fc.png)

Examining the plug-in source code, this was the only reference to `REPO_SYNCABLE` I could find:

https://github.com/pydio/pydio-core/blob/0266e1f93c4a019c8cf71626eb095a125fcaec5b/core/src/plugins/meta.syncable/class.ChangesTracker.php#L624
```
        if(isSet($metaSourcesOptions["meta.syncable"]) && (!isSet($metaSourcesOptions["meta.syncable"]["REPO_SYNCABLE"]) || $metaSourcesOptions["meta.syncable"]["REPO_SYNCABLE"] === true )){
            $metaSourcesOptions["meta.syncable"]["REQUIRES_INDEXATION"] = true;
        }
```

So it looks like the actual behavior is that if the option isn't set (as in the default bootstrap file installed with Pydio), then assume the same behavior as if it was set to true.

I should also note that the Pydio sync client for Windows had no trouble doing an initial sync with a few test files.

This was all initially confusing because (1) the Getting Started \ Checking Sync manual section says to verify this setting, and (2) the GUI said it wasn't enabled, meaning I need to fix it, (3) yet the sync client would sync.

Therefore maybe there are some things to fix:

- If I'm reading the code right and it really was syncable, then the user interface should reflect that with a checked box instead of an unchecked box.
- Maybe the default `bootstrap_repositories.php` should explicitly set the option.

**Comment by cdujeu** [comment]
i totally agree
we should set `"meta.syncable"     => array("REPO_SYNCABLE" => true),`in the bootstrap_repositories.php file

**Comment by cdujeu** [comment]
fixed
