### ISSUE TITLE
Telechargement superieur a 1.6GB ne fonctionne pas

### ISSUE THREAD

**Issue by mohamedSolimani** [pydio/pydio-core#1183]
Bonjour,

Lors du téléchargement d'un fichier de 4.4GB, le téléchargement s’arrête a 1.3 ou 1.6GB.

Pouvez-vous m'aider?
Voici ma configuration PHP 5.6:
max_execution_time = 3230
max_input_time = 3230
memory_limit = 50G
upload_max_filesize = 16G
max_file_uploads = 40
pdo_mysql.cache_size = 2000

**Comment by cdujeu** [comment]
bonjour, 
merci d'utiliser le forum et pas github pour ce genre de questions.
-c
