### ISSUE TITLE
Sound files in a directory as a playlist

### ISSUE THREAD

**Issue by Kwadz** [pydio/pydio-core#1186]
Hi,
Is there a plan to add the possibility to play continuously all sound files of a directory in the web interface?
Regards

**Comment by Kwadz** [comment]
What is the player you use to play files in the web interface? Where are located the related files?

**Comment by cdujeu** [comment]
hi, 
in fact if you let the folder open an play the file directly from the list (not from the right-panel), at the end it will automatically start playing the next one in the list.
