### ISSUE TITLE
S3-based workspaces cannot be synchronized

### ISSUE THREAD

**Issue by raphael0202** [pydio/pydio-core#1190]
I've noticed that the synchronization client (Linux) works well for a local storage workspace, but not for one base on Amazon S3.
I've investigated a bit, and found out that on my Pydio instance, the `servername.tld/api/my-files/stat_hash/key` works well (local storage based), but `servername.tld/api/s3_workspace/stat_hash/key` returns an empty response, hence the sync problem.
Is synchronization for S3-based workspaces supposed to work or is this feature still missing?

**Comment by cdujeu** [comment]
hi, please use the forum for asking question. GH issues are only for "qualified" bugs, thx.
That said, make sure to enable metastore / meta.filehasher on the s3 workspace.

**Comment by raphael0202** [comment]
Thanks, meta.filehasher needed to be activated. However, it would be preferable if the response of the `servername.tld/api/s3_workspace/stat_hash/key` endpoint is more informative that just an empty response.
