### ISSUE TITLE
[index.elasticsearch] missing composer.json

### ISSUE THREAD

**Issue by isma91** [pydio/pydio-core#1194]
Need to create the file `composer.json` with : 
`{
   "require": {
       "ruflin/elastica": "dev-master"
   }
}`
to avoid the require error when enable the plugin `index.elasticsearch`

**Comment by ghecquet** [comment]
Added with version 3.2 of the elasticsearch plugin

**Comment by afm-mike** [comment]
This helped me.  I can now get into a ws w/o issue after activating the elaasticsearch plugin.  However, if I type a search term, I get an error, like:  no such index [index: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx].  Do I need to build the index from the command line first, unlike the Lucene plugin?  Thanks

**Comment by afm-mike** [comment]
Yes apparently I do, and it works great so far.
