### ISSUE TITLE
Small files (< 50 kB) cannot be downloaded with the web interface

### ISSUE THREAD

**Issue by raphael0202** [pydio/pydio-core#1197]
Pydio version: 6.4.1

When I try to download small files (approximately < 50 kB), the response from the server is an empty file. After the POST request requesting the file, I checked that the headers of the response, and there was indeed a `Content-Length: 0`.
Downloading files > 50 kB works well.
Surprisingly, when downloading a zip of a folder, files < 50 kB are included and non-empty.

**Comment by cdujeu** [comment]
Hello, please use (and search) the forum before posting here. 
You must have a php output_buffering set, disable it.
