### ISSUE TITLE
Drag and drop directories Firefox

### ISSUE THREAD

**Issue by GoZOo** [pydio/pydio-core#1203]
Drag and drop to upload directories does not work on Firefox on OSX and Windows. Only simple files work.

On Chrome, directories can be uploaded with drag and drop.

**Comment by cdujeu** [comment]
it's a limitation of FF unfortunately. Closing for now.

**Comment by GoZOo** [comment]
Can you at least display a warning to ff users so they know they can't drag'n drop files ?
