### ISSUE TITLE
Access directory with ACL

### ISSUE THREAD

**Issue by Ant95** [pydio/pydio-core#1205]
Hi,

I may have found an issue trying to get Pydio work with POSIX ACLs.

Pydio is running on Apache 2.4.10 on Debian Jessie.
apache2 module "mpm_itk" is installed and enabled.
The virtualhost is configured with: `AssignUserID pydio pydio`

Let's say I have a directory at /data/test with:

`ls -dl /data/test`:

> drwxrwx---+ 3 root root 4096 Aug 26 16:32 test

`getfacl /data/test`:

> \# file: test
\# owner: root
\# group: root
user::rwx
user:pydio:rwx
group::---
mask::rwx
other::---

/data/test is the root path of my repository named "Test".
This repository is configured with "Use POSIX" set to "yes".

Now when I try to access a this repository I get this error:

> error l.877	class.fsAccessDriver.php	message=You are not allowed to access folder pydio://001c12...

Code which throws the error:
> if(!is_readable($path) && !is_writeable($path)){
	throw new Exception("You are not allowed to access folder " . $path);
}

I tried to run `is_readable` and `is_writeable` manually on /data/test as pydio user:
`su -c "php -r 'var_dump(is_readable(\"/data/test\"));'" pydio`:
> bool(true)

`su -c "php -r 'var_dump(is_writeable(\"/data/test\"));'" pydio`:
> bool(true)

The issue may came from "stream wrappers" used by Pydio, but I am not enough familiar with them and Pydio to look further.

**Comment by cdujeu** [comment]
Hi Antoine
Thanks for your detailed report. We'll look into this.
-c

**Comment by 7omate** [comment]
Might be related https://pydio.com/forum/f/topic/hack-ajaxplorer-php-5-2-6-linux-acls/

**Comment by cdujeu** [comment]
Should be fixed now
