### ISSUE TITLE
Upload file with accent don't works since pydio 6.4.2

### ISSUE THREAD

**Issue by Nanomani** [pydio/pydio-core#1206]
Upload file with accent don't works from pydio 6.4.1.
Same thing with menu upload or drag and drop.

message in log : 

> 	ERROR	admin	error l.1334	class.fsAccessDriver.php	message=move_uploaded_file(): The second argument to copy() function cannot be a `directory`

This bug gone if downgrade to pydio 6.4.0

tested only with : Windows OS (Fr)

**Comment by cdujeu** [comment]
Interesting point for you: i'm just working on reworking the whole encoding process : now the default encoding everywhere in the app will always be UTF-8, and we will encode/decode if necessary only to access the underlying storage, using a dedicated wrapper. 
If you want to have a look, check the encoding-rework branch, which is itself a branch of "namespaces", which will become "develop" very soon.
To develop on that branch directly from github, you'll have to install Composer and NPM, and run composer install in src/core/src/, and in each plugin that has a "composer.json" file. Then run npm install then grunt in each plugin that has a package.json, as before.

**Comment by Nanomani** [comment]
very interesting indeed. I have closed this issue because I do not have time to investigate and with the all next massive change I think you have others priority. it is wiser to wait. Thx

**Comment by Nanomani** [comment]
If I comment this PR, upload  works fine with accent in file name : 
(tested with pydio 6.4.2)

https://github.com/pydio/pydio-core/commit/32a1d7235d5057fab2958e518537ce80c1c10441#diff-8df7097b1c74911dd29a78497a51e4b2

**Comment by 7omate** [comment]
To test before closing this issue:

- Windows Server (IIS, Apache, MySQL UTF-8 NFC, define('AJXP_LOCALE', 'en_US.UTF-8');
    1. Upload from windows machine
    2. Upload from Mac
    3. Upload from PydioSync (Mac and Windows)
    4. (Various FS drivers AWS, FS)

- Linux Server (6.4.2 upload of accentuated files currently ok)
    1. Upload from windows machine
    2. Upload from Mac
    3. Upload from PydioSync (Mac and Windows)

**Comment by cdujeu** [comment]
Closing for now, please open a new one when testing new beta.
