### ISSUE TITLE
Monitor a repository

### ISSUE THREAD

**Issue by netcohh** [pydio/pydio-core#1210]
What I would like to have is an email-notification if a user changes/uploads anything into the repository I’m monitoring.
It would be nice and could save a lot of time, because I or my customers have to login to pydio and look for changes only when there actually are some.

Would this be possible in the future?

**Comment by cdujeu** [comment]
it's already possible, please go to the forum, you must have a proper configuration for the emails.

**Comment by netcohh** [comment]
Silly question, but are you sure?
Here: https://pydio.com/forum/f/topic/monitor-a-repository/  you wrote it's not possible. Well, it was last march, maybe it's implemented by now?
