### ISSUE TITLE
thumbmail and right panel preview not updated after editing with Zoho

### ISSUE THREAD

**Issue by Nanomani** [pydio/pydio-core#1213]
thumbmail and right panel preview not updated after editing with Zoho.

scenario : 
edit file.doc with zoho
change 1st page Title 
thumbmail and right panel preview are not updated

tested with 6.4.2 and 6.5.1

**Comment by cdujeu** [comment]
@Nanomani can you test this fix ?

**Comment by Nanomani** [comment]
Pydio seems : 
- detect a change on doc.
- try to applied an update

But the file in data/ cache / imagick_thumb is not updated
Perhaps this file must be deleted first before update with unoconv...

**Comment by Nanomani** [comment]
tested with 6.5.3. Always the same.
must be staying open I think 

PS : zoho is correctly tuned and works fine :-)

**Comment by Nanomani** [comment]
old issue.
collaborate is better.
