### ISSUE TITLE
Automatic Camera Upload

### ISSUE THREAD

**Issue by emresaracoglu** [pydio/pydio-core#1220]
Hello Charles ,

Do you think the automatically photo upload feature for mobile drive?

[Question 1 - June 1, 2015](https://pydio.com/forum/f/topic/automatic-backup-of-photos/)
[Question 2 - July 2, 2013](https://pydio.com/forum/f/topic/photos-auto-upload-for-mobile-client/)

**Comment by 7omate** [comment]
![screenshot_2016-09-30-11-55-17](https://cloud.githubusercontent.com/assets/5781835/18988081/43c075bc-8705-11e6-9f88-09a7076bcb5e.png)
![screenshot_2016-09-30-11-55-24](https://cloud.githubusercontent.com/assets/5781835/18988082/43c71d22-8705-11e6-8bc2-5b9fe5b4fa6d.png)

You can configure a **Backup** that should do what you want.

Keep us posted.

**Comment by emresaracoglu** [comment]
Yes this is backup system very nice and Android. This is Pydio Pro version?
I're talking about automatically sync photos and videos to Pydio and I can't see for iOS

**Comment by 7omate** [comment]
Yes that's Pydio Pro Android.
We're still working on the iOS new version.

**Comment by leobouilloux** [comment]
Hello @emresaracoglu ,
I'm the current iOS developper at Pydio.

I'am still working on the iOS application but the backup feature will not be available for the release.
I'll add this feature in the next update.

If you provide me your email address, I can add you to the beta testing.

**Comment by emresaracoglu** [comment]
Hello @leobouilloux 

I'm glad you work, we use more than a year Pydio but I've changed to application cloud with other cloud app.

I was really looking forward for your work, I wish you good work
Thank you for your time

**Comment by danielskowronski** [comment]
@leobouilloux any plans to actually implement that feature on iPhone app?
