### ISSUE TITLE
PostgreSQL Doesn't have BLOB data type

### ISSUE THREAD

**Issue by dweimer** [pydio/pydio-core#1224]
in Commit [d2a60295e7322b4de871f18237bceee9483d520f](https://github.com/pydio/pydio-core/commit/d2a60295e7322b4de871f18237bceee9483d520f) You changed a text to BLOB, however PostgreSQL doesn't have a blob data type. It has a [BYTEA](https://wiki.postgresql.org/wiki/BinaryFilesInDB) data type that maybe the closest equivalent.

**Comment by cdujeu** [comment]
hey @dweimer join the gitter chatroom, we were just discussing that earlier :-)
Thx for reporting though.

**Comment by cdujeu** [comment]
See https://github.com/pydio/pydio-core/pull/1225

**Comment by dweimer** [comment]
Unfortunately I can't join the chat room today, in an online training for work, was working on updating my test system during breaks, look like you already have the fix in the works, going ahead and marking the issue closed.
