### ISSUE TITLE
Do not log out automatically after upgrade via UI

### ISSUE THREAD

**Issue by dnauck** [pydio/pydio-core#1227]
Noticed it during Pydio 7 Beta tests.

When upgrading via UI, there is a popup with the upgrade process and useful information if the upgrade was successful or not and which upgrade step failed and why.

But you have only 2 seconds to see it because you're logged out automatically.

Please change it to have some kind of "finish upgrade" button to verify that the upgrade was successful, etc. before logging out.

**Comment by cdujeu** [comment]
Should be fixed by https://github.com/pydio/pydio-core/blob/develop/dist/php/6.5.4-extractArchive-post.php, to be tested when we build package
