### ISSUE TITLE
CSS issue on extrack , move or copy files with 6.5.x

### ISSUE THREAD

**Issue by Nanomani** [pydio/pydio-core#1239]
with 6.4.2

![image](https://cloud.githubusercontent.com/assets/3939543/19214633/c387bef2-8d88-11e6-8ced-93cd43c11905.png)

with 6.5.3

![image](https://cloud.githubusercontent.com/assets/3939543/19214640/e1e90478-8d88-11e6-9d95-16981f4532bb.png)

**Comment by cdujeu** [comment]
i don't have that, browser?

**Comment by Nanomani** [comment]
All 
All Cache cleaned
I retest

**Comment by Nanomani** [comment]
Sorry my fault.
Something must be recheck with branding tools in my side.
By default all is fine.

**Comment by cdujeu** [comment]
ok - we do have to rework the branding tool in-depth. This will be after 7.0
