### ISSUE TITLE
Very Special case with Lucence when the first letter in a word in file name have an accent

### ISSUE THREAD

**Issue by Nanomani** [pydio/pydio-core#1243]
Very Special case with Lucence when the first letter in a word in file name have an accent. 
this file can be found with "Lucene search tools" only if the keyword has his first letter without accent.

Not Linked with https://github.com/pydio/pydio-core/pull/1242

Same result with 6.4.2 and 6.5.4

My setting in plugin Lucence
- Text/Num (case Insensitive)
- Auto-Joker Enable

Scenario : 

there is one file named "être 1000 étés passé.docx" under  "my files" indexed
- search with keyword "être" => the file is not found !!!!!
- search with keyword "etre" => the file is found
- search with keyword "Etre" => the file is found
- search with keyword "1000" => the file is found
- search with keyword "étés" => the file is not found !!!!!
- search with keyword "etés" => the file is found
- search with keyword "etes" => the file is not found !!!!!
- search with keyword "Etés" => the file is found
- search with keyword "passé" => the file is found

Only the first letter in the keyword should be unaccented
I hope this is clear enough

**Comment by Nanomani** [comment]
this workaround fix this issue :

add this line after line 176 in LuceneIndexer.php

before : 

line 176 : `$textQuery = $httpVars["query"];`

after : 

line 176 : `$textQuery = $httpVars["query"];`
line 177 : `$textQuery = iconv('UTF-8', 'ASCII//TRANSLIT//IGNORE', $textQuery);`

**Comment by cdujeu** [comment]
Just to be sure, did you actually try the UTF8TextNum analyzer? 
I don't have that issue on linux / mac, so maybe it's win specific (or non-utf8 specific).

**Comment by Nanomani** [comment]
Yep. 
the result are much more bad.
All word with accent can't be search not only with the first letter.

for example
search with keyword "passé" => the file is found with Text/Num (case Insensitive)
search with keyword "passé" => the file is not found with UTF8 Text/Num (case Insensitive)

**Comment by Nanomani** [comment]
fixed with https://github.com/pydio/pydio-core/commit/e6e72b95316ae01a6673c1b322dddc71fe19e5b5

Works very well
Thx

**Comment by cdujeu** [comment]
? mmm, i'm lost: the Normalization fixes your issue ?

**Comment by Nanomani** [comment]
Yep. 
I have thinked this this PR was related to this issue
I test and this fix my issue :-) sorry ...

**Comment by Nanomani** [comment]
less tolerant but more just

tested wit file named "êtré 1000 étés passé.docx"

search with keyword "êtré" => the file is found
search with keyword "etré" => the file is not found !!!!!
search with keyword "étre" => the file is not found !!!!!
search with keyword "Etre" => the file is not found !!!!!
search with keyword "Etré" => the file is not found !!!!!
search with keyword "1000" => the file is found
search with keyword "étés" => the file is found
search with keyword "etés" => the file is not found !!!!!
search with keyword "etes" => the file is not found !!!!!
search with keyword "Etés" => the file is not found !!!!!
search with keyword "passé" => the file is found

**Comment by Nanomani** [comment]
in perfect world is to add an option to sensitive accent or not.
But this is another issue ...
however this fix goes in a good way in my mind

**Comment by Nanomani** [comment]
add this seems working for me

line 176 : $textQuery = $httpVars["query"];
line 177 : $textQuery = iconv('UTF-8', 'ASCII//TRANSLIT//IGNORE', $textQuery);

**Comment by cdujeu** [comment]
Safety first: i've put a parameter :-)
