### ISSUE TITLE
Support starttls for LDAP connection

### ISSUE THREAD

**Issue by dani** [pydio/pydio-core#1248]
the LDAP auth only supports plain LDAP or LDAP over SSL (ldaps). But there's no way to specify start_tls.

I have an openldap server which is not binding on port 636 (ldaps isn't available) but require starttls to bind.

Juste adding

```
        if ($ldapconn) {
            $this->logDebug(__FUNCTION__, 'ldap_connect(' . $this->ldapUrl . ',' . $this->ldapPort . ') OK');
            ldap_set_option($ldapconn, LDAP_OPT_PROTOCOL_VERSION, 3);
            // Start tls
            ldap_start_tls($ldapconn);
```

in plugins/auth.ldap/class.ldapAuthDriver.php line 215 does the trick. But it should be available as an option (probably a third option in the dropdown which actually propose either standard ldap or SSL)

**Comment by cdujeu** [comment]
@c12simple can you check if we can simply add this as an option?

**Comment by cdujeu** [comment]
@dani @c12simple can you quickly verify that my commit does the trick? Close issue if ok.

**Comment by c12simple** [comment]
I don't have CA signed certificate to test.
But it works if I set TLS_REQCERT never in ldap.conf

**Comment by cdujeu** [comment]
ok so the code is good anyway?

**Comment by c12simple** [comment]
Yes, it's good.
