### ISSUE TITLE
Pydio 7 - Orbit Theme - icons missing

### ISSUE THREAD

**Issue by dnauck** [pydio/pydio-core#1255]
Hello,

the following icons are missing from the distribution:

```
GET  https://pydio.example.com/plugins/gui.ajax/res/themes/orbit/images/Tplus.png 404
GET https://pydio.example.com/plugins/gui.ajax/res/themes/orbit/images/Tminus.png 404
```

Referenced in:

core/src/plugins/gui.ajax/res/themes/orbit/css/components/accordion.less
core/src/plugins/gui.ajax/res/js/vendor/webfx/xtree.js 
core/src/plugins/gui.ajax/res/themes/orbit/css/pydio.css

**Comment by cdujeu** [comment]
thx
