### ISSUE TITLE
public upload privacy

### ISSUE THREAD

**Issue by unixland** [pydio/pydio-core#1256]
Hi,

I'm testing pydio 7 and the "public upload-feature". Therefore I created an public Link with just the permission to upload files (no download, no preview).

If two users on different devices upload some files, they can see the uploaded files from the other user too. They can't do anything with these files but they can see the Filename an the preview-icon (e.g. the thumbnails from uploaded pictures).

In this way an unfriendly user could see all uploaded files just by open the link and wait for uploads (and never refresh this site).

I expected every user could only see his own uploaded files.

**Comment by cdujeu** [comment]
Hi!
Thanks for your report. 
I understand the case. Previously we did not use notifications for "minisites", but now they are wired, and indeed if two users connect to the same minisite, they are the same pydio user for the system, thus receiving notifications one from another. 
We'll fix that!

**Comment by ghecquet** [comment]
Updated the pydio booster to reflect the changes
