### ISSUE TITLE
Pydio 7 public links issue

### ISSUE THREAD

**Issue by fjvt** [pydio/pydio-core#1258]
Recently tested pydio 7 (community) and could not get public links to work.

Pydio does not generated the share.php file.

6.4.2 on the same machine / config works fine. 

PHP 56
Freebsd
Nginx

Unfortunately I am new to pydio and I was unable to find our information ...

**Comment by cdujeu** [comment]
Hi indeed you are new to Pydio, otherwise you would know that Github is not a "support" channel, but for qualified bugs only :-). No worries, but please post to the forum instead, see  https://pydio.com/en/community, 
thx!

**Comment by fjvt** [comment]
In the meantime I found out what the issue was (change between pydio 6 vs pydio 7).
A community forum post explained the required changes.
