### ISSUE TITLE
Issue while Upgrading from 7.0 to 7.0.1

### ISSUE THREAD

**Issue by dnauck** [pydio/pydio-core#1260]
Hello,

while upgrading 7.0 to 7.0.1 i get the following error during upgrade via webui:

	Applying upgrade pydio-core-upgrade-7.0.0-7.0.1.zip
	Checking download permissions
	- OK
	Downloading upgrade archive
	- File saved in /home/pydio/workspace.example.com/data/tmp/update/pydio-core-upgrade-7.0.0-7.0.1.zip
	Checking archive integrity
	- Hash is ok (14ddf1d378e19d20c796cefd2a966b6e)
	Checking folders permissions
	- OK
	Extracting Archive
	Blocking all XHR in page: OK
	- Checking Php Version (7.0.8-0ubuntu0.16.04.3) : OK
	- Extracted folder /home/pydio/workspace.example.com/data/tmp/update/pydio-core-upgrade-7.0.0-7.0.1
	Backuping your modified files
	- Nothing to do
	Copying core source files
	- Error : Unable to emit response; headers already sent

Any idea how to debug/check whats went wrong? I updated during 7.0 Beta tests dozen of times without such an issue.

**Comment by cdujeu** [comment]
For that kind of requests, please use the forum, not github, thanks
