### ISSUE TITLE
PHP error on using pydio pro app (Call to a member function getId() on null)

### ISSUE THREAD

**Issue by huzergackl** [pydio/pydio-core#1269]
Exception in php error log after opening the pydio pro app:
Call to a member function getId() on null in /var/www/files/core/src/pydio/Core/Services/UsersService.php on line 161

Below is a screenshot of Kibana containing the following log files:
* pydio log
* apache error log
* apache access log

![screen](https://cloud.githubusercontent.com/assets/4304911/20076147/97d947b4-a537-11e6-9a45-aac6fcf0bc04.png)

Especially notice the request "/index.php?get_action=switch_repository". It got a response with http status 500 (internal server error). I think this line is related to the entry in apache error log.

I did not notice any impact on the app. Nevertheless it could be worth, a closer look.

**Comment by huzergackl** [comment]
The call stack should be:
UserService.php => getRepositoriesForUser
SessionRepositoryMiddleware.php => switchUserToRepository
SessionRepositoryMiddleware.php => handleRequest

The error can be reproduced with pydio 7.0.1 community edition and the latest pro app (updated today).

**Comment by cdujeu** [comment]
hi, is it iOS or Android?

**Comment by huzergackl** [comment]
hi charles, sorry, i forgot to mention that. The error could be reproduced with the android app.
Just let me know if you need more detailed steps to reproduce. Maybe i can help to narrow it down more precisely.

**Comment by cdujeu** [comment]
mmm, still not sure of what you are pointing out: the app is working without issue, but just you see that error appear in your logs, that's it?

**Comment by cdujeu** [comment]
@huzergackl can you explain more about this? What is the actual end-user symptom?

**Comment by 7omate** [comment]
Hi,
`grep "Pydio Pro" /path/to/pydio_access_log | grep 500` 

I do have some entries but they all come from Pydio Pro.10 you seem to also have this with Pydio Pro.12, it would be great if you managed to identify the steps you follow in the app to trigger this error.

I tried that but the error didn't appear.
- Is it a "Keep offline" action?
- Changing workspace?
- configure backup
- Browsing the workpace

**Comment by huzergackl** [comment]
Ok, i first thought it would be a more severe issue but it clearly isn't. It catched my attention because i had no such errors before October 22. After having a closer look i can put your mind at ease: There are no end-user symptoms and the error always appears exactly once at a time only and requires some time in between to occur again. I'am not sure if it has to be fixed at all...

Here are the statistics:
![bildschirmfoto vom 2016-11-10 20-36-08](https://cloud.githubusercontent.com/assets/4304911/20191350/6bce3d32-a785-11e6-8049-eb85beabf12b.png)

I had a few tries on my test-system to find the exact steps to reproduce.

STR:
* User is logged in and the login data is saved.
* Open one specific repository from the sidebar on the left
* During real usage the user would e.g. download a file but this is not required to reproduce the error
* After that put the app in background
* While working in other apps the pydio app gets closed. This can be simulated by manually ending the app by pressing the home button for a longer time and swiping the app out of the launcher.
* Afterwards go to the home screen and start the app again
* The splash screen is visible for a second. After that the last workspace appears.

=> At this point the error is in the log file. But even if i try the exact same steps again immediately, the error wont occur again. If another test is done after an hour the error can be found again.

I also noticed that there is a "switch_repository" on first try. But not if the steps are repeated immediately.

First try:
```
/index.php?get_action=get_xml_registry HTTP/1.1" 200 39256 "-" "Pydio-Native-Pydio Pro Pydio Pro.12"
/index.php?get_action=switch_repository HTTP/1.1" 500 1119 "-" "Pydio-Native-Pydio Pro Pydio Pro.12"
/index.php?get_action=get_xml_registry HTTP/1.1" 200 1358 "-" "Pydio-Native-Pydio Pro Pydio Pro.12"
/index.php?get_action=get_seed HTTP/1.1" 200 1273 "-" "Pydio-Native-Pydio Pro Pydio Pro.12"
/index.php?get_action=get_seed HTTP/1.1" 200 1273 "-" "Pydio-Native-Pydio Pro Pydio Pro.12"
/index.php?get_action=login HTTP/1.1" 200 1470 "-" "Pydio-Native-Pydio Pro Pydio Pro.12"
```

Repeated immediately:
```
/index.php?get_action=get_xml_registry HTTP/1.1" 200 39258 "-" "Pydio-Native-Pydio Pro Pydio Pro.12"
/index.php?get_action=imagick_data_proxy HTTP/1.1" 200 1335 "-" "Pydio-Native-Pydio Pro Pydio Pro.12"
/index.php?get_action=get_seed HTTP/1.1" 200 1273 "-" "Pydio-Native-Pydio Pro Pydio Pro.12"
/index.php?get_action=get_seed HTTP/1.1" 200 1273 "-" "Pydio-Native-Pydio Pro Pydio Pro.12"
/index.php?get_action=login HTTP/1.1" 200 1470 "-" "Pydio-Native-Pydio Pro Pydio Pro.12"
```

As i said i am not sure anymore whether this has to be fixed at all. At least it seems to be a topic with low priority in my opinion.

**Comment by huzergackl** [comment]
The error did not occur on 7.0.2 and it seems like it is not present in 7.0.3 as well.

I think this commit fixed it:
https://github.com/pydio/pydio-core/commit/adbc8398c35a89d7c0f2d3b9dbbeb70212d2e973
