### ISSUE TITLE
Pydio omits the 1st word in downloaded filenames (cyrillic only)

### ISSUE THREAD

**Issue by sysvano** [pydio/pydio-core#1272]
![2016-11-09_1-01-23](https://cloud.githubusercontent.com/assets/23344948/20114965/48db37b2-a618-11e6-922e-0e8eeacb8e1e.jpg)
Pydio omits the 1st word in downloaded filenames (cyrillic only). As for the latin filenames - everything is OK. If the filename consists of only 1 word in cyrillic - downloading it is impossible.
I've attached a screenshot where you can see the original filename and the downloaded one.

Running version is 7.0.1. I've noticed it since I started using Pydio (ver. 6.4.1).

**Comment by sysvano** [comment]
Running version is 7.0.1. I've noticed it since I started using Pydio (ver. 6.4.1).

**Comment by sysvano** [comment]
1 - server OS is Ubuntu 14.04, Client OS - any Windows/Linux distro (tried in many computers) The "AJXP_LOCALE" parameter was never touched (should I change it?). Version 7.0.1 was newly installed, not updated from any previous one.
2 - The stated issue is browser independent (tried IE, Edge, Chrome, Firefox, etc.)

**Comment by cdujeu** [comment]
can you post the output of `echo $LANG` on your server command line?

**Comment by cdujeu** [comment]
also can you attach a couple of files with these problematic cyrillic names?

**Comment by sysvano** [comment]
Perhaps you meant this output:
`> locale
LANG=
LANGUAGE=
LC_CTYPE="POSIX"
LC_NUMERIC="POSIX"
LC_TIME="POSIX"
LC_COLLATE="POSIX"
LC_MONETARY="POSIX"
LC_MESSAGES="POSIX"
LC_PAPER="POSIX"
LC_NAME="POSIX"
LC_ADDRESS="POSIX"
LC_TELEPHONE="POSIX"
LC_MEASUREMENT="POSIX"
LC_IDENTIFICATION="POSIX"
LC_ALL=`
Or this:
`> locale -a
C
C.UTF-8
POSIX
en_AG
en_AG.utf8
en_AU.utf8
en_BW.utf8
en_CA.utf8
en_DK.utf8
en_GB.utf8
en_HK.utf8
en_IE.utf8
en_IN
en_IN.utf8
en_NG
en_NG.utf8
en_NZ.utf8
en_PH.utf8
en_SG.utf8
en_US.utf8
en_ZA.utf8
en_ZM
en_ZM.utf8
en_ZW.utf8
ru_RU.utf8
ru_UA.utf8`
The output of the `echo $LANG` command is empty.
A problematic file is attached.
[ТЗ компьютерная техника.zip](https://github.com/pydio/pydio-core/files/584405/default.zip)
Zipped to preserve Russian filename.

**Comment by sysvano** [comment]
Just noticed that even the folder names looking like this:
![1](https://cloud.githubusercontent.com/assets/23344948/20193782/5f8c28a0-a7b1-11e6-8e8f-17b9b003f3f8.jpg)
after their selection look this way:
![2](https://cloud.githubusercontent.com/assets/23344948/20193830/94d5294e-a7b1-11e6-9b66-34ae92db815a.jpg)
The names don't change on the filesystem. Their names restore in Pydio when I leave such cyrillic named folders.

**Comment by sysvano** [comment]
Also noticed that when I create a new file or folder named with cyrillic characters the first word is also dropped (Pydio even writes the name without the 1st word to the filesystem). However if I put a digit or some latin symbol as the 1st one in the name of created file/folder - the name isn't changed after saving.

**Comment by 7omate** [comment]
Hi, can you try to identify some minimal problems that we could reproduce? We have no knowledge of Cyrillic...
Please give us sample problematic name and actions:
- 1 character folder name (New)
- 1 character folder name (Rename)
- 1 character file upload
- 1 character file rename
- then we'll check with zips
- zip creation from web
- zip browsing
- zip extraction

It's not the same if the problem is character or word-wise.
We'll need your database encoding settings and Pydio encoding settings. 
Did you define an encoding during install or in `conf/boostrap_conf.php` define("AJXP_LOCALE", "en_US.UTF-8"); ?
Is there something regarding encoding in `data/plugins/boot.conf/encoding.php` ?

**Comment by sysvano** [comment]
Hi, 7omate! Thank you for your interest to my problem.
Cyrillic is Russian charset.

1. A parameter `define("AJXP_LOCALE", "en_US.UTF-8");` is commented (by default).
2. As for "data/plugins/boot.conf/encoding.php" - I have no such file in this location (never deleted it).
3. When I try to create a new 1 character named folder "я"  - I get an error "Enter a correct folder name"
4. When I rename a folder named "1" to "я" - the folder is renamed successfully
5. When I try to upload a file named "я.docx" I get an error that I'm not allowed to upload that file there, however any other file that consists of 2 or more Russian words can be uploaded successfully as well as any latin named file and a file the name of which starts with some digit.
6. When I try to rename a file named "1.doc" to "я.doc" I get an error ".doc Forbidden", however when I try to rename it to "абра кадабра.doc" the file is renamed successfully, but just after renaming I Pydio drops the first word. After refreshing the page Pydio shows the correct filename "абра кадабра.doc".
7. When I try to create a zip from web I get an error ".zip contains forbidden characters" (in this case it's no matter how many Russian words I type to name a zip)
8. When I try to browse a russian named zip I get an error:
9. ![123](https://cloud.githubusercontent.com/assets/23344948/20276102/b4550d8a-aabc-11e6-89ad-44d2595c605d.jpg)
10. As for a zip extraction - I have no such feature (I didn't find it, maybe because I'm using a free version of Pydio)

**Comment by 7omate** [comment]
Thanks for your detailed replied we should be able to reproduce and fix this soon.

Can you try uncommenting `define("AJXP_LOCALE", "en_US.UTF-8");` to see if it changes anything?

P.S.: maybe the joomla guys are better than us. But also there is hope that one day we'll handle all those characters correctly.

**Comment by cdujeu** [comment]
@c12simple can you check that? I'm having none of these issues on my system, I guess sysvano system (CentOS) is wrongly configured, (echo $LANG returns empty). Any hints?

**Comment by sysvano** [comment]
I'm having Ubuntu Server 14.04

**Comment by cdujeu** [comment]
oups ok, Ubuntu Server :-)

**Comment by sysvano** [comment]
Uncommenting `define("AJXP_LOCALE", "en_US.UTF-8");` doesn't solve the problem.

**Comment by sysvano** [comment]
If you need, I can register an account and send the login and password to your email for you to test my installation.

**Comment by 7omate** [comment]
I think there is a configuration problem on your side...
Creating / Renaming / Uploading files and folder called `я(Ø|.txt|.doc)` works fine for me.
(Server Linux ext3, en_US.UTF-8, utf-8 mariaDB)

When I unzip the zip file you mentioned earlier I get `íá ™Æ¨ØÏÓ‚•‡≠†Ô ‚•Â≠®™†.doc`. <- **How did you create it** 
When I upload it and try to Explore it in Pydio it doesn't work.

I think this actually belongs to the forum...

**Comment by cdujeu** [comment]
The zip issue is probably a common encoding issue that is happening often in pydio, should be put out of the way.

**Comment by sespivak** [comment]
Hi, @7omate 
This zip file created with russian codepage cp866. In Linux you can correct unpacked filenames with:
`find . -type f -exec sh -c 'np=`echo {}|iconv -f cp1252 -t cp850| iconv -f cp866`; mv "{}" "$np"' \;`
I too can't browse zip files with any filename with russian char. Even if I switch off zip file browsing in access.fs plugin, zip file folders don't disappear from left panel with folder names.

**Comment by 7omate** [comment]
[Российская Федерация.zip](https://github.com/pydio/pydio-core/files/592642/default.zip)

You can upload it to http://demo.pyd.io/ and explore it... It works fine.
(Archive created on a Mac with `zip -r "Российская Федерация.zip" "Российская Федерация"` so yeah long story short looks like config issues)

**Comment by sespivak** [comment]
> You can upload it to http://demo.pyd.io/ and explore it... It works fine.

Yes, it works, but only if Zip Codepage is UTF-8. This file contents looks like "¦а¦-TБTБ¦¬¦¦TБ¦¦¦-TП ¦д¦¦¦+¦¦TА¦-TЖ¦¬TП" in most of Windows archive tools, e.g. Total Commander, 7zip, etc. Only WinRAR unpacks this file correctly. This files can be used in MacOS and Linux without problem, not in Windows.

If in Pydio main settings Zip Codepage is set to CP866, it's not used for zip browsing and that is the problem!
Pydio shows Parsing error: wrong XML... And I can't even copy this error message, because on mouse click it disappears.
You can test your files repacked with CP866 codepage:
[Российская Федерация.zip](https://github.com/pydio/pydio-core/files/592743/default.zip)

**Comment by sysvano** [comment]
Just tried all I did a day ago in demo.pyd.io - all really worka fine with russian chars. I've changed my server default charset to "en_US.UTF-8" (was "ru_RU.UTF-8") and it didn't help. Maybe there's something wrong with default apache or php locale settings? As for the DB - I use MariaDB in UTF-8.

**Comment by sysvano** [comment]
Hey guys!

My problem seems to be solved! You were right about my server misconfiguration. The issue was in Apache2 config. I've changed a variable `export LANG=C` to `export LANG=en_US.UTF-8` in  `/etc/apache2/envvars` and now all works perfectly with russian filenames and folders. I think You can include such check into the installer to avoid such problems in future. The setting `export LANG=C` is Apache's default in Ubuntu Server 14.04. I've checked all my servers that run Apache2 under Ubuntu 14.04 and they were all configured this way.

Thank you all, guys! You helped me a lot!

**Comment by 7omate** [comment]
Great news! Thanks for sharing the fix :)

**Comment by sysvano** [comment]
Successfully tested the fix on another Ubuntu server - all is OK! The only thing is that the Linux system locale isn't so important as I initially thought (it was 'ru_RU.UTF-8' there).

**Comment by sysvano** [comment]
Upd: recently installed ubuntu server 18.04 and faced the same issue. Querried the list of installed locales and got the list:
`C
C.UTF-8
POSIX
ru_RU.utf8`
Then I've decided to set the "export LANG" variable to "ru_RU.utf8" in /etc/apache2/envvars to play a trick, and it worked! No need to gen the "en_US.utf8" locale if you really don't need it! The "export LANG" variable must be any utf8 locale, but not the default "C".
