### ISSUE TITLE
dedicated mbParseUrl() break pydio if WinOS

### ISSUE THREAD

**Issue by Nanomani** [pydio/pydio-core#1280]
see this commit : 
https://github.com/pydio/pydio-core/commit/3f3513cefab1031a41c910eafbe6057998b7442a

this break pydio with this error message in all repo :
"Cannot find repository with this id!"

In log there is this "error l.257" in "MetaStreamWrapper.php"

tested wtih :
Pydio 7.0.1 + pydio-latest 10 nov 2016
Windows Server OS
Apache 2.4.23 + FastCGI
Php 5.6.27

**Comment by cdujeu** [comment]
hi @Nanomani 
that one bfd03729637ceb3a8b3ce3683c22ebcbe21af830 should do the job, can you test?

**Comment by Nanomani** [comment]
Fixed :-) 
thx
