### ISSUE TITLE
Upload - Allowed Extensions not working.

### ISSUE THREAD

**Issue by pskit** [pydio/pydio-core#1283]
I’ve been using Pydio Community in the past and the “allowed extension list” works great. All I had to do was add the extension I wanted to allow in the uploader options and done. On the Pydio Enterprise version it looks like it may be more involved. I’ve added the extensions I want to allow, but nothing takes effect. Tried a apache restart as well. Something I’m missing? Thanks.

**Comment by cdujeu** [comment]
hi, it's not Pydio Enterprise specific, but more probably Pydio 7 :-)

**Comment by pskit** [comment]
Gotcha, for the meantime is there a way to manually override the gui and modify the allowed extensions?

**Comment by cdujeu** [comment]
Hi @pskit, you can grab the code from the fix, but then you have to recompile the uploader.html plugin (`npm install` then `grunt`)

**Comment by pskit** [comment]
Thanks for the update. Are there more specific instructions for going through the steps above? I'm a bit of a Linux noob. Thanks.

**Comment by pskit** [comment]
Just noticed that 7.0.2 (with fixes) may be coming out before December, maybe its best I wait...

**Comment by cdujeu** [comment]
yes wait for 7.0.2, it's coming this week.

**Comment by adietz00** [comment]
I'm in Ubuntu 16.04.1 LTS running Pydio 7.0.2-13 from repo and I'm experiencing this very same problem. Any clues?
