### ISSUE TITLE
Comma in filename cause "contains forbidden character" on compress action

### ISSUE THREAD

**Issue by sespivak** [pydio/pydio-core#1285]
Comma in filename cause "contains forbidden character" on compress action.

Test cases:

file "1,2.txt" selected -> Menu more -> Compress... -> error "contains forbidden character"
folder "myfolder" selected with file "1,2.txt" inside -> Menu more -> Compress... -> compressed without errors
folder "books, papers" selected with file "1,2.txt" inside -> Menu more -> Compress... -> error "contains forbidden character"
folder "books, papers" selected with file "1.txt" inside -> Menu more -> Compress... -> error "contains forbidden character"

Tested 18 Nov 2016 on http://demo.pyd.io/ login as admin/admin, so it's not a "config issue".

**Comment by 7omate** [comment]
Definitely looks like a bug. Awesome report ;)

**Comment by cdujeu** [comment]
hi, 
i think it's an issue with the command line, that has been fixed in the code and will be in 7.0.2.
If you have time you can test with latest build? (see https://download.pydio.com/pub/core/ci/?C=M;O=D)

**Comment by cdujeu** [comment]
Yes for me it's fixed in current develop branch. Please reopen if necessary.
