### ISSUE TITLE
sqlite support is broken

### ISSUE THREAD

**Issue by zoof** [pydio/pydio-core#1291]
As discussed [here](https://pydio.com/forum/f/topic/database-locked-after-upgrade-to-7-0/), pydio reports "database is locked" when installation is using sqlite.

**Comment by regs01** [comment]
Also having issue. Even clean install of 7.0.4 leads immediately to to database is locked error even at first login.

**Comment by cdujeu** [comment]
we should basically drop the support for sqlite (warning added in installer in p8 already)

**Comment by zoof** [comment]
So is switching from Sqlite to MariaDB on an existing installation a straightforward process?

**Comment by cdujeu** [comment]
definitely not sorry.

**Comment by zoof** [comment]
So you recommend installing from scratch?

**Comment by cdujeu** [comment]
yes

**Comment by cdujeu** [comment]
(you can wait for pydio 8.0.2 this week or next week)

**Comment by regs01** [comment]
> we should basically drop the support for sqlite (warning added in installer in p8 already)
had to move to mysql, but why? sqlite is far better solution when it comes to something little single server.
