### ISSUE TITLE
No Welcome Page displaying a list of workspaces

### ISSUE THREAD

**Issue by Gitek1** [pydio/pydio-core#1295]
Hello,

after successfully installing pydio 7.1 I try to get THIS SCREEN displayed after logging in as admin:

https://pyd.io/wp-content/uploads/2014/09/02-Welcome-Page.png

Every time I login I am guided straight to “settings” (with no option to go to any workspace). 
I even can’t login with the user which have any other profile than ADMINISTRATOR (and nothings happen, no errors in log file), if I change permission (profile) to ADMINISTRATOR than I can login but application just redirect to settings ( so no Welcome Page). I realized, that this happens because I have only “Settings” REPOSITORY.

**Comment by cdujeu** [comment]
hi, please do not post here but in the forum intsead, thanks.

**Comment by Gitek1** [comment]
Ok, sorry.

I post here where this issue already been opened: 

https://pydio.com/forum/f/topic/pydio7-workspace-not-showing-after-login-see-screenshot/?bbp_reply_to=106260&_wpnonce=b0b5446695#new-post

Thanks.
