### ISSUE TITLE
Zip delegation broken on 7.0.2

### ISSUE THREAD

**Issue by ytzelf** [pydio/pydio-core#1302]
Using Zip delegation on 7.0.2 doesn't work anymore.

I can see the temp file being created in /tmp/ as well as the bottom-right popup with progress but once @ 100% it closes and download isnt launched at all.

Pydio and Nginx log are silent error-wise.

**Comment by cdujeu** [comment]
please post to the forum before opening an issue. We will open an issue once it's properly qualified.
thx

**Comment by ytzelf** [comment]
Done right here
https://pydio.com/forum/f/topic/zip-delegation-broken-on-7-0-2/

Sorry for bypassing the forums. Let me know if I can be of any help
