### ISSUE TITLE
ajxp_user links back to ajxp_home

### ISSUE THREAD

**Issue by AthletiaTech** [pydio/pydio-core#1307]
Hi, we disabled Home (ajxp_home) workspace because we just don't need it.
But when a user edits his profile in ajxp_user workspace he can't get back because the link in the lower left links back to ajxp_home. It brings up this error:

> Cannot access to workspace with id/alias ajxp_home#0 /plugins/core.conf/AbstractConfDriver.php(614): Pydio\Core\Services\UsersService::getRepositoryWithPermission(Object(Pydio\Conf\Sql\SqlUser), 'ajxp_home')

I think it would be better to link back to the default workspace like my-files.

**Comment by cdujeu** [comment]
indeed, interesting

**Comment by cdujeu** [comment]
fixed in v8 already
