### ISSUE TITLE
Share: Specifying a password which is "too short" results in share without protection

### ISSUE THREAD

**Issue by Flauschbaellchen** [pydio/pydio-core#1314]
Hi,

I already expierenced this bug in 6.4.2 and now after an update to 7.0.3:

When I try to share a file by link using a password, short passwords results in a share without one.
E.g. using "123" as a password does not work.
The user gets a notification "Passwort too short or empty" but that's only a warning.
The share is created without a password.

Additionally:
Within the admin control panel there is an option to force the usage of passwords.
However, I do not want to force every link to be proteced - but if an user shares a proteced link the password should meet a (admin specified) length-requirement.

**Comment by cdujeu** [comment]
hi, this cannot really be easily solved in the current implementation, because as soon as you check the box, it enables the link (public), then you have to manually add a password and if it's too short it's not taken into account indeed.
