### ISSUE TITLE
PICK FOLDER

### ISSUE THREAD

**Issue by 7omate** [pydio/pydio-core#1315]
Behavior between drag and drop to upload and PICK FOLDER upload differ.
- Empty folders are not created correctly
- Nested files are not uploaded `folder/subfolder/file.txt` (At least on Windows, Firefox & Chrome)

See details:
https://pydio.com/forum/f/topic/bug-at-uploader-html-on-pydio-7-0-3/#post-107820

**Comment by cdujeu** [comment]
Unfortunately, this is a limitation due to the spec of the "input type=file" HTML tag: it will only populate with non-empty directories. We should still be able to create the folders "in-between".  
See https://bugs.chromium.org/p/chromium/issues/detail?id=360412 for example

**Comment by cdujeu** [comment]
in fact we can't detect "in-between" folders if they don't contain any file, as the item.webKitRelativePath does not detect them neither. Wont fix as of now, use drag'n'drop instead.
