### ISSUE TITLE
Session Credential Empty

### ISSUE THREAD

**Issue by carlchan** [pydio/pydio-core#1316]
commit 210d2c37268ebf84caa9234ecd022159499f1110 in Core/Services/AuthService.php
line 93:
`if (ConfService::getContextConf($tempContext, “SESSION_SET_CREDENTIALS”, “auth”) && !$bypass_pwd) {`

causes messages
> Session credential are empty! Did you forget to check the Set Session Credential in the Authentication configuration panel?

Need to revert back to
`if (ConfService::getContextConf($tempContext, “SESSION_SET_CREDENTIALS”, “auth”)) {`

**Comment by cdujeu** [comment]
Hi @carlchan 
Sorry to come back only now. Can you give more info about exactly WHEN this is happening? Normal connexion of normal user? Or when running an action in background? Or other api connexion?
-c

**Comment by cdujeu** [comment]
@carlchan I need more info on that one
I guess you are using the FSMount feature
Is it configured to actually use the Session Credentials or not? I think the issue comes from elsewhere.

**Comment by carlchan** [comment]
Sorry I didn't see you updated this until now.

I reverted my "patch" in AuthServices.php and added the change in FileSystemMounter.php
Things seem to be working, I'm not seeing the credential missing message any more.

The original bug seemed to have been triggered when trying to delete files from a fsmount workspace; uploading files didn't seem to trigger it.  So yes it was using session credentials to mount the space, but for some reason couldn't find them when deleting files.

My original post in the forums had a better description of what I did when I first encountered it:
https://pydio.com/forum/f/topic/7-0-3-bug-session-credential-empty-includes-fix/

Thanks for making this fix! I'll keep testing and see if I encounter this issue again with the new changes.

**Comment by carlchan** [comment]
OK, So I've put both changes from 5908f02 and d0a823c in and I still get the error messages from pydio-booster.

The logs look like this:
> ==> /var/log/php7.0-fpm.log <==
> [20-Jan-2017 15:27:46] WARNING: [pool pydio] child 23734 said into stderr: "NOTICE: PHP message: [PYDIO] IP 127.0.0.1 | user USERNAME | Error | Meta plugin | from Pydio\Core\PluginFramework\PluginsService | Cannot instanciate Meta plugin, reason : Session credential are empty! Did you forget to check the Set Session Credential in the Authentication configuration panel?"
> [20-Jan-2017 15:27:46] WARNING: [pool pydio] child 23734 said into stderr: "NOTICE: PHP message: [PYDIO] IP 127.0.0.1 | user USERNAME | Error | error l.311 | from PluginsService.php | message=Error while loading workspace smbhome : Session credential are empty! Did you forget to check the Set Session Credential in the Authentication configuration panel?"
> 
> ==> /var/log/apache2/error.log <==
> [Fri Jan 20 15:27:46.885656 2017] [proxy_fcgi:error] [pid 644:tid 139643563513600] [client 127.0.0.1:49336] AH01071: Got error 'PHP message: [PYDIO] IP 127.0.0.1 | user USERNAME | Error | Meta plugin | from Pydio\\Core\\PluginFramework\\PluginsService | Cannot instanciate Meta plugin, reason : Session credential are empty! Did you forget to check the Set Session Credential in the Authentication configuration panel?\nPHP message: [PYDIO] IP 127.0.0.1 | user USERNAME | Error | error l.311 | from PluginsService.php | message=Error while loading workspace smbhome : Session credential are empty! Did you forget to check the Set Session Credential in the Authentication configuration panel?\n'
> 
> ==> /var/log/apache2/pydio.access.log <==
> 127.0.0.1 - - [20/Jan/2017:15:27:46 -0500] "GET /api/24f2999b70f3cc385dbe2b3de05908f2/upload/put/Desktop?auth_hash=XXXXXXXXXXXXXXXXXXXXXXX%3AXXXXXXXXXXXXXXXXXXXXX&auth_token=XXXXXXXXXXXXXXXXXXXXXXXX&xhr_uploader=true HTTP/1.1" 200 404 "-" "Go-http-client/1.1"
> 10.2.0.64 - - [20/Jan/2017:15:27:46 -0500] "POST /index.php? HTTP/1.1" 200 260 "https://URL/ws-smbhome/Desktop" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36"

> ==> /var/log/pydio-booster.log <==

> Jan 20 15:27:46 pydio-01 pydio[4175]: INFO 2017/01/20 15:27:46.725625 [pydiomiddleware] START
> Jan 20 15:27:46 pydio-01 pydio[4175]: INFO 2017/01/20 15:27:46.725728 [pydiomiddleware] END - took %s 65.609µs
> Jan 20 15:27:46 pydio-01 pydio[4175]: ERROR 2017/01/20 15:27:46.725753 [pydiomiddleware] Not a match
> Jan 20 15:27:46 pydio-01 pydio[4175]: INFO 2017/01/20 15:27:46.725807 [pydiomiddleware] START
> Jan 20 15:27:46 pydio-01 pydio[4175]: INFO 2017/01/20 15:27:46.725928 [pydiomiddleware] Request Job Start {http  <nil> 127.0.0.1   false device=upload
> Jan 20 15:27:46 pydio-01 pydio[4175]: INFO 2017/01/20 15:27:46.726058 [pydiomiddleware] Node job: retrieved {24f2999b70f3cc385dbe2b3de05908f2 /Desktop
> Jan 20 15:27:46 pydio-01 pydio[4175]: INFO 2017/01/20 15:27:46.726196 [pydiomiddleware] END - took %s 383.298µs
> Jan 20 15:27:46 pydio-01 pydio[4175]: INFO 2017/01/20 15:27:46.726205 [pydiomiddleware] START
> Jan 20 15:27:46 pydio-01 pydio[4175]: INFO 2017/01/20 15:27:46.726289 [pydiomiddleware] Request Job Start {http  <nil> 127.0.0.1 /api/{repo}/upload/pu
> Jan 20 15:27:46 pydio-01 pydio[4175]: ERROR 2017/01/20 15:27:46.726342 [pydiomiddleware] Could not decode to auth
> Jan 20 15:27:46 pydio-01 pydio[4175]: INFO 2017/01/20 15:27:46.837032 [pydiomiddleware] END - took %s 110.819853ms
> Jan 20 15:27:46 pydio-01 pydio[4175]: INFO 2017/01/20 15:27:46.837072 [pydioupload] REQ START
> Jan 20 15:27:46 pydio-01 pydio[4175]: ERROR 2017/01/20 15:27:46.888166 [pydiomiddleware] Request: error while decoding  invalid character '<' looking
> Jan 20 15:27:46 pydio-01 pydio[4175]: ERROR 2017/01/20 15:27:46.888291 [pydioupload] Pydio Upload returns an error :  context canceled
> Jan 20 15:27:46 pydio-01 pydio[4175]: INFO 2017/01/20 15:27:46.888337 [pydioupload] REQ END took %s 51.257374ms
> Jan 20 15:27:46 pydio-01 pydio[4175]: panic: runtime error: slice bounds out of range [recovered]
> Jan 20 15:27:46 pydio-01 pydio[4175]: panic: runtime error: slice bounds out of range [recovered]
> Jan 20 15:27:46 pydio-01 pydio[4175]: panic: runtime error: slice bounds out of range
> Jan 20 15:27:46 pydio-01 pydio[4175]: goroutine 2280 [running]:
> Jan 20 15:27:46 pydio-01 pydio[4175]: panic(0xaae820, 0xc4200100c0)
> Jan 20 15:27:46 pydio-01 pydio[4175]: /usr/local/go/src/runtime/panic.go:500 +0x1a1
> Jan 20 15:27:46 pydio-01 pydio[4175]: github.com/pydio/pydio-booster/encoding/path.(*decodeState).unmarshal.func1(0xc4202c99c8)
> Jan 20 15:27:46 pydio-01 pydio[4175]: /home/pydio/tcAgent/work/f9990cede0540743/src/github.com/pydio/pydio-booster/encoding/path/decode.go:89 +0x11b
> Jan 20 15:27:46 pydio-01 pydio[4175]: panic(0xaae820, 0xc4200100c0)
> Jan 20 15:27:46 pydio-01 pydio[4175]: /usr/local/go/src/runtime/panic.go:458 +0x243
> Jan 20 15:27:46 pydio-01 pydio[4175]: github.com/pydio/pydio-booster/encoding/path.(*decodeState).unmarshal.func1(0xc4202c9580)
> Jan 20 15:27:46 pydio-01 pydio[4175]: /home/pydio/tcAgent/work/f9990cede0540743/src/github.com/pydio/pydio-booster/encoding/path/decode.go:89 +0x11b
> Jan 20 15:27:46 pydio-01 pydio[4175]: panic(0xaae820, 0xc4200100c0)
> Jan 20 15:27:46 pydio-01 pydio[4175]: /usr/local/go/src/runtime/panic.go:458 +0x243
> Jan 20 15:27:46 pydio-01 pydio[4175]: github.com/pydio/pydio-booster/encoding/path.(*decodeState).path(0xc4201c6c40, 0xa50900, 0xc420282c60, 0x16)
> Jan 20 15:27:46 pydio-01 pydio[4175]: /home/pydio/tcAgent/work/f9990cede0540743/src/github.com/pydio/pydio-booster/encoding/path/decode.go:364 +0x645
> Jan 20 15:27:46 pydio-01 pydio[4175]: github.com/pydio/pydio-booster/encoding/path.(*decodeState).value(0xc4201c6c40, 0xa50900, 0xc420282c60, 0x16)
> Jan 20 15:27:46 pydio-01 pydio[4175]: /home/pydio/tcAgent/work/f9990cede0540743/src/github.com/pydio/pydio-booster/encoding/path/decode.go:214 +0x111
> Jan 20 15:27:46 pydio-01 pydio[4175]: github.com/pydio/pydio-booster/encoding/path.(*decodeState).unmarshal(0xc4201c6c40, 0xa50900, 0xc420282c60, 0x0,
> Jan 20 15:27:46 pydio-01 pydio[4175]: /home/pydio/tcAgent/work/f9990cede0540743/src/github.com/pydio/pydio-booster/encoding/path/decode.go:104 +0x243
> Jan 20 15:27:46 pydio-01 pydio[4175]: github.com/pydio/pydio-booster/encoding/path.Unmarshal(0xc420111340, 0x20, 0x20, 0xa50900, 0xc420282c60, 0x19, 0
> Jan 20 15:27:46 pydio-01 pydio[4175]: /home/pydio/tcAgent/work/f9990cede0540743/src/github.com/pydio/pydio-booster/encoding/path/decode.go:47 +0x102
> Jan 20 15:27:46 pydio-01 pydio[4175]: github.com/pydio/pydio-booster/io.(*Node).UnmarshalPath(0xc420282b40, 0xc420111340, 0x20, 0x20, 0xc4207a0000, 0x
> Jan 20 15:27:46 pydio-01 pydio[4175]: /home/pydio/tcAgent/work/f9990cede0540743/src/github.com/pydio/pydio-booster/io/node.go:104 +0xad
> Jan 20 15:27:46 pydio-01 pydio[4175]: github.com/pydio/pydio-booster/encoding/path.(*decodeState).path(0xc4201c6b60, 0xad5400, 0xc420282b40, 0x16)
> Jan 20 15:27:46 pydio-01 pydio[4175]: /home/pydio/tcAgent/work/f9990cede0540743/src/github.com/pydio/pydio-booster/encoding/path/decode.go:275 +0xb69
> Jan 20 15:27:46 pydio-01 systemd[1]: pydio-booster.service: main process exited, code=exited, status=2/INVALIDARGUMENT
> Jan 20 15:27:46 pydio-01 systemd[1]: Unit pydio-booster.service entered failed state.
> Jan 20 15:27:46 pydio-01 pydio[4175]: github.com/pydio/pydio-booster/encoding/path.(*decodeState).value(0xc4201c6b60, 0xad5400, 0xc420282b40, 0x16)
> Jan 20 15:27:46 pydio-01 pydio[4175]: /home/pydio/tcAgent/work/f9990cede0540743/src/github.com/pydio/pydio-booster/encoding/path/decode.go:214 +0x111
> Jan 20 15:27:46 pydio-01 pydio[4175]: github.com/pydio/pydio-booster/encoding/path.(*decodeState).unmarshal(0xc4201c6b60, 0xad5400, 0xc420282b40, 0x0,
> root@pydio-01:~# journalctl -u pydio-booster -b | grep 15:27:46
> Jan 20 15:27:46 pydio-01 pydio[4175]: INFO 2017/01/20 15:27:46.725625 [pydiomiddleware] START
> Jan 20 15:27:46 pydio-01 pydio[4175]: INFO 2017/01/20 15:27:46.725728 [pydiomiddleware] END - took %s 65.609µs
> Jan 20 15:27:46 pydio-01 pydio[4175]: ERROR 2017/01/20 15:27:46.725753 [pydiomiddleware] Not a match
> Jan 20 15:27:46 pydio-01 pydio[4175]: INFO 2017/01/20 15:27:46.725807 [pydiomiddleware] START
> Jan 20 15:27:46 pydio-01 pydio[4175]: INFO 2017/01/20 15:27:46.725928 [pydiomiddleware] Request Job Start {http  <nil> 127.0.0.1   false device=upload&get_action=keystore_generate_auth_token } [] map[device:[upload] get_action:[keystore_generate_auth_token]] token
> Jan 20 15:27:46 pydio-01 pydio[4175]: INFO 2017/01/20 15:27:46.726058 [pydiomiddleware] Node job: retrieved {24f2999b70f3cc385dbe2b3de05908f2 /Desktop Home Network 2015.png {0 false false false    { } {     false    }}} from /io/24f2999b70f3cc385dbe2b3de05908f2/Desktop/Home Network 2015.png
> Jan 20 15:27:46 pydio-01 pydio[4175]: INFO 2017/01/20 15:27:46.726196 [pydiomiddleware] END - took %s 383.298µs
> Jan 20 15:27:46 pydio-01 pydio[4175]: INFO 2017/01/20 15:27:46.726205 [pydiomiddleware] START
> Jan 20 15:27:46 pydio-01 pydio[4175]: INFO 2017/01/20 15:27:46.726289 [pydiomiddleware] Request Job Start {http  <nil> 127.0.0.1 /api/{repo}/upload/put/{nodedir}  false xhr_uploader=true } [[X-File-Direct-Upload request-options] [X-Pydio-Admin-Auth XXXXXXXXXX:XXXXXXXXXXXX] [X-File-Name {nodename}]] map[xhr_uploader:[true]] options
> Jan 20 15:27:46 pydio-01 pydio[4175]: ERROR 2017/01/20 15:27:46.726342 [pydiomiddleware] Could not decode to auth
> Jan 20 15:27:46 pydio-01 pydio[4175]: INFO 2017/01/20 15:27:46.837032 [pydiomiddleware] END - took %s 110.819853ms
> Jan 20 15:27:46 pydio-01 pydio[4175]: INFO 2017/01/20 15:27:46.837072 [pydioupload] REQ START
> Jan 20 15:27:46 pydio-01 pydio[4175]: ERROR 2017/01/20 15:27:46.888166 [pydiomiddleware] Request: error while decoding  invalid character '<' looking for beginning of value
> Jan 20 15:27:46 pydio-01 pydio[4175]: ERROR 2017/01/20 15:27:46.888291 [pydioupload] Pydio Upload returns an error :  context canceled
> Jan 20 15:27:46 pydio-01 pydio[4175]: INFO 2017/01/20 15:27:46.888337 [pydioupload] REQ END took %s 51.257374ms
> Jan 20 15:27:46 pydio-01 pydio[4175]: panic: runtime error: slice bounds out of range [recovered]
> Jan 20 15:27:46 pydio-01 pydio[4175]: panic: runtime error: slice bounds out of range [recovered]
> Jan 20 15:27:46 pydio-01 pydio[4175]: panic: runtime error: slice bounds out of range
> Jan 20 15:27:46 pydio-01 pydio[4175]: goroutine 2280 [running]:
> Jan 20 15:27:46 pydio-01 pydio[4175]: panic(0xaae820, 0xc4200100c0)
> Jan 20 15:27:46 pydio-01 pydio[4175]: /usr/local/go/src/runtime/panic.go:500 +0x1a1
> Jan 20 15:27:46 pydio-01 pydio[4175]: github.com/pydio/pydio-booster/encoding/path.(*decodeState).unmarshal.func1(0xc4202c99c8)
> Jan 20 15:27:46 pydio-01 pydio[4175]: /home/pydio/tcAgent/work/f9990cede0540743/src/github.com/pydio/pydio-booster/encoding/path/decode.go:89 +0x11b
> Jan 20 15:27:46 pydio-01 pydio[4175]: panic(0xaae820, 0xc4200100c0)
> Jan 20 15:27:46 pydio-01 pydio[4175]: /usr/local/go/src/runtime/panic.go:458 +0x243
> Jan 20 15:27:46 pydio-01 pydio[4175]: github.com/pydio/pydio-booster/encoding/path.(*decodeState).unmarshal.func1(0xc4202c9580)
> Jan 20 15:27:46 pydio-01 pydio[4175]: /home/pydio/tcAgent/work/f9990cede0540743/src/github.com/pydio/pydio-booster/encoding/path/decode.go:89 +0x11b
> Jan 20 15:27:46 pydio-01 pydio[4175]: panic(0xaae820, 0xc4200100c0)
> Jan 20 15:27:46 pydio-01 pydio[4175]: /usr/local/go/src/runtime/panic.go:458 +0x243
> Jan 20 15:27:46 pydio-01 pydio[4175]: github.com/pydio/pydio-booster/encoding/path.(*decodeState).path(0xc4201c6c40, 0xa50900, 0xc420282c60, 0x16)
> Jan 20 15:27:46 pydio-01 pydio[4175]: /home/pydio/tcAgent/work/f9990cede0540743/src/github.com/pydio/pydio-booster/encoding/path/decode.go:364 +0x645
> Jan 20 15:27:46 pydio-01 pydio[4175]: github.com/pydio/pydio-booster/encoding/path.(*decodeState).value(0xc4201c6c40, 0xa50900, 0xc420282c60, 0x16)
> Jan 20 15:27:46 pydio-01 pydio[4175]: /home/pydio/tcAgent/work/f9990cede0540743/src/github.com/pydio/pydio-booster/encoding/path/decode.go:214 +0x111
> Jan 20 15:27:46 pydio-01 pydio[4175]: github.com/pydio/pydio-booster/encoding/path.(*decodeState).unmarshal(0xc4201c6c40, 0xa50900, 0xc420282c60, 0x0, 0x0)
> Jan 20 15:27:46 pydio-01 pydio[4175]: /home/pydio/tcAgent/work/f9990cede0540743/src/github.com/pydio/pydio-booster/encoding/path/decode.go:104 +0x243
> Jan 20 15:27:46 pydio-01 pydio[4175]: github.com/pydio/pydio-booster/encoding/path.Unmarshal(0xc420111340, 0x20, 0x20, 0xa50900, 0xc420282c60, 0x19, 0x8)
> Jan 20 15:27:46 pydio-01 pydio[4175]: /home/pydio/tcAgent/work/f9990cede0540743/src/github.com/pydio/pydio-booster/encoding/path/decode.go:47 +0x102
> Jan 20 15:27:46 pydio-01 pydio[4175]: github.com/pydio/pydio-booster/io.(*Node).UnmarshalPath(0xc420282b40, 0xc420111340, 0x20, 0x20, 0xc4207a0000, 0x7f149a612098)
> Jan 20 15:27:46 pydio-01 pydio[4175]: /home/pydio/tcAgent/work/f9990cede0540743/src/github.com/pydio/pydio-booster/io/node.go:104 +0xad
> Jan 20 15:27:46 pydio-01 pydio[4175]: github.com/pydio/pydio-booster/encoding/path.(*decodeState).path(0xc4201c6b60, 0xad5400, 0xc420282b40, 0x16)
> Jan 20 15:27:46 pydio-01 pydio[4175]: /home/pydio/tcAgent/work/f9990cede0540743/src/github.com/pydio/pydio-booster/encoding/path/decode.go:275 +0xb69
> Jan 20 15:27:46 pydio-01 systemd[1]: pydio-booster.service: main process exited, code=exited, status=2/INVALIDARGUMENT
> Jan 20 15:27:46 pydio-01 systemd[1]: Unit pydio-booster.service entered failed state.
> Jan 20 15:27:46 pydio-01 pydio[4175]: github.com/pydio/pydio-booster/encoding/path.(*decodeState).value(0xc4201c6b60, 0xad5400, 0xc420282b40, 0x16)
> Jan 20 15:27:46 pydio-01 pydio[4175]: /home/pydio/tcAgent/work/f9990cede0540743/src/github.com/pydio/pydio-booster/encoding/path/decode.go:214 +0x111
> Jan 20 15:27:46 pydio-01 pydio[4175]: github.com/pydio/pydio-booster/encoding/path.(*decodeState).unmarshal(0xc4201c6b60, 0xad5400, 0xc420282b40, 0x0, 0x0)
> Jan 20 15:27:46 pydio-01 pydio[4175]: /home/pydio/tcAgent/work/f9990cede0540743/src/github.com/pydio/pydio-booster/encoding/path/decode.go:104 +0x243
> Jan 20 15:27:46 pydio-01 pydio[4175]: github.com/pydio/pydio-booster/encoding/path.Unmarshal(0xc420111340, 0x20, 0x20, 0xad5400, 0xc420282b40, 0x20, 0x2)
> Jan 20 15:27:46 pydio-01 pydio[4175]: /home/pydio/tcAgent/work/f9990cede0540743/src/github.com/pydio/pydio-booster/encoding/path/decode.go:47 +0x102
> Jan 20 15:27:46 pydio-01 pydio[4175]: github.com/pydio/pydio-booster/io.NewNode(0xc4202c9d30, 0x3, 0x3, 0x1)
> Jan 20 15:27:46 pydio-01 pydio[4175]: /home/pydio/tcAgent/work/f9990cede0540743/src/github.com/pydio/pydio-booster/io/node.go:54 +0x16a
> Jan 20 15:27:46 pydio-01 pydio[4175]: github.com/pydio/pydio-booster/server/middleware/pydioupload.handle.func1(0x0)
> Jan 20 15:27:46 pydio-01 pydio[4175]: /home/pydio/tcAgent/work/f9990cede0540743/src/github.com/pydio/pydio-booster/server/middleware/pydioupload/handler.go:191 +0x73b
> Jan 20 15:27:46 pydio-01 pydio[4175]: github.com/pydio/pydio-booster/server/middleware/pydioupload.errHandle.func1(0xc42006c600, 0xc42067b600)
> Jan 20 15:27:46 pydio-01 pydio[4175]: /home/pydio/tcAgent/work/f9990cede0540743/src/github.com/pydio/pydio-booster/server/middleware/pydioupload/handler.go:92 +0x27
> Jan 20 15:27:46 pydio-01 pydio[4175]: created by github.com/pydio/pydio-booster/server/middleware/pydioupload.errHandle
> Jan 20 15:27:46 pydio-01 pydio[4175]: /home/pydio/tcAgent/work/f9990cede0540743/src/github.com/pydio/pydio-booster/server/middleware/pydioupload/handler.go:92 +0x16
> 

Chrome then reports switching back to polling and pydio-booster restarts.  Removing !$bypass_pwd or !empty($pwd) from AuthServices makes everything behave correctly again.

**Comment by carlchan** [comment]
Upgrade to 7.0.4 was successful.  Userside messages of "Session Credential Empty" are now gone, but it seems Pydio Booster is now broken.  The messages are now being thrown by Pydio Booster instead:

`Feb 23 10:09:57 pydio pydio[16997]: 127.0.0.1#011USERNAME#011Pydio\Core\PluginFramework\PluginsService#011Meta plugin#011Cannot instanciate Meta plugin, reason : Session credential are empty! Did you forget to check the Set Session Credential in the Authentication configuration panel?`

**Comment by ullibo** [comment]
I had the same problem with fsmounter + devil during indexing in 8.01. The mount of the smb-share via udevil worked fine but indexing throws the same error as carlchan told.  Removing  "&& !$bypass_pwd" in the authservice.php File solved the indexing-error. Is there a reason why the fix isn´t build in ?

**Comment by c12simple** [comment]
Hello,
@carlchan  Error when deleting: fixed in 8.0.1
@ullibo Error when indexing: fixed by this commit
https://github.com/pydio/pydio-core/commit/090d42e145303dc4b6c11eda7060a79ff30643a8

**Comment by ullibo** [comment]
@carlchan: Thank you very much !!!
