### ISSUE TITLE
WebDav: If a file is modified over WebDav nothing is put in ajxp_changes

### ISSUE THREAD

**Issue by phiyuku** [pydio/pydio-core#1318]
If a file is modified over WebDav nothing at all is recorded in ajxp_changes. This causes PydioSync to not sync the changes. If it is modified over the WebUI a type of "content" is added to ajxp_changes. I think the same expectation should be there if modified over WebDav.

Pydio 7.0.3

Edit: This will also happen with creates as well (of course) but, just wanted to add to that since I have another WebDav client create a file as xxx.ext.tactipart and then move it to xxx.ext

**Comment by cdujeu** [comment]
https://github.com/pydio/pydio-sync/issues/156
