### ISSUE TITLE
Multiple workspace folders when username has spaces at end

### ISSUE THREAD

**Issue by flipswitchingmonkey** [pydio/pydio-core#1322]
Pydio Free / 7.0.3

This is a pretty major issue imho. To recreate:
- Create any new user. Log in once. Notice the user's workspace folder gets created on disk.
- Log out
- Log in again, but this time put a single (or multiple, doesn't matter) space character behind the username.
> authentication works! obviously the trailing space is cut for authentication
That's the first bug. It really shouldn't authenticate with faulty characters. But it gets worse:
> notice how a second workspace folder gets created for the username with the extra spaces!

So, depending on how many spaces a user puts at the end, he can create dozens of workspaces, each working with a single login.

**Comment by flipswitchingmonkey** [comment]
It's easy to fix in plugins/authfront.session_login/SessionLoginFrontend.php:
change
` $userId = (isSet($httpVars["userid"]) ? $httpVars["userid"] : null);`
to
`$userId = (isSet($httpVars["userid"]) ? trim($httpVars["userid"]) : null);`

**Comment by cdujeu** [comment]
ok for me :-)
