### ISSUE TITLE
Download with PowerFS is broken from 7.0.2

### ISSUE THREAD

**Issue by Nanomani** [pydio/pydio-core#1325]
Download with PowerFS is broken from 7.0.2
Temp_archive_file.zip in temp_path is created
But download process never start.

On default repo there is no issue
Appear only with new FS standard repo

Tested without accent in absolute path and files.

Rollback to Pydio 7.0.1 fixe this issue
Tested only on Windows

**Comment by faelnor** [comment]
Yup, same problem here. Zip download works on certain repos but not everywhere, maybe a permission issue when trying to move back the zip from /tmp? Although I checked that all my paths are writable.

**Comment by cdujeu** [comment]
Please verify, there was a f*cking typo... Sorry for taking so much time.

**Comment by faelnor** [comment]
The fix resolved this issue for me. Thank you very much!

**Comment by Nanomani** [comment]
Yep fixed for me too. Thx
