### ISSUE TITLE
Method createIndexedDocument in index.lucene is called multiple times on the same node

### ISSUE THREAD

**Issue by bures** [pydio/pydio-core#1330]
When indexation is triggered from the UI, the CoreIndexer schedules the indexation as a task, which in the call chain includes TaskService::publishTaskUpdate. Method publishTaskUpdate triggers the node.meta_change, to which Lucene reacts by reindexing the node.

I did not investigate it further, but it seems that the reindexing was triggered during the computation multiple times for the same node.

Eventually this successfully finishes, just it does not seem right that the same node gets indexed multiple times. 

I have briefly checked, it seems that the same problem might be for index.elasticsearch. Other plugins seem to be unaffected as they do not combine the use of tasks with being trigerred by node.meta_change.

**Comment by cdujeu** [comment]
Hi tomas, 
Ok thanks for reporting, i'll try to reproduce that.
-c
