### ISSUE TITLE
Copy & Paste links with Firefox

### ISSUE THREAD

**Issue by phil8900** [pydio/pydio-core#1332]
The issue descirbed here: https://pydio.com/forum/f/topic/link-share-firefox/ is still there with FF52.

I can't copy&paste any links with firefox and can't mark text - it is pretty messed up.

**Comment by cdujeu** [comment]
Hi, what version are you using?

**Comment by cdujeu** [comment]
no feedback

**Comment by GCHPX** [comment]
can you please reopen this issue as it still doesn´t work? i can provide you the needed feedback
