### ISSUE TITLE
[urgent] Php 7.1 support

### ISSUE THREAD

**Issue by cdujeu** [pydio/pydio-core#1334]
Many forum threads point to issues when upgrading to php 7.1

**Comment by drzhouq** [comment]
It is true. It seems the most latest release work with php7.1 is pydio 6.54. And we have the issue of mcrypt_create_iv being depreciated. I changed that function call to use random_bytes and seems to work.

**Comment by cdujeu** [comment]
Should be fixed by https://github.com/pydio/pydio-core/commit/72cebac3bf11a6c868abd6c24d9a15704c8fe864
Can you try to apply the same changes in your install?

**Comment by josh4trunks** [comment]
72cebac worked for me after upgrading to PHP7.1 =]

**Comment by transpine** [comment]
72cebac Thank!!. Also worked for me. Php7.1. I added "$current = $this;' and changed some '$this' to '$current' as the fixes. When will it be released officially?
