### ISSUE TITLE
WebDAV hidden files not possible

### ISSUE THREAD

**Issue by mikerhyner** [pydio/pydio-core#1335]
It’s still not possible to create hidden files (.*) using WebDAV, such files will not exist after creation (immediately deleted or not even stored).

I’ve read  [https://pydio.com/forum/f/topic/webdav-issues/#post-109085 this discussion], but even with the most current pydio release, there’s not even existing a file named “class.AJXP_Sabre_Collection.php”, so I’m not able to try to work around that issue.

Hidden files really should work, as there are some applications (e.g. KeeWeb [1] or Office for Mac) that allow to use WebDAV as their storage backend, and makes excessively use of hidden files for temporary file storage. So by now, Pydio based services (like our “wulche.ch”) unfortunately cannot really be used together with such applications.

Version tested: 7.0.4 (Enterprise)

[1] [https://keeweb.info/]

**Comment by cdujeu** [comment]
Hi Mike, it's working actually. 
Just go to the global options of access.fs plugin, and enable the "Show Hidden Files" parameters. I can successfully create .* files with WebDAV.
