### ISSUE TITLE
Special characters in username

### ISSUE THREAD

**Issue by mbadici** [pydio/pydio-core#1337]
We create a new user in Pydio 7.0.4 .
In the second tab “User Information” the full name contained a special char ( an ampersand “& ” )
The settings where accepted but at the first login the user had a parsing error
( DOMDocument::loadXML(): EntityRef: expecting ‘:’ in entity, line: 1 )
I think it should either not accept the name from the begining ( the easy way) or escape the special chars in order to allow them.

**Comment by cdujeu** [comment]
Hi, should be fixed by https://github.com/pydio/pydio-core/commit/94e8b7a4c82368397c6e9b8e44a9622352dc0226
