### ISSUE TITLE
PhpMailLite.php fail requiring vendor/autoload.php

### ISSUE THREAD

**Issue by GoZOo** [pydio/pydio-core#1341]
I use Pydio open-source version 7.0.4 , when i use a feature which send mail (creating a user or resetting password), i have the following error message:
`PhpMailLite.php	message=require_once(vendor/autoload.php): failed to open stream: No such file or directory`

Thanks for your help

**Comment by Ardinis** [comment]
Confirmed with quota user too.
Every function using mail triggers this error.
There is no vendor folder in plugins/mailer.phpmailer-lite folder.

**Comment by cdujeu** [comment]
Hi guys, 
Sorry for the late answer. Just to make sure, what kind of installation are you using? (zip, targz, rpm, deb) ? 
thx

**Comment by GoZOo** [comment]
Installation has been made long time ago. I don't remember which one between zip or targz was used. Last updates have been made thanks to the built-in update feature.

**Comment by GoZOo** [comment]
I found a 6.2.1.tar.gz on my server, so the last manual update or installation should be done thanks to targz. I hope this will help

**Comment by cdujeu** [comment]
Go inside plugins/mailer.phpmailer-lite/, and run `composer install`.
You must first install composer on the server, see https://getcomposer.org 
Probably an issue in the update process.

**Comment by GoZOo** [comment]
I confirm that fix my issue. Thanks @cdujeu !

**Comment by davidrahusen** [comment]
Dear all, this doesn't work, have no console access to my webspace resp. no PHP from within console. Any other chance to get that annoying "vendor/autoload.php"?

**Comment by cdujeu** [comment]
hi @davidrahusen just grab the latest zip/tar.gz of pydio and drop in the plugins/mailer.phpmailer-lite/vendor folder inside your install.

**Comment by davidrahusen** [comment]
Forgot to comment ... got it work. Thanx!
