### ISSUE TITLE
Opening an image in the pixlr editor if the site is https

### ISSUE THREAD

**Issue by slvxstar** [pydio/pydio-core#1343]
If the site works by https then the pictures do not open in the pixlr editor

**Comment by cdujeu** [comment]
Hi, check the content of the plugin (inside the PHP class), and switch http://pixlr.com/ to https://pixlr.com/ ... 
Should do the trick, already commited in develop branch.

**Comment by slvxstar** [comment]
Clear! I'll try to fix it myself.
You can close to commit.
