### ISSUE TITLE
Improve upload notification box

### ISSUE THREAD

**Issue by CarstenGrohmann** [pydio/pydio-core#1346]
![notification_box](https://cloud.githubusercontent.com/assets/4849907/25760347/abc92a60-31d6-11e7-932c-4500ee8e713a.png)

The icon in the dialog is nearly invisible as the red drawn box shows. Please choose a better visible icon.

The current text `Uploading <number> files` is inspecific, because you can see if this is the absolute number of files or the outstanding files to upload. Thereby I suggest to change it to a more specific message like

 * `Uploading file <current number> of <absolute count>`

or
 * `<number of outstanding files> files left to upload`

Regards,
Carsten

**Comment by cdujeu** [comment]
Should have been fixed already.
