### ISSUE TITLE
Cannot select multiple files using Ctrl + left click with pydio 8.0

### ISSUE THREAD

**Issue by Nanomani** [pydio/pydio-core#1351]

**Comment by Nanomani** [comment]
tested with all latest navigator

**Comment by Nanomani** [comment]
sorry to insist.
But is there any little chance this issuse be concidered before 8.0.3 ?
It is the only reason why we stay with pydio 7.0.4

**Comment by cdujeu** [comment]
ok ok, this is because it's you ;-)

**Comment by Nanomani** [comment]
ok wow i appreciate the effort
Thank you ;-)
