### ISSUE TITLE
Slow loading Shared links page

### ISSUE THREAD

**Issue by ravicacat** [pydio/pydio-core#1362]
Hi!

I'm using Pydio (good job by the way!!) for sharing folders with some files in it.

When opening link webpage goes blank and takes several seconds to load Pydio interface and download menu options.
After that, downloading files is fast.

I don't know if I can speed up this some way, or perhaps generating direct download links? Is there any way to do that? Perhaps not loading the interfaces is much faster.

Thanks for all!

**Comment by cdujeu** [comment]
hello, please use the forum and do not open issues until they are fully "qualified".
-c
