### ISSUE TITLE
Issue when using a S3 repo with AJXP_USER variable.

### ISSUE THREAD

**Issue by smichelet** [pydio/pydio-core#1365]
Hello.

Some informations about my installation :
- OS : CentOS 7
- Pydio Community version 8.0.0-1 : Package pydio-all-8.0.0-1.el7.centos.noarch
- I followed the documentation to install Pydio : https://pydio.com/en/docs/v8/centosrhel-systems

I'd like to use a LDAP authentication and users directory on a AWS S3 repository.
When the configuration of my container is mybucket for example, everything works fine.
But when I configure my container as mybucket/AJXP_USER I get an error message when I try to browse my repo.

It worked on version 6.0.8 but it seems not to work anymore since the version 7.
I've got the same problem mentionned on this post on the Pydio Forum and I can't find an answer to solve this issue :
https://pydio.com/forum/f/topic/same-s3-workspace-no-more-working-on-pydio-7/

Here are some screenshots so you can see my configuration and the error message. If you want more informations, please ask me.

![001](https://user-images.githubusercontent.com/19533272/26835929-b60546be-4ad9-11e7-9a8e-afd42dcf4445.png)

![002](https://user-images.githubusercontent.com/19533272/26835960-cb396d80-4ad9-11e7-9c44-bfeac2fe83a0.png)

**Comment by cdujeu** [comment]
hi, we really prefer that you use forum threads instead of GitHub until the bug is fully qualified...
But well, you got enough screenshots, ok for this time :-)
Did you try to swith the "Signature Version" of the access.s3 plugin to many values.
-c

**Comment by smichelet** [comment]
Hmm sorry about the way to open tickets :)
Yes I already tried to switch between version 2 and version 4 without success :/
I did it in the web configuration of my repository.

**Comment by piranhaphish** [comment]
This is affecting me as well on 8.0.1.

I upgraded from 6.0.8, then configured an S3 repository in bootstrap_repositories.php using ".../AJXP_USER". I receive the same SignatureDoesNotMatch error.

In my case, the usernames are email address, so both the forward-slash (from the config setting) and the at-sign (from the username) are both URL-encoded.

Do you have any ideas for a workaround for the moment, as I'm eager to upgrade from v6.

**Comment by piranhaphish** [comment]
Okay, I found a workaround for my particular use case.

Because I'm using bootstrap_repositories.php and AJXP_USER is in the path portion, I was able to set this:

    "CONTAINER"    => "<bucket name>",
    "PATH"         => "/AJXP_USER",

I'm not sure if there's a way to configure a PATH for a normal workspace using the settings GUI or not. And I don't suppose this would work if the username needed to be part of the bucket name itself and that username contained symbols that get urlescape'd.

**Comment by smichelet** [comment]
Hi.

Hmm, when configuring a workspace using the GUI it doesn't add lines in the /etc/pydio/bootstrap_repositories.php
How did you to use bootstrap repositories to configure your workspaces, please ?

By the way, on the GUI, when configuring the workspace, it seems the field "Alias" is used to determinate the path of the remote storage space. But there is others issues, it seems it doesn't use the macro like "AJXP_USER" and we can reach a parent directory modifying the URL.

**Comment by piranhaphish** [comment]
bootstrap_repositories.php is for "hard-coded" repositories (i.e. My Files, Common Files). They cannot be created or editing using the GUI and, thus, are really for system administrators to define and not Pydio administrators.

I used the [Pydio S3 Documentation](https://pydio.com/en/docs/references/plugins/access/s3) to update/add the following parameters to the "My Files" section:

    …
    "API_KEY"     => "<my api key>",
    "SECRET_KEY"  => "<my secret>",
    "CONTAINER"   => "<my container>",
    "REGION"      => "us-east-1",
    "API_VERSION" => "latest",
    "PATH"        => "/AJXP_USER",
    …

**Comment by smichelet** [comment]
I confirm, it works just well like this. Thanks for your help. It's an alternative to make it work instead of using the GUI.
