### ISSUE TITLE
pydio 8 : Modified dates not readable in detailed display

### ISSUE THREAD

**Issue by hugoShaka** [pydio/pydio-core#1369]
When browsing the files on a Workspace the "Modified" column content is not shown in human readable format.
This happens only in "Detail mode".

**Example :**
![picture of the issue](https://image.ibb.co/cvuXHa/screen.png)

**Environement  :** 
- PHP version 7.1.6
- Locales : fr_FR.UTF-8
- Pydio migrated from 6 to 8 manually (fresh install but database migrated with the scripts [here](https://github.com/pydio/pydio-core/tree/develop/dist/php))
- Full diagnostic paste [here : http://paste.debian.net/971415/](http://paste.debian.net/971415/)

**Comment by cdujeu** [comment]
should be fixed in develop branch
