### ISSUE TITLE
Pixlr plugin still redirect to http while host is https

### ISSUE THREAD

**Issue by bitsandnumbers** [pydio/pydio-core#1371]
... thus creating a mixed contents issue in the web browser and preventing Pixlr to open. We get a white page instead of the editor ...

So basically the Pixlr plugin try to open "http://pixlr.com" instead of "https://pixlr.com" when Pydio host is in https.

The strange thing is that PixlrEditor.php has the right "https" string inside the PHP class, so it should not happen. It *could* be an issue on Pixlr's end.

Workaround right now is to disable mixed contents protection in the web browser, which is a different operation depending on the browser. Check the manual of your browser for help with that.

Steps to reproduce : 
- Linux server : Ubuntu 16.04 on Scaleway
- SSL certificate from Letsencrypt
- Docker image from linuxserver.io
- Pydio 8.0.1
- Trying to open an image file (PNG) with Pixlr plugin from "my-files" workspace

**Comment by cdujeu** [comment]
Seems like Pixlr is sending back http:// whatever we ask
Can you try that, in plugins/editor.pixlr/PixlrEditor.php
Line 130, replace the existing $response = $response .... code  with
```
            // Make sure we load the https
            $redirect = $postResponse->getHeader("Location");
            $redirect = str_replace("http://", "https://", $redirect);
            // Send redirect Header
            $response = $response
                ->withStatus(302)
                ->withHeader("Location", $redirect);

```
I think it does the job, can you confirm?

**Comment by bitsandnumbers** [comment]
Hi @cdujeu , thank you for the answer, but I no longer use pydio. I was using it for work but the desktop sync didn't suit my needs. It's a shame because everything else was very good. So, I cannot give any more feedback about this issue. Sorry.

**Comment by cdujeu** [comment]
ok np, thanks
