### ISSUE TITLE
failedAJXP.log should probably be a tmpfile

### ISSUE THREAD

**Issue by exadeci** [pydio/pydio-core#1372]
When running multiples instances of Pydio on a server if 2 different instances end up creating `failedAJXP .log` the second instance won't have the right to replace it, so it should probably be a:
https://secure.php.net/manual/en/function.tmpfile.php

https://github.com/pydio/pydio-core/blob/68e50b20717fe764ee2ceccd41cf99e0850e8bcb/core/src/core/src/pydio/Core/Utils/Http/BruteForceHelper.php#L44

https://github.com/pydio/pydio-core/blob/68e50b20717fe764ee2ceccd41cf99e0850e8bcb/core/src/core/src/pydio/Core/Utils/Http/BruteForceHelper.php#L69

**Comment by cdujeu** [comment]
mmm, actually if it's a tmpfile the value will be different on each request, so we won't be able to reopen it. I think that you'd better set different temporary folders for each instance instead. You can set the temp folder in the settings.
