### ISSUE TITLE
searchbar dissapears if no results are found

### ISSUE THREAD

**Issue by psy** [pydio/pydio-core#1376]
While searching for users (via Addressbook -> Directory) the searchbar dissapears if there are no results and you have to close and reopen the addressbook to start a new search. See attached screenshots:

![selection_250](https://user-images.githubusercontent.com/1132707/27834819-ba87f6d6-60d8-11e7-9f1a-898f5d76a875.png)

![selection_251](https://user-images.githubusercontent.com/1132707/27834816-b73fd4f8-60d8-11e7-9b9f-857e5a3220a6.png)

**Comment by cdujeu** [comment]
indeed, thx
