### ISSUE TITLE
logger.text: no config options

### ISSUE THREAD

**Issue by psy** [pydio/pydio-core#1377]
The logger.text plugin seems to have no config options to change the path where the logs are stored. As it tryies to store the logs in AJXP_INSTALL_PATH/data/logs by default, this leads to logs in /usr/share/pydio/ if you install it via your repositories (at least on debian), where the webserver isn't allowed to write.

**Comment by cdujeu** [comment]
when you switch to the text logger in the admin interface, there IS an option to choose where to store the logs.

![capture d ecran 2017-09-26 a 10 48 01](https://user-images.githubusercontent.com/2465057/30851217-3b8bf276-a2a8-11e7-920e-c27b0edec1be.png)
