### ISSUE TITLE
Upload modal window display issue

### ISSUE THREAD

**Issue by jamaa** [pydio/pydio-core#1384]
Using pydio 8.0.1

I have only one Uploader activated (PLUpload). The content of the upload modal seems to be restricted to the width of the one tab present at the top, making it very narrow in this case. See a screenshot here: http://imgur.com/kHxj96k

I think the upload interface should utilize the full width of the modal window, independent of the number of tabs present at the top.

(originally posted [here](https://pydio.com/forum/f/topic/upload-modal-window-display-issue/)

**Comment by cdujeu** [comment]
w-i-p

**Comment by cdujeu** [comment]
FYI, if you want to apply the patch, rebuild js library by running `npm install && grunt` inside the access.fs/ plugin folder
