### ISSUE TITLE
Remember me feature work half

### ISSUE THREAD

**Issue by kilian442** [pydio/pydio-core#1386]
I'm sorry in advance for my bad english, i'm french :)

Everytime i want to reconnect to my pydio instalation after using the remember me feature, the login popup stay displayed like this and blocking me for doing anything in the background
![the problem](https://user-images.githubusercontent.com/1560888/29979830-62314c06-8f47-11e7-83a4-ddd7d1096147.png)
but if i retype the url of the pydio instalation, everything work. (http://192.168.1.17/pydio in this screenshot)

This issue happen in edge, firefox and chrome (when i write this message) on a Windows OS (client), i can't test other configuration.

I don't know if this can help you, but here is my instalation:
- Running on apache 2 server, hosted by a Raspbery Pi 3 with a Raspbian 8
- The pydio instalation is on /pydio and work with an alias in apache configuration
- Pydio is using a MySQL server in the same machine
- Login and Passwd are stored in DB
- Pydio is using MemCached as cache server

here is the diagnostic page of pydio
```
Client : Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:55.0) Gecko/20100101 Firefox/55.0
Crypto Extension Detected : OpenSSL
Command Line Available : Yes
DOM Enabled : Yes
Exif Enabled : Yes
GD Enabled : Yes
Upload Max Size : 1G
Memory Limit : 128M
Max execution time : 30
Safe Mode : 0
Safe Mode GID : 0
Xml parser enabled : 1
Server OS : Linux
Session Save Path : /var/www/pydio/data/sessions
Session Save Path Writeable : Yes
PHP Version : 5.6.30-0+deb8u1
Locale : C
Directory Separator : /
PHP Opcode Cache extension loaded : Yes
PHP INTL extension loaded : Yes
PHP Output Buffer disabled : Yes
PHP File Uploads enabled : Yes
Magic quotes disabled : Yes
Upload Tmp Dir Writeable : Yes
PHP Upload Max Size : 1073741824
PHP Post Max Size : 1073741824
Users enabled : Yes
Guest enabled : No
Writeable Folders : [<b>cache</b>:true,<br> <b>data</b>:true]
Zlib Enabled : Yes
```

If you have any question about my configuration, send me a mail at redhenessddns@gmail.com

**Comment by cdujeu** [comment]
Hi @kilian442 
thanks for the detailed report
-c

**Comment by manipulator01** [comment]
+1

**Comment by alicancakil** [comment]
Hello @cdujeu 
I am having the same issue with Pydio 8.0.1 on Ubuntu 16.04.2 LTS and PHP 7.0.22

I understand that you're aware of the issue but is there any workaround available for the time being?

Thank you kindly <3

**Comment by cdujeu** [comment]
we'll try to look at it this week.

**Comment by cdujeu** [comment]
Ok I have good news here : https://github.com/pydio/pydio-core/commit/65529883f7b29889168c4418b60e6318cfd1052c
If you want to apply the fix, don't panic, there are a couple of changes, but you should be able to fix the problem by just applying the changes in the PHP files (not xml nor JS). See `core/src/core/src/pydio/Core/Services/UsersService.php` and `core/src/plugins/authfront.session_login/SessionLoginFrontend.php`

If you are motivated to apply the whole patch, after the update, you'll have to 
1 - clear the plugins cache (data/cache/plugins_*.*)
2 - rebuild JS libraries by calling `npm install && grunt` inside gui.ajax and core.authfront plugins folders.
3 - Make sure your browser cache is emptied.

After that, please confirm everything is working well :-). I've changed how the feature works for the sake of simplification, and it should make it much more robust.

**Comment by alicancakil** [comment]
Hello @cdujeu 

I've applied PHP changes that you published. _I wasn't motivated enough to apply the whole patch :)_

Now this shows up: https://i.imgur.com/nhxfAob.png

:(

**Comment by cdujeu** [comment]
hi, is this happening on all cases, or only when you try to reopen a browser with "remember me" previously checked? Did you make sure to totally wipe your browser cookies & caches?
