### ISSUE TITLE
SAMBA / SMB Workspace Driver - Buffer Issues

### ISSUE THREAD

**Issue by sduensin** [pydio/pydio-core#1387]
Specifying buffering in the SMB driver configuration (smb.php) prevents browsing large shares from a Windows host.  Removing SO_RCVBUF=8192 SO_SNDBUF=8192 fixes the issue.

See:  https://pydio.com/forum/f/topic/unable-to-download-several-files-from-smb-workspaces/#post-113784

**Comment by cdujeu** [comment]
@c12simple what do you think, shall we add that as a parameter? Do we know why there were these parameters at the first place?

**Comment by c12simple** [comment]
A param is added in config of smb plugins
https://github.com/pydio/pydio-core/commit/829dedcd5368e1a4676e5e4706ea92dd1788b1ce
