### ISSUE TITLE
Segmentation fault when indexing samba share with space in directory names

### ISSUE THREAD

**Issue by Madko** [pydio/pydio-core#1396]
I’m trying for the first time pydio so maybe I’m doing something wrong. I have activated the samba plugin, and in the web interface I can browse any samba shares. It’s working fine. But, the indexation is not working and seems to get stuck.

So I run the indexation with the CLI and I get this error:

```
[root@pydio-test pydio]# /opt/rh/rh-php56/root/usr/bin/php /usr/share/pydio/cmd.php -u=madko -a=index -r=samba
Please enter the password: 
*****************************
Current User is 'madko'
*****************************
Applying action 'index' on workspace Samba (3b683f9zz3ddfbcb960a670e7fa5b81)
<?xml version="1.0" encoding="UTF-8"?><tree ><message type="ERROR">FILE_IS_A_DIRECTORY opening remote file \TEST\SUBDIR\0 -</message></tree>
PHP Fatal error:  FILE_IS_A_DIRECTORY opening remote file \TEST\SUBDIR\0 - in /usr/share/pydio/plugins/access.smb/smb.php on line 280
PHP Fatal error:  Access to undeclared static property: Pydio\Access\Driver\StreamProvider\SMB\SMBAccessWrapper::$crtZip in /usr/share/pydio/plugins/access.smb/SMBAccessWrapper.php on line 198
Segmentation fault
```

So I have this directory “\TEST\SUBDIR\0 – TEST”, it seems that spaces in names are a problem ??

I’m using pydio-8.0.1-2.el7.centos.noarch

Best regards,
Edouard

**Comment by Madko** [comment]
Hello ? is there someone?

**Comment by cdujeu** [comment]
hi madko, 
sorry for the delay
can you please use the forum instead of posting in github? GH is for qualified bugs only, 
thx
-c

**Comment by cdujeu** [comment]
https://forum.pydio.com

**Comment by Madko** [comment]
I've come here because I had no answer on the forum, which was full of spam by the way... Seems now it has moved to discourse, but google auth is broken I can't log in anymore "Sorry, there was an error authorizing your account. Perhaps you did not approve authorization? "

**Comment by cdujeu** [comment]
can you try to register with an email instead of google maybe?

**Comment by Madko** [comment]
done with github auth, so something is definitively broken with google auth
https://forum.pydio.com/t/pydio-segfault-on-samba-share-with-spaces/110

**Comment by Madko** [comment]
where should we report bugs ?

**Comment by cdujeu** [comment]
it's not a bug until it's not qualified as such = easily reproducible :-) 
I'll ping c12simple again to carry on the discussion on your thread in the forums.

**Comment by cdujeu** [comment]
if it's a bug we'll reopen for sure

**Comment by Madko** [comment]
I can give you my ansible playbooks if you'd like to try to reproduce the segfault. btw how a segfault can't be a bug ? Interesting subject ;)

**Comment by cdujeu** [comment]
to answer your question : pydio is part of a broader system and believe me, many many issues can be linked to anything but pydio.

**Comment by Madko** [comment]
I can give you my ansible playbooks if you'd like to try to reproduce the segfault. btw how a segfault can't be a bug ? Interesting subject ;)

**Comment by Madko** [comment]
I understand, but look what is happening from a user perspective : 
- I tried to use the forum, which is online but not used anymore (why??)
- I tried to report on github, as for any serious project (no more luck)
- I tried on twitter, no response (not a big deal)
- I was sent from here to an other forum (mmm ok...)
- There it was more like "this is how you can do it without the part you want to use" (ok an abvious workaround)
- And at last here, I'm told that the bug is certainly not from pydio. 
- And that it has to be qualified first as a bug before opening an issue.

So If users can't open ticket here because it's not yet qualified as a bug, how do we qualified an issue as a bug ? I'm really willing to conform to your original process, because pydio seems such a good product, and it really deserves a community.

**Comment by cdujeu** [comment]
Hey madko
Sorry about all that, this forum stuff has been really broken lately. And thank you for your patience. 
Our basic process is explained all around in both the README and https://pydio.com/fr/community. The base was : please discuss in the forum first, and open a github issue once you are invited to do so. But indeed forum was broken (very very heavy spamming), so we changed to a new platform (as indicated clearly on the old forum), so we can start again the normal process.
So, again, once we have a clear way to reproduce the bug, we will open an issue with clear scenario, on which os to reproduce it etc. 
You will not be left aside ;-)

**Comment by cdujeu** [comment]
And finally : this "qualified bug" may seems obvious to you, but I can assure you that 90% of what [non-technical] people think as a bug are in fact simple configuration problems. Thus the distinction.

**Comment by Madko** [comment]
I've made PR #1403 to fix indexation launch from CLI. Still not sure if it fix the segfault yet.
