### ISSUE TITLE
Public links not working

### ISSUE THREAD

**Issue by unematt** [pydio/pydio-core#1398]
I can't get public links to work on my Pydio 7 install on Centos 7. I get the error 'Oups, cannot find this page' error. 

I've set Pulic Base URI to /pydio/public and the download URL to mydomain.info/pydio/public . I've cleared the cache files plugin*.ser in /var/cache/pydio . Rewrite is set to /pydio , Everything seems to work on the install except the public links.

**Comment by unematt** [comment]
When I look in the logs, I see a user created when a file is make public. Its some random chars is seems. Still results in cannot find page.

**Comment by cdujeu** [comment]
please use the forum
