### ISSUE TITLE
Pydio 8.0.1: Display/Layout of Shared Files in Firefox browser disrputs view

### ISSUE THREAD

**Issue by mhongslo** [pydio/pydio-core#1399]
I'm using Pydio 8.0.1 community edition and PPHP 5.6  I have setup a scenario where another user is sharing files with my user and when I view the Shared Files in Firefox browser (version 56.0.2 (64-bit) on a Windows 10 Pro system, the view doesn't properly show the file list.  The file names are hidden behind the left navigation panel.

![pydio-shared-files-view](https://user-images.githubusercontent.com/33552745/32667903-bd7a675a-c601-11e7-8c49-13881aeb9bdb.png)

**Comment by cdujeu** [comment]
hi we cannot reproduce this behavious, did you try with the very last version of FF (57)?

**Comment by mhongslo** [comment]
Firefox Version 57 seems to fix the problem.
