### ISSUE TITLE
Default displayMode in upload folder not implemented in Pydio v8

### ISSUE THREAD

**Issue by bjholties** [pydio/pydio-core#1402]
Dear all,

In the upload folder I need to set the default displayMode for all users to 'list', which was previously implemented in the pre-React version of Pydio. It would be great if this could be implemented and configurable in the manifest.xml (plugins/access.fs)?

I am adding this ticket based on this topic:
https://pydio.com/forum/f/topic/sort-folders-by-date-modified-for-all-users-and-repositories/#post-127044

Kind regards,

Berend

**Comment by cdujeu** [comment]
done in develop branch, will be in 8.2.0 (added default display and default sorting options in workspace editor).
