### ISSUE TITLE
preview in right panel stuck with "no compatible source" with 8.x

### ISSUE THREAD

**Issue by Nanomani** [pydio/pydio-core#1404]
1 - click on a file *.mov, preview in right panel display "no compatible source"
2 - click on a file doc, jpg or all other there is a preview, preview in right panel stuck with "no compatible source"
3 - workaround is to refresh with F5 (Pydio refresh don't works)

tested with ubuntu server 16.04 LTS or windows server and pydio 8.0.2

![2017-12-18_093553](https://user-images.githubusercontent.com/3939543/34097192-84283154-e3d8-11e7-8b45-69977a7bf835.jpg)

**Comment by spec1re** [comment]
Same here since latest update.

**Comment by OsmelTorres** [comment]
Same for me, also pydio 8.0.2.

**Comment by cdujeu** [comment]
Hi, 
1 - Are you sure it was really working with 8.0.1 and **this** format ? 
2 - What about mp4 ? 
-c

**Comment by spec1re** [comment]
Hello, yes it was working fine in 8.0.1, with mp4 and even with mov, when using Chrome. The only limit was files larger as 2 GB wouldn't play.

**Comment by cdujeu** [comment]
and now, is mp4 working? (it is for me)

**Comment by Nanomani** [comment]
nope for MP4, not for me.

**Comment by spec1re** [comment]
![image](https://user-images.githubusercontent.com/11883076/34148090-3e7233b2-e4a0-11e7-9029-3c59f6f72ef2.png)

No luck, running debian jessie here.

**Comment by Nanomani** [comment]
Firefox 57.0.2 issue :(
With chrome 63.0.3239.108 all is fine.

**Comment by spec1re** [comment]
Tried with FireFox 57.0.2 x64 and Chrome 63.0.3239.108 x64, none is working here.

**Comment by Nanomani** [comment]
Your are right @spec1re  after a clear cache this issue come back in Chrome O_o

**Comment by spec1re** [comment]
Okay, here my temp workaround:

1. delete /usr/share/pydio/plugins/editor.video
2. unpack pydio-plugin-editor.video_8.0.1-3_all.deb and copy editor.video to /usr/share/pydio/plugins
3. clear plugins cache

and et voilà its working again. :)

**Comment by Nanomani** [comment]
Yep roll back "plugin-editor.video" before 8.0.2 fix this issue for me too
thx @spec1re

**Comment by cdujeu** [comment]
@c12simple can you make a diff to see what we broke?

**Comment by OsmelTorres** [comment]
Yes, spec1re workaround worked for me. I Have Video Again. Thanks

**Comment by AlCan13** [comment]
I have installed pydio 8.0.2 from sources and same story. 
Linux srvr-2 4.9.0-4-amd64 #1 SMP Debian 4.9.65-3+deb9u1 (2017-12-23)
Firefox 56.0 x32

**Comment by ChuckDaniels87** [comment]
It seems this was fixed upstream: https://github.com/videojs/videojs-flash/pull/39

Is it possible to update this plugin before next Pydio release?

**Comment by corradiniste** [comment]
Are there any updates?

**Comment by morvans** [comment]
This behavior is probably the result of a major version change of Video.js (5.19.2 to 6.4.0).
The root cause is this dependency has no version requirement in package.json : 
`    "video.js": "*"`

**Comment by corradiniste** [comment]
I don'see any change :(

**Comment by c12simple** [comment]
Thanks all, fixed
