### ISSUE TITLE
HTTP auth breaks pydio

### ISSUE THREAD

**Issue by kethinov** [pydio/pydio-core#1406]
Same issue described here: https://pydio.com/forum/f/topic/401-from-react-fetch/

@cdujeu asked for a GitHub issue to be filed, so I'm filing one here:

Example use case: Deploy pydio (which depends on systemjs) to an environment which requires presenting PKI certs for all HTTP traffic, including JS fetch requests.

At present with the current version of systemjs, that use case is broken in Firefox and Safari.

I submitted a PR to systemjs here https://github.com/systemjs/systemjs/pull/1782

Once it is merged and released, the dependency in pydio will need to be upgraded.

**Comment by kethinov** [comment]
The systemjs guys are [saying](https://github.com/systemjs/systemjs/pull/1782#issuecomment-359763009) pydio should [set](https://github.com/systemjs/systemjs/blob/master/docs/config-api.md) `meta: { '*': { authorization: true } }` in your systemjs config to resolve this rather than accepting the PR that I sent them which alters systemjs itself to presents credentials for same origin fetch requests by default.

**Comment by c12simple** [comment]
Hi,
I add the meta as you mentioned.
https://github.com/pydio/pydio-core/commit/c24e8374831b7fb0fe55bbb56b329bef42780233
