### ISSUE TITLE
PHP 7.2 fatal error at installation

### ISSUE THREAD

**Issue by calvintam236** [pydio/pydio-core#1416]
I tried to run the installation with PHP 7.2.1, and I can't even get through the first step in the installation wizard.

```
count(): Parameter must be an array or an object that implements Countable
```

pydio-core: v8.0.2
apache
php 7.2.1

**Comment by CupCakeArmy** [comment]
Same problem here🖐

**Comment by cdujeu** [comment]
We’ll look into this but be patient, we are working like dogs on the next major release... stick to 7.1 in between

**Comment by CupCakeArmy** [comment]
I discovered some interesting stuff. Basically it works fine if php is installed locally. If I have a php container, a separate web/nginx container with the pydio files and one for the db, the problem occurs.

**Comment by nienic** [comment]
Is there a quick way to fix it? I can't change PHP version.

**Comment by cdujeu** [comment]
@c12simple can you provide the fix ?

**Comment by senthor** [comment]
Same issue. When upgrading Ubuntu to 18.04 LTS, PHP is upgraded to 7.2, breaking existing Pydio installations.

**Comment by cdujeu** [comment]
we're on it

**Comment by DrPine** [comment]
Was this closed because it was fixed or fix still in development?  If it was fixed, the issue persists with the latest PHP and Pydio 8.0.0 setup.

OS: `CentOS 7`
PHP: `7.3.4`
Nginx: `1.15.11`

**Comment by c12simple** [comment]
Hello,

I would like to clarify with you on version of Pydio that you have error. Do you have 8.0.0 ? We fix the problem with php 7.2 in 8.0.x or 8.2.x

**Comment by DrPine** [comment]
Thats what I was wondering, did I need to downgrade. I believe I have PHP 7.3.4 thats what I wrote, so I will try downgrading today.

**Comment by c12simple** [comment]
Hello,
Confirmed: Pydio 8.2.3 + centos 7 + php 7.3 + apache run properly without any issue.

**Comment by DrPine** [comment]
Apache comes preconfigured with PHP so maybe it's my Nginx setup.

Maybe I use Apache for this and Nginx for everything else hah

**Comment by PineSmokes** [comment]
Maybe I use apache for this and nginx for everything else rofl

**Comment by calvintam236** [comment]
I think Nginx should be supported for this application. It should not have problem on either Apache or Nginx.

**Comment by cdujeu** [comment]
Pydio 8 perfectly works with both, as long as PHP is correctly configured.
