### ISSUE TITLE
Metadata search for text fields is broken

### ISSUE THREAD

**Issue by achern** [pydio/pydio-core#1426]
As mentioned in the thread below, metadata fields of type short text or long text do not appear in the advanced search box, while other types do:

https://pydio.com/forum/f/topic/help-how-to-enable-tags-metadata-under-advanced-search/

This was on a fresh 8.2.0 install on Ubuntu Server 18.04 using the packages.

**Comment by cdujeu** [comment]
hi Achern, coming back on that one, I still cannot reproduce it. 
Did you
1 - Define metadata in the Text Metadata (e.g. "comment" => Short Text)
2 - List the fields names in the Lucene Indexer section (comment)

Charles

**Comment by achern** [comment]
I just figured out the problem after failing to reproduce the issue in a new workspace. I had an underscore in my field name, and removing it fixes the issue!
