### ISSUE TITLE
Share User Add Multiple Group 

### ISSUE THREAD

**Issue by vinc76** [pydio/pydio-core#1427]
Hello to the team
We are in Core version.
We use user shares.
We have created several groups that list users.
If we assign a first group and validate: no problem.
We add a second user group and we validate: The group then added takes the name of the first group added. The second group is not added.
We checked in the shares that the user did there is only one group and not both.

I do not speak English very well, my apologies, but if you can help us,
thank you,
Vincent
PS: ADDGROUPENOTVALIDE.JPEG: This is the capture before validation
ADDGROUPAFTERVALIDE.JPEG: result after saving
![addgroupaftervalide](https://user-images.githubusercontent.com/40198938/41281286-4ac2ddd6-6e31-11e8-9c8c-99e6e4e0bc53.JPG)
![addgroupnotvalide](https://user-images.githubusercontent.com/40198938/41281288-4ae4a2d6-6e31-11e8-9dab-9d2990c3ae46.JPG)

**Comment by cdujeu** [comment]
Hi, can you provide the exact version of Pydio? 
Thx

**Comment by vinc76** [comment]
Hi,
Sorry i forgot, we are in version 8.2.0 of MAY 22, 2018
Thx,

Vincent

**Comment by cdujeu** [comment]
hi again - just trying to reproduce that but I can't
Do you just use pydio "internal" users or do you use external directories connectors (like ldap ..) ?

**Comment by vinc76** [comment]
Hello,

we only use users and internal group at Pydio.
Here's a screenshot of groups / users:
![capture](https://user-images.githubusercontent.com/40198938/42159764-3281ebbc-7df5-11e8-964c-84b8074138a0.JPG)

**Comment by cdujeu** [comment]
So the EDI group ID is EDIWORKSPACE right?

**Comment by vinc76** [comment]
EDI is Label 
and 
EDIWORSPACE is ID Group
![capture](https://user-images.githubusercontent.com/40198938/42160007-01197bf2-7df6-11e8-9adc-bbf4827f84ee.JPG)

**Comment by cdujeu** [comment]
ok i'll try to reproduce with similar groups

**Comment by cdujeu** [comment]
ok now i can reproduce strange behaviors with sub groups - i'll keep you informed

**Comment by vinc76** [comment]
Thank's for your help

**Comment by cdujeu** [comment]
ok should be fixed by https://github.com/pydio/pydio-core/commit/2b80cddda914daad9134e17ea33f098994308cad

**Comment by vinc76** [comment]
I'll do a test tomorrow at the latest
Thank's a lot

**Comment by vinc76** [comment]
I just did the test,
I did not do a thorough test based on the users in the group.
But it seems that this is corrected.
Here is the result in image.
![capture](https://user-images.githubusercontent.com/40198938/42226819-36a8d066-7ee0-11e8-967e-c60d703c4393.JPG)
