### ISSUE TITLE
Audio Player not working properly on most browswers

### ISSUE THREAD

**Issue by plangham100** [pydio/pydio-core#1438]
I just migrated to pydio 8 on a new server with debian 9 and this same issue exists from the system we migrated from. with pydio 8 on debian 8.

The audio player doesn't work at all in some web browsers and works differently on different browsers and it doesn't work completely correctly in any browser.

In chrome for windows I get playback and sound but no ability to skip forward or skip to the next track or even change tracks.  When I close the chrome player window it keeps playing audio.

In Firefox clicking the player buttons does nothing and no playback occurs.  i can select tracks but cant hear them if they are in fact playing.

It is extremely buggy.

The older player at least played the audio and would let you jump ahead in playback and change tracks but the new player is really messed up.

I use pydio exclusively for musicians and they must be able to listen to their songs.

Im hoping this issue can be resolved.

PL

**Comment by cdujeu** [comment]
Hi, should be fixed in 8.2.2

**Comment by plangham100** [comment]
I will upgrade and check it out
