### ISSUE TITLE
I can't share any file to public users

### ISSUE THREAD

**Issue by corradiniste** [pydio/pydio-core#1452]
I'm on shared hosting.

Client : Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36
Crypto Extension Detected : OpenSSL
Command Line Available : Yes
DOM Enabled : Yes
Exif Enabled : Yes
GD Enabled : Yes
Upload Max Size : 2000M
Memory Limit : 1024M
Max execution time : 300
Safe Mode : 0
Safe Mode GID : 0
Xml parser enabled : 1
Server OS : Linux
Session Save Path : /home/athemovv/php_sessions
Session Save Path Writeable : Yes
PHP Version : 7.2.15
Locale : C
Directory Separator : /
PHP Opcode Cache extension loaded : Yes
PHP INTL extension loaded : Yes
PHP Output Buffer disabled : Yes
PHP File Uploads enabled : Yes
Magic quotes disabled : Yes
Upload Tmp Dir Writeable : Yes
PHP Upload Max Size : 2097152000
PHP Post Max Size : 2097152000
Users enabled : Yes
Guest enabled : No
Writeable Folders : [cache:true,
data:true]
Zlib Enabled : Yes

**Comment by cdujeu** [comment]
Hello, please use the forum instead. We create issues only for qualified bugs.
Thanks
