### ISSUE TITLE
Pydio installation error

### ISSUE THREAD

**Issue by BerkeAras** [pydio/pydio-core#1455]
Hello.

Im new to Pydio and I get a error at the installation. I've copied all files to my webserver, but I got this error:

`This XML file does not appear to have any style information associated with it. The document tree is shown below.
<tree>
<message type="ERROR">
Declaration of ftpAccessDriver::deldir($location) should be compatible with AbstractAccessDriver::deldir($location, $repoData)
</message>
</tree>`

**Comment by danut2006** [comment]
Hi, I have the same issue with the Pydio, did someone find how we can fix this?
Thank you!

**Comment by BerkeAras** [comment]
Just clear your cache, delete the pydio files on the Webserver and upload them again
