### ISSUE TITLE
Feature request: Publication of a file from a specific date and time

### ISSUE THREAD

**Issue by Ajtak** [pydio/pydio-core#216]
Hello. 
I miss the feature that I had to share a file, so you could set the date from when to when this file is to be shared. I would imagine it to be today I would share the file, and the dialogue would set that you want to share from tomorrow by one hour. The file would then go to download. And maybe I set that up to six hours. and after this time, you should go download the file again.

**Comment by cdujeu** [comment]
Won't implement for the moment, will over-complicate the UI for the user.
