### ISSUE TITLE
details view broken since pydio 5.0.4

### ISSUE THREAD

**Issue by dani** [pydio/pydio-core#330]
Since I've upgraded to pydio 5.0.4 (from Ajaxplorer 5.0.3), the details view looks broken: instead of having a correct icone for each file (either a directory icone, or a preview for image, pdf and office files) I get the rate stars displayed in quite a strange way, see screenshot (every element get this icone, it's not even possible to distinguish files and folders).

![pydio_detail_view](https://f.cloud.github.com/assets/526826/1359782/79c8acf4-37e6-11e3-9df2-b644cee51b36.png)

Other views are not affected (list and thumbs are ok).

BTW, not really related to this issue, but it looks like list and details should be the other way arround, actualy, the list view gives more details than details view

**Comment by cdujeu** [comment]
no news, reopen if necessary
