### ISSUE TITLE
Add support for mysqli_, deprecate mysql_

### ISSUE THREAD

**Issue by echampet** [pydio/pydio-core#345]
mysql_* is deprecated in php 5.5
http://php.net/manual/en/migration55.deprecated.php

we need to add support for mysqli_*  and deprecated in a way mysql_* / migrate user to mysqli_*

**Comment by cdujeu** [comment]
Added a check inside Dibi initiatilisation, mysql case is now switching to mysqli by default if the extension is loaded.
