### ISSUE TITLE
Zoho Editor Does not work properly on IE11

### ISSUE THREAD

**Issue by Cosmo-Kramer** [pydio/pydio-core#477]
Hello,
I’d like to report that Zoho Editor does not work properly using IE11 (Windows 8.1). If I click anywhere in the text, it does not produce a cursor, it simply highlights everything. Other functions seem to work properly.

Thank you for your time and hard work on PYDIO. It is a great product.

**Comment by cdujeu** [comment]
Now working for me with 6.5.1 and the new version of zoho, on Win 7 and Win 10. Can anyone test on Win 8.1 ? @Nanomani @Cosmo-Kramer ?
thx

**Comment by Nanomani** [comment]
Sorry all our PC are under Win 10.

**Comment by cdujeu** [comment]
Closing for now.
