### ISSUE TITLE
SpamAssasin MPART_ALT_DIFF_COUNT on share invitation emails

### ISSUE THREAD

**Issue by alozzy** [pydio/pydio-core#488]
Invitation emails in v5.2.2 are now being treated as spam by SpamAssasin, due to this rule:

https://wiki.apache.org/spamassassin/Rules/MPART_ALT_DIFF_COUNT

Excerpt from above:

"The mail contains the content in both HTML and plain text format, but their content is (very probably) different – the number of words is significantly different in the two versions. This suggests that the sender is not using a normal mail client, and is attempting to evade filtering by using a message which looks different to humans and mail filters."

It would be helpful to have an option to disable HTML format for invitations to avoid this problem

**Comment by cdujeu** [comment]
hi @alozzy did you dig that subject on your side or not at all..? Any PR?

**Comment by alozzy** [comment]
Hi @cdujeu

Nope, I haven't pursued this any further. I don't really have the skill set to figure this out.

Thanks

Alan

**Comment by cdujeu** [comment]
Since then, user can disable HTML format for emails.
