### ISSUE TITLE
No Preview of *.mp4 videos in Safari

### ISSUE THREAD

**Issue by bax-** [pydio/pydio-core#514]
The preview of video files doesn't work in Safari (7.0.2)

**Comment by cdujeu** [comment]
Sorry I still cannot reproduce that (even on demo). Re-open if necessary.

**Comment by bax-** [comment]
I keep getting this error also on a fresh install on another system.
Pydio 6.0.5 (my own and the demo version).
Safari 8.0.4 on my machine and on numerous (!) other ones.

Could it have to do something with the old video.js version?

**Comment by bax-** [comment]
As you investigated [here](https://pyd.io/f/topic/no-video-previews-in-safari/page/2/#post-90986) the issue seems to have to do with https (and spdy) connections on Safari.
