### ISSUE TITLE
VersionControl_Git is getting pretty old

### ISSUE THREAD

**Issue by jprjr** [pydio/pydio-core#536]
Hi there -

I've been working on my Pydio docker container based on Arch Linux, which uses the latest version of git (1.9.1)

I've managed to install VersionControl_Git - but I get a lot of errors after creating a workspace with meta.git.

I noticed that VersionControl_Git hasn't updated in ~3 years and works by calling `git` on the command line. I'm guessing that git's output has changed a bit and VersionControl/Git no longer works correctly.

I think a decent fix for this would be to switch to use libgit2 w/ the php bindings - https://github.com/libgit2/php-git - this would provide a native interface to git instead of calling and parsing `/usr/bin/git`

**Comment by figassis** [comment]
I don't see why we keep trying to implement git versioning on a document management system where the end user might be using large files. That will just create headaches. Pydio supports Amazon S3, and S3 implements versioning. How about moving in that direction?

**Comment by cdujeu** [comment]
Hi, I totally agree. Reason why we did not spend time updating this library yet. Pydio has always tried to use existing features of underlying storage / os and to not reinvent the wheel, thus using s3 versioning for s3 storage is clearly the way. But still we do support FS storage, so we have to provide an implementation for that, and git is still really acceptable as long as files are not too big. And idea for linux based FS was also to interact with LVM. 
-c

**Comment by rawtaz** [comment]
Or even better, ZFS.

Perhaps Mercurial for version control is an option? AFAIK it handles large files better than git.

11 jan 2016 kl. 10:22 skrev Charles du Jeu <notifications@github.com>:

**Comment by cdujeu** [comment]
not migrated yet, but switched to Composer instead of PEAR installation, which allows us to embed the lib directly. Closing for now.
