### ISSUE TITLE
Support LDAP schema where only groups know their own member

### ISSUE THREAD

**Issue by ygini** [pydio/pydio-core#580]
Apple Open Directory service use a LDAP schema where group members are managed on the group LDAP record, not on the user record.

To know if a user belong to a group, we must check groups, not users.

For example, if I check the record for the group "cn=LabA" I've multiple memberUid field, one per member. The field are filled with the user uid, not the full dn.

Nested groups are more difficult, they use a custom apple-group-nestedgroup field filled up with nested group GUID.

At this time, pydio don't support this kind of setup (or I didn't find the documentation), is it possible to update this part? At least for simple group management, not the nested.

**Comment by cdujeu** [comment]
fixed by @c12simple implementation of "fakeMemberOf".
