### ISSUE TITLE
Is underscore allowed in group names ?

### ISSUE THREAD

**Issue by PhilJung** [pydio/pydio-core#610]
I have tried creating a group id = POLE_RH, name = POLE_RH
It works
Then I created 2 users in this group.
I never been able to see these users in the MMI. Creating the users again raised an error 'duplicate user id'.  Had to patch group id and name in database to remove _ and I immediately recovered the 2 users in the MMI

**Comment by cdujeu** [comment]
FYI
https://github.com/dg/dibi/issues/159
