### ISSUE TITLE
Install failed with mysql and `utf8mb4`

### ISSUE THREAD

**Issue by Beanow** [pydio/pydio-core#642]
```
CREATE TABLE IF NOT EXISTS `ajxp_users` (
`login` varchar(255) NOT NULL,
`password` varchar(255) NOT NULL,
`groupPath` varchar(255) NULL,
PRIMARY KEY (`login`)
);
```

Fails because `ERROR 1071 (42000): Specified key was too long; max key length is 767 bytes`

More information on this in https://mathiasbynens.be/notes/mysql-utf8mb4#column-index-length

**Comment by cdujeu** [comment]
to be rechecked

**Comment by cdujeu** [comment]
we now specify utf8 on table creations so this issue should not be valid anymore.
