### ISSUE TITLE
Login button image

### ISSUE THREAD

**Issue by martinschaible** [pydio/pydio-core#661]
Login Screen:

The login button is rendered by a image stored in the orbit theme:

<input class="dialogButton dialogFocus" title="OK" src="plugins/gui.ajax/res/themes/orbit/images/actions/22/dialog_ok_apply.png" name="ok" height="22" type="image" width="22">

This could cause troubles with a CSS from a third party theme rendered by a seperate plugin.
Solutions:
- Move the image into a css class.
- Use a symbol from Font Awesome instead.

Thanks!

**Comment by cdujeu** [comment]
no more valid
