### ISSUE TITLE
Theme - > override.css

### ISSUE THREAD

**Issue by martinschaible** [pydio/pydio-core#663]
As we know, creating a theme based on the new theme orbit might be tricky. The plugin gui.ajax needs to be changed. The better way is to create a own plugin, which overwrites the css from the theme. This needs a bit programming skills, what can not  be expected from a designer.

My idea:
- Each of the four themes should support a css file called override.css.
- The file can be activated/deactivated in the plugin gui.ajax on per theme base.

Benefits:
- Minimal change of the plugin gui.ajax
- It's update-save
- Ready for designers without messing arround with code.

**Comment by cdujeu** [comment]
we'll have to rework theming more deeply. old themes removed in pydio7, now only orbit stays.
