### ISSUE TITLE
Login page: More space

### ISSUE THREAD

**Issue by martinschaible** [pydio/pydio-core#688]
The german translation needs a bit more space for the string "Remember me".

Could you please change the layout, that the "remember me" and "forgot password" are one underneath the other instead of in parallel? I think, it would better look anyway.

![zwischenablage01](https://cloud.githubusercontent.com/assets/3628499/4835532/6a69e69c-5fb8-11e4-9721-829696695c7e.png)

**Comment by cdujeu** [comment]
fixed in dev
