### ISSUE TITLE
Samba passwords sanitized

### ISSUE THREAD

**Issue by NHellFire** [pydio/pydio-core#695]
Samba passwords are being sanitized. My password contains a < and I'm unable to view that, I have to manually edit the database and correct the password.

**Comment by NHellFire** [comment]
When using environment with smbclient, it treats the whole thing as
username, so password won't be used.
Created a PR to fix the original issue.

**Comment by old9** [comment]
@NHellFire How do you manually update the database? I got similar problem that I set a password with special characters(`<` and `>`) during the start wizard, and now I have no way to login.

**Comment by cdujeu** [comment]
we have to tackle this issue and decide what to do

**Comment by c12simple** [comment]
Hi @NHellFire , @old9 
it's fixed: https://github.com/pydio/pydio-core/commit/4a64194c0b24c9dcb99a5528c31c26d09255b67c
