### ISSUE TITLE
Requirement to enter OTP bypassed with PydioSync and WebDAV

### ISSUE THREAD

**Issue by mikerhyner** [pydio/pydio-core#704]
Accounts with enabled OTP features can still be accessed without OTP (no need to enter yubikey/google auth code) using WebDAV or PydioSync. That imho jeopardizes the security benefit of OTPs, specially because PydioSync connection cannot be turned off afaik (as possible with WebDAV and not enabled by default).

For WebDAV, I know it's hard to solve because every DAV reqest needs to be
authenticated (and new OTP would need to be entered again on every access) because
there's nothing like a steady session (perhaps accepting successive requests from the same IP address within a certain time window without checking OTP password part after an initial successful
authentication including the OTP part could do the trick).

Tested with lastest testing release 5.3.4 (installed via Debian Repository).

**Comment by cdujeu** [comment]
manually disable sync & webdav.
