### ISSUE TITLE
Using a consistent response format for the CLI-Interface

### ISSUE THREAD

**Issue by tolgauen** [pydio/pydio-core#707]
This is just an enhancement request since I'm playing around a lot with the CLI-Interface.
Here are some examples to clarify what I mean. 

Suppose you want to add a workspace quota and you made a typo while you were typing in your password:
cmd.php -u= -p= -r=ajxp_conf -a=meta_source_add --repository_id= --DRIVER_OPTION_DEFAULT_QUOTA=25M --DRIVER_OPTION_CACHE_QUOTA=false --new_meta_source=meta.quota

This is what I get when I try to execute the action with the typo:

<?xml version="1.0" encoding="UTF-8"?>
<tree>
<logging_result value="-1"/>
</tree>

Thats fine by me. But that was pretty much the only error response which I got in XML (so far). Responses to other types of error were only returned as an exception message. Here is an example for that, this happened when I tried to delete a workspace quota with a typo in the repository ID:

PHP Fatal error:  Uncaught exception 'Exception' with message 'Invalid repository id! 574aea796812f6c3942' in /var/www/plugins/access.ajxp_conf/class.ajxp_confAccessDriver.php:1434
Stack trace:
#0 /var/www/core/classes/class.AJXP_Controller.php(478): ajxp_confAccessDriver->switchAction('meta_source_del...', Array, Array)
#1 /var/www/core/classes/class.AJXP_Controller.php(284): AJXP_Controller::applyCallback(Object(DOMXPath), Object(DOMElement), 'meta_source_del...', Array, Array)
#2 /var/www/cmd.php(197): AJXP_Controller::findActionAndApply('meta_source_del...', Array, Array)
#3 {main}
  thrown in /var/www/plugins/access.ajxp_conf/class.ajxp_confAccessDriver.php on line 1434
 
It would be great if you could consistently use XML as the response format, regardless if it is for an error or success response. This would allow a better response interpretation and accessibility for other applications using your CLI-Interface.

**Comment by cdujeu** [comment]
part of api v2
