### ISSUE TITLE
smbclient workspaces: Cannot create recycle folder

### ISSUE THREAD

**Issue by matsimon** [pydio/pydio-core#714]
Condition:
- Have an SMBclient workspace
- I have an AD/LDAP authentication
- User wants to open a workspace and gets a red bar popping up saying: Cannot create recycle folder. Pleasee check repository configuration or that your folder is writeable!

Disabling the recycle folder for that workspace doesn't change the error or fix the access. I've seen this when I had the time to try installing manually from git a test setup, but suspected that it was an error in permissions caused by myself and I reverted back to 5.3.3 deb package.

However I can now confirm with that this also applies to the DEB-packaged 5.3.4 and not only pre-5.3.4 code..

**Comment by matsimon** [comment]
Sorry for the long time - I'd have a test instance up and running again, contact me off-Github and I'll provide with credentials.

Trying to answer @c12simple 's questions:

> Can user map network driver on local machine ?

 By means that users can mount the drive on a Windows box? Yup, otherwise we'd have a pretty fire in the IT department ;-)

> Which attr of user you mapped to Pydio as their identity

 __sAMAccountname__

> What is access permission (NTFS) on this network driver

I'm not certan about your question - you might mean the network drive / SMB share itself?

Users in this simple use case have full access as the drive is calle TransferTeacher which is a temporary storage location for all teachers to exchange information between each other.
The actual admin account even has full access to the share - I can't really grant mor then full access.
>  I wrote 90% because of error when you use userPrincipalName to map to Pydio.

I've left the recycle blank, still the error shows up

Users are (at least here) are used to use their sAMAccountname, so that would be excluded.
It's now a test setup on Pydio 5.3.5 and still 100% reproducible error rate *sad*

**Comment by cdujeu** [comment]
@matsimon sent you an email, with @c12simple in cc. Did you actually test v6.0.2?

**Comment by cdujeu** [comment]
@koenn did you ever solve this issue? We could not reproduce that on matsimon server, it was a config problem.

**Comment by c12simple** [comment]
On matsimon server:
1. Test with ldap user (admin user can't access to smb server)
2. In authentication setting, select "Store credential in SESSION"
(save username/password in encrypted session variable)
3. In workspace config, select "use Credential session" (call
username/password in session for each smbclient command to access to
smb server)
4. You can test with account tcuong-pydio and I set only access to
TransferAlle workspace

**Comment by koenn** [comment]
> @koenn did you ever solve this issue?
 I worked around it by disabling recycle bin on the affected workspaces, so it's not an acute problem for me anymore. 
Possibly I too missed one of the settings about 'store credentials in session', or I lost them during the upgrade from 5.x to 6.

**Comment by matsimon** [comment]
Late update: This issue can be closed by now, I've not encountered anymore in a fresh install anymore. Thanks for your help :-)
