### ISSUE TITLE
plugin properties not applied using roles

### ISSUE THREAD

**Issue by mikerhyner** [pydio/pydio-core#773]
Tested Procedure:
- Login as super admin (user "admin")
- Go to Settings -> Roles
- Create a new role, named e.g. "OTP_YK"
- Edit the newly created role
- Add the following plugin parameters to the role:
  * plugin identificator: "authfront.otp", parametername "yubikey1" for workspace "All Workspaces"
  * plugin identificator: "authfront.otp", parametername "yubikey2" for workspace "All Workspaces"
  * push button "add paramters"
- save the role
- Under User and Groups -> Edit a certain user
- Assign the role "OTP_YK" created before to the user
- Save the user
- Go to parameters section

Experienced result:
- On the lower area of the screen, there are no assigned plugin paramters visible

Expected result:
- On the lower area of the screen, below an "All Workspaces" section under "authfront.otp", the paramters "Yubikey1" and "Yubikey2" assigned to the role before shoud appear (as it does within role properties and for other plugin parameters set like e.g. meta.quota also assigned to a role).

Also made some screenshots:
- 1st screenshot shows the plugin parameters added to the role:
![bildschirmfoto vom 2014-12-07 16 01 48](https://cloud.githubusercontent.com/assets/8648903/5331416/11be84b2-7e2b-11e4-961f-bacfedcfcf3e.png)
- 2nd screenshot shows the user info properties with role assigned:
![bildschirmfoto vom 2014-12-07 16 02 21](https://cloud.githubusercontent.com/assets/8648903/5331418/11c252d6-7e2b-11e4-9fee-fc7127114e66.png)
- 3rd screenshot shows the plugin parameters of the user with role assigned:
![bildschirmfoto vom 2014-12-07 16 02 38](https://cloud.githubusercontent.com/assets/8648903/5331417/11c04626-7e2b-11e4-82fd-b31a68753c55.png)

**Comment by cdujeu** [comment]
Ok got it: @mikerhyner you did not put any actual "values" for the parameters, that's why they are not appearing. If you set values in the role params (like yubikey: xxxxx , secret : yyyyy), they do appear in the user params.

**Comment by mikerhyner** [comment]
Thanks for your investigation. So it's what I've already noticed/assumed that roles seem to be the wrong means for that, because users should be able to set their own Yubikey or Google Secrets (thus left empty). Have achieved that in the meantime by modifying some manifest.xml file, hence those parameters will appear in every user dashboard.
