### ISSUE TITLE
display mode is never memorize

### ISSUE THREAD

**Issue by Ellega** [pydio/pydio-core#777]
if you switch between your workspace the display mode is always "list standard"
the last display mode is never reused
set "skip interface preferences" to "NO" change nothing

**Comment by Ellega** [comment]
Ok this bug is fixed. Thx. :-)
But this fix introduce another one bug.
All Meta property are displayed.
It is not possible to hide one.

![2015-01-22_104351](https://cloud.githubusercontent.com/assets/3939543/5853500/9ea5a9b0-a224-11e4-9bb9-1aedacb716c7.jpg)

**Comment by cdujeu** [comment]
There were some changes here as well indeed. But i tested that, it was working. Did you make sure to properly clear all caches (server-side & browser-side)?

**Comment by Ellega** [comment]
Yep. I'm very sure. 
I always do that before to pollute you with a new issue. :-)
Tested with a new clean install and with an install updated.
Always the same. A windows OS specific bug ? ...
I'll try to understand what's wrong

**Comment by cdujeu** [comment]
np, reopened :-)
There were a couple of properties that were saved directly to the "root" of the user preferences, whereas now they should be saved on a per-repository / per-widget basis. But maybe I messed up something.
-c

**Comment by cdujeu** [comment]
ok reproduced :-)

**Comment by cdujeu** [comment]
;-)
