### ISSUE TITLE
Shared file via a public link doesn't work

### ISSUE THREAD

**Issue by pwldp** [pydio/pydio-core#797]
Hi!

I generate a public link and when try open it in a browser window I got an error:
```The requested URL /pydio/data/public/1450b9.php was not found on this server.```
In apache logs I have an error:
```script '/usr/share/pydio/data/public/1450b9.php' not found or unable to stat```.

Pydio ver. 6.0.2.

**Comment by c12simple** [comment]
Hi,
Did you enable rewrite module?

**Comment by pwldp** [comment]
Rewrite module is disabled.
Should be enabled?

**Comment by cdujeu** [comment]
@pwldp please don't use Github for asking questions, use the forum instead, thank you. https://pyd.io/f/
