### ISSUE TITLE
Files with .ppt extension display as "My Account"

### ISSUE THREAD

**Issue by wsv-accidis** [pydio/pydio-core#803]
I uploaded a file with the extension .ppt (Microsoft Powerpoint) and while downloading works fine, the file type is displayed as "My Account". Probably a small cosmetic fix. If anyone can point me to the right file to update I will do it myself.

![image](https://cloud.githubusercontent.com/assets/10297778/5720915/284c5fb6-9b2b-11e4-951a-325c5c942d9d.png)

**Comment by cdujeu** [comment]
hi, could you eventually attach a file that creates the problem? I cannot reproduce this on my side...

**Comment by Ellega** [comment]
I have this little bug with all file ppt

file ppt to test: 

https://www.dropbox.com/s/0iuj0mcd5w8ea33/Pr%C3%A9sentation%20de%20test.ppt?dl=0
.

**Comment by wsv-accidis** [comment]
Same here - it happens with any PPT file I upload, at least all the ones I've tried.

I am thinking it may have to do with configuration. If you can point me at the point in the code where the lookup is made, I can do some debugging myself.

**Comment by Ellega** [comment]
@cdujeu, you must reproduce this easily  ;-)
