### ISSUE TITLE
wget and curl not working with direct file link

### ISSUE THREAD

**Issue by RickBianchi** [pydio/pydio-core#804]
Cannot download direct file link on the headless sever with wget or curl, both only pull down the php file, and not the file I was actually trying to share.

For example:
wget http://pydio.myserver.com/pydio/data/public/1150d1.php?dl=true&file=%2F1aa3556cbf%2Fdd.txt

No txt file, just php.

https://pyd.io/f/topic/wget-shared-file-link/#post-86916

**Comment by cdujeu** [comment]
arf arf, tested and I was doing the same as you :-)
You have to use quotes otherwise the shell is cutting after &
Try wget "http://pydio.myserver.com/pydio/data/public/1150d1.php?dl=true&file=%2F1aa3556cbf%2Fdd.txt"

**Comment by RickBianchi** [comment]
Nice one.

That gets the job done, works in curl as well. Both botch up the filename, it would be nice if it preserved it.

**Comment by vpicavet** [comment]
@cdujeu Is this possible with recent pydio ? I can't find a way to get your URL scheme working for direct download ?

**Comment by cdujeu** [comment]
Hi now you can directly use the following scheme 
http://pydio.myserver.com/pydio/data/public/1150d1/dl/dd.txt

**Comment by vpicavet** [comment]
I only get 404 error with Pydio 6.4.2, is it in more recent versions ?

Opening this kind of URL : http://pydio.myserver.com/pydio/data/public/1150d1 gives me a web page with a big download button

If I copy the origin URL from the downloaded file, it gives me : https://pydio.myserver.com/pydio/index_shared.php?secure_token=8WjXfoobaaaaaaarrrrrw&minisite_session=5eea33&

But the http://pydio.myserver.com/pydio/data/public/1150d1/dl/dd.txt URL returns 404. 

Any hint ?

( real urls redacted )

**Comment by vpicavet** [comment]
I only get 404 error with Pydio 6.4.2, is it in more recent versions ?

Opening this kind of URL : http://pydio.myserver.com/pydio/data/public/1150d1 gives me a web page with a big download button

If I copy the origin URL from the downloaded file, it gives me : https://pydio.myserver.com/pydio/index_shared.php?secure_token=8WjXfoobaaaaaaarrrrrw&minisite_session=5eea33&

But the http://pydio.myserver.com/pydio/data/public/1150d1/dl/dd.txt URL returns 404. 

Any hint ?

( real urls redacted )

**Comment by cdujeu** [comment]
Ha yes sorry I thought you were asking for v7. 
The URL's indicated at the beginning of this thread should then work for v6.X

**Comment by GiancarloF** [comment]
is it possible to get the direct download link from rest API in 6.x ? or at least the html embed code would be fine
