### ISSUE TITLE
No login screen / button when Guest Browsing is active

### ISSUE THREAD

**Issue by joachimcarrein** [pydio/pydio-core#808]
I have Pydio since it was ajaxplorer.
It has always been active with 1 workspace accessible through guest browsing.

Now, after upgrading to v6, guest browsing still works, but there is no button or other mean to login properly.

Currently I have a bookmark to fireAction("login") which does the trick, but it would be nice to have a decent solution.

**Comment by cdujeu** [comment]
should be fixed in code
