### ISSUE TITLE
Pydio 6.0.2, webgui, php transfer from tmp to destination after finished upload very slow

### ISSUE THREAD

**Issue by zette** [pydio/pydio-core#809]
I've installed Pydio 6.0.2 on fresh debian 7.8 from official repositories.
I've vhanged max upload file size to allow DVD ISO images uploads. Copy operation with webgui works fine and transfer is about 25MB/second on LAN.
After upload indicator reaches 100%, file is very slowly growing in destination and it takes few hours to finish for 4GB file.
I've found that during transfer php stores uploaded files in defined tmp directory, and only after that it copies file to defined destination. I've monitored this copy operation from OS level, and the transfer is extremly slow, measured in KB/s...
Both tmp and destination are located on same dedicated RAID, and local transfer (on same file) from tmp to destination tested on debian level gives results over 50MB/s.
Pydio 6.0.2
PHP: 5.4.36

**Comment by c12simple** [comment]
Hi,
What's limit_memory on php.ini?

**Comment by zette** [comment]
memory_limit is set to 512M
