### ISSUE TITLE
Pydio 6.0.2, WebDAV upload from WIN7 fails with "0x80070057: The parameter is incorrect"

### ISSUE THREAD

**Issue by zette** [pydio/pydio-core#810]
Pydio 6.0.2 installed from repositories on clean debian 7.8 with WebDAV shares enabled and working fine. PHP is configured to handle uploads of DVD ISO files (16G upload limit).
When using Win7 WebDAV shares to upload ~4GB file to server, when the transfer is finished I'm getting copy error message "Error 0x80070057: The parameter is incorrect" on Windows side. 
Copying of smaller files (tested up to 500MB) works fine, but slow finalization reported in #809.

In tmp directory I've found file: failedAJXP.log containing
```
a:0:{}
```
No errors in apache error log.

**Comment by c12simple** [comment]
please use Forum for this question
