### ISSUE TITLE
Can't download file in guest access when PowerFS active 

### ISSUE THREAD

**Issue by butaman** [pydio/pydio-core#822]
After I upgraded Pydio 5.x to 6.0.2, I can't download file by context menu in guest access.

Guest account has "Read" permission for the workspace, and file preview works correctly. However I get blank page when I do "Download" in context menu. There is no log output for this problem in apache, php5-fpm, and pydio. 

Here is link for the workspace: https://file.opap.jp/ws-kosys-ep02/
When you click download of "LICENSE.txt", you will get 0 byte blank page.

Pydio version 6.0.2 (I  patched https://github.com/pydio/pydio-core/commit/deeb0588982d55d1c87d10538f35e761eb8add11 manually )
Ubuntu 14.04.1 LTS (64bit)
Apache + php5-fpm

**Comment by cdujeu** [comment]
Hi @butaman 
This is probably a config issue, please stick to the forum. We use github only once the bug are really 100% qualified.
Thank you so much
-c
