### ISSUE TITLE
direct download links not working

### ISSUE THREAD

**Issue by bax-** [pydio/pydio-core#825]
Hi!

I’m using nginx and the nginx config from https://pyd.io/nginx/

The “direct download link” button on my download page creates files with the following name:
'XXX.com/share/347272?dl=true&file=GENERICFILENAME'
All the requests to /share/ are redirected to /data/public/, that works.
But the link just brings me back to the download page, no direct download is happening.
What works is the following (adding the share.php and replacing the first “?” with “&”):
'XXX.com/share/share.php?hash=347272&dl=true&file=GENERICFILENAME'

Then again this doesn’t work (replacing the first “?” with “&”):
'XXX.com/share/347272&dl=true&file=GENERICFILENAME'

I don’t know if there is something missing in the NGINX configuration (I couldn’t yet guess what it is, I also didn’t find anything specific in the .htaccess) or if there is something wrong with the link creation…

also see https://pyd.io/f/topic/direct-download-link-not-working/

**Comment by cdujeu** [comment]
please stick to the forum unless you are explicitely invited to create a bug, thx!
