### ISSUE TITLE
Message box with Powerfs don't work fine

### ISSUE THREAD

**Issue by Ellega** [pydio/pydio-core#835]
Compress files with PowerFS makes the job:
- archive.zip is created
- the current folder is updated

But the message box on bottom of page seems do not work correctly

In normal use we must have for 4 files selected to compress these message : 
 1 - Creating archive, please wait (0%) 
 2 - Creating archive, please wait (25%) 
 3 - Creating archive, please wait (50%) 
 4 - Creating archive, please wait (75%)
 5 - Creating archive, please wait (100%) 
 6 - Reload current folder

Actually there is only the first message that appear when the job is finish (tested with big files).
 - Creating archive, please wait (0%)

there is a little difference with "download all" from minite. there is 2 messages
 - Creating archive, please wait (0%) 
 - Archive download should start automatically

**Comment by cdujeu** [comment]
windows I guess? Working for me on *nix systems...

**Comment by Ellega** [comment]
Sorry, I can't tested on *nix systems.
Ok I will try to invetigate again on my side. But not so easy ...

Is it possible for you to ask someone to make a little test on IIS just for confirm or not this specific Bug on Windows OS ? Thx

**Comment by cdujeu** [comment]
i can verify, will try to fix it

**Comment by cdujeu** [comment]
Hi Nicolas 
I had the same problem on IIS, but the Archive file was not created at all. 
I saw that the command line "bat" script was successfully created in the tmp folder (make sure to set your own pydio tmp folder in the main options), but not triggered. When I manually called the script via command line, the operation was then finished successfully in the GUI (create archive and trigger archive download).
The following patch did make it work, plus setting the correct permissions in the tmp folder to make sure the .bat script could be successfully deleted.
Can you see if it makes any difference for you?
```
Index: plugins/action.powerfs/class.PowerFSController.php
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- plugins/action.powerfs/class.PowerFSController.php	(revision 860473e737ce175ad6b3981a8e091166b38b785f)
+++ plugins/action.powerfs/class.PowerFSController.php	(revision )
@@ -99,7 +99,7 @@
 
             case "postcompress_download":
 
-                $archive = AJXP_Utils::getAjxpTmpDir()."/".$httpVars["ope_id"]."_".$httpVars["archive_name"];
+                $archive = AJXP_Utils::getAjxpTmpDir().DIRECTORY_SEPARATOR.$httpVars["ope_id"]."_".$httpVars["archive_name"];
                 $fsDriver = AJXP_PluginsService::getInstance()->getUniqueActivePluginForType("access");
                 if (is_file($archive)) {
                     register_shutdown_function("unlink", $archive);
@@ -163,7 +163,7 @@
                 $cmdSeparator = ((PHP_OS == "WIN32" || PHP_OS == "WINNT" || PHP_OS == "Windows")? "&" : ";");
                 //$archiveName = SystemTextEncoding::fromUTF8($httpVars["archive_name"]);
                 if (!$compressLocally) {
-                    $archiveName = AJXP_Utils::getAjxpTmpDir()."/".$httpVars["ope_id"]."_".$archiveName;
+                    $archiveName = AJXP_Utils::getAjxpTmpDir().DIRECTORY_SEPARATOR.$httpVars["ope_id"]."_".$archiveName;
                 }
                 chdir($rootDir);
                 $cmd = $this->getFilteredOption("ZIP_PATH")." -r ".escapeshellarg($archiveName)." ".implode(" ", $args);
Index: core/classes/class.AJXP_Controller.php
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- core/classes/class.AJXP_Controller.php	(revision 860473e737ce175ad6b3981a8e091166b38b785f)
+++ core/classes/class.AJXP_Controller.php	(revision )
@@ -377,7 +377,17 @@
                   $cmd .= "\n DEL ".chr(34).$tmpBat.chr(34);
                   AJXP_Logger::debug("Writing file $cmd to $tmpBat");
                   file_put_contents($tmpBat, $cmd);
-                  pclose(popen('start /b "CLI" "'.$tmpBat.'"', 'r'));
+                  //pclose(popen('start /b "CLI" "'.$tmpBat.'"', 'r'));
+                  $proc = popen('start /b "CLI" "'.$tmpBat.'"', "r");
+                  while (!feof($proc)) {
+                      $results = fgets($proc, 256);
+                      if(!$results || strlen($results) == 0) {
+                          break;
+                      }
+                      AJXP_Logger::debug("Proc output: ".$results);
+                  }
+                  pclose($proc);
+
               }
         } else {
             $process = new UnixProcess($cmd, (AJXP_SERVER_DEBUG?$logFile:null));

```

**Comment by Ellega** [comment]
Hi Charles,

I have set my own pydio tmp folder in the main options

1 - Without patch:

 a - From Workspace

"compress" files with accent in file name               => Good
"compress" files with accent in path                       => Good
"download" files with accent  in file name               => Good
"download" files with accent in path                        => Failed !!!! (Cannot find archive.zip)
"download" folder with accent in path                      => Good

 b - From Minisite

"download selected" files with accent  in file name     => Good
"download all" files with accent  in file name               => Good
"download seleted" files with accent in path               => Good
"download all" files with accent in path                       => Good

2 - With your patch:

Conclusion : 
All result are the same than without patch
Patch makes no difference for me
The case "download files with accent in path"  is another little bug I think.

**Comment by cdujeu** [comment]
So if you say "Good" you mean that the archive is correctly built and download is correctly triggered??? In that case we can close this bug. If the archive is not huge, it's normal that you don't see 20%, 40%, etc... it's just polling the server for status, you should see progress only if the zip operation is longer than the actual polling time.
-c
