### ISSUE TITLE
An invalid entry crontab in parameter "schedule" broke Pydio 

### ISSUE THREAD

**Issue by Ellega** [pydio/pydio-core#840]
When you add a new task in setting "scheduler" you must add a valid crontab entry in parameter "schedule" otherwise Pydio is broken.

Actually we can save all value in parameter "schedule" without check. 
If value "schedule" is invalid, Pydio can't reload task list and Pydio is broken.

After you must manually edit the file "calendar.json" and restart Apache.

I have found a code which does such validation
Perhaps this can help you : 
http://stackoverflow.com/questions/235504/validating-crontab-entries-w-php

**Comment by c12simple** [comment]
Hello,
please test this commit
https://github.com/pydio/pydio-core/commit/00690032916faf6f7197c7b27b515bd0e2f223d7

**Comment by Ellega** [comment]
Hi @c12simple,
this bug is fixed.
Thx :-)
