### ISSUE TITLE
API not working on IIS when installed to root folder

### ISSUE THREAD

**Issue by jacobludriks** [pydio/pydio-core#842]
As per https://pyd.io/f/topic/first-letter-getting-stripped-from-api-url-iis/

The issue only occurs if Pydio is installed in the root of IIS (ie. c:\inetpub\wwwroot). I’ve debugged rest.php and this is what I’ve gotten:

URL is http://pydio.domain.com/api/default/changes/0

`$uri = $_SERVER["REQUEST_URI"];`

This returns “/api/default/changes/0″

`$scriptUri = ltrim(dirname($_SERVER["SCRIPT_NAME"]),'/')."/api/";`

This returns “\/api/”

`$uri = substr($uri, strlen($scriptUri));`

This returns “efault/changes/0″

`$uri = explode("/", trim($uri, "/"));`

This returns an array of three items – “efault”, “changes”, “0”

`$repoID = array_shift($uri);`

This returns “efault”

`$action = array_shift($uri);`

This returns “changes”

`$path = "/".implode("/", $uri);`

This returns “/0″

I suspect the issue is with `$scriptUri = ltrim(dirname($_SERVER["SCRIPT_NAME"]),'/')."/api/";`. The function `dirname($_SERVER["SCRIPT_NAME"])` is returning “\” when it should be returning “/”. This appears to be Windows-specific as per http://php.net/manual/en/function.dirname.php

**Comment by jacobludriks** [comment]
Also my PHP coding skills aren't as good as they used to be, so I don't feel confident to submit a pull request. Sorry!

**Comment by cdujeu** [comment]
Jacob
Can you try to replace the dirname() function by AJXP_Utils::safeDirname() ? It should fix the issue I think
charles

**Comment by jacobludriks** [comment]
That works great, thanks Charles. I'm not too sure how to implement a pull request so I'll leave it to you.

**Comment by cdujeu** [comment]
Thx for pointing that out. I'll M commit the change.
