### ISSUE TITLE
Check for free space before compressing directory for download

### ISSUE THREAD

**Issue by vineoak** [pydio/pydio-core#844]
I have a small suggestion regarding the feature of downloading folders. I checked and did not find this on the list of suggestions. When a user wants to download a folder from a workspace then it is compressed and offered for download. This is very convenient. However if a user presses the download link on top of a large directory structure containing considerable amount of data then this could result in no free space on a server.

My suggestion would be to check for available space before creating the compressed file. This is just an idea.

Got the idea when working on Pydio 6.0.3 on CentOS 7 setup

**Comment by cdujeu** [comment]
Please post in the forum until it's a fully qualified bug or feature request, thx
