### ISSUE TITLE
Sharing a single file break Pydio if accent in Path

### ISSUE THREAD

**Issue by Ellega** [pydio/pydio-core#847]
Sharing a single file breaks Pydio if accent in path (in file name or in folder name)

Pydio stays with a public link empty.
It is not possible to close the windows. 
We must refresh the navigator.

![2015-03-02_210727](https://cloud.githubusercontent.com/assets/3939543/6449366/9483d0d6-c120-11e4-9d70-9777f9343e76.jpg)

After It seems possible to editing the sharing but the public link stays empty.

**Comment by Ellega** [comment]
1 - sharing "test/été.jpg" => Public link is empty 
 2 - rename "test/été.jpg" to "test/ete.jpg"  => Public link is displayed when editing
 3 - rename "test/ete.jpg" to "test/été.jpg" => public link works fine 

All of this to say that this bug is limited to the display process. The sharing works well.

**Comment by cdujeu** [comment]
Can you verify the fix?

**Comment by Ellega** [comment]
As always this works perfectly when you fix a bug. 
Thx :-)
