### ISSUE TITLE
FTP login screen disappeared after upgrade

### ISSUE THREAD

**Issue by tborgans** [pydio/pydio-core#849]
Hi,

I am using a patched version of auth.ftp . In the global config I have still selected auth.ftp and "ftp login screen" is set to yes under "main instance" but after upgrade to 6.0.4 my FTP login screen disappeared. Instead of this login screen the normal login screen on the left side is visible.

I have cleared the cache and set this option again but nothing changes.

I am missing something?

thomas

**Comment by cdujeu** [comment]
Please post in the forum until it's a fully qualified bug, thx
