### ISSUE TITLE
The display window is too small when editing pdf with PdfJS on Minisite

### ISSUE THREAD

**Issue by Ellega** [pydio/pydio-core#857]
tested with Firefox 36, IE II, chrome 41

![2015-03-12_114628](https://cloud.githubusercontent.com/assets/3939543/6616533/24100ef0-c8af-11e4-9fa3-168b65e688d7.jpg)

tested with safari 5 (Windows OS)

![2015-03-12_114653](https://cloud.githubusercontent.com/assets/3939543/6616535/2c3a1fe4-c8af-11e4-9f34-6ec88d7326ff.jpg)

In normal use with others file type

![2015-03-12_120006](https://cloud.githubusercontent.com/assets/3939543/6616617/138a365e-c8b0-11e4-986a-a4a4a456a645.jpg)

![2015-03-12_120030](https://cloud.githubusercontent.com/assets/3939543/6616628/2c772c9e-c8b0-11e4-805b-1dccad9a9194.jpg)

**Comment by cdujeu** [comment]
ha ha indeed :-)
Can you try to replace line 18 of editorjs/manifest.xml with
```		<div id="pdf_box"  box_width="90%" box_height="90%" class="editor_container pdfjs_viewer"><iframe></iframe></div>
```
(and clear the plugins cache of course)

**Comment by Ellega** [comment]
![2015-03-12_122737](https://cloud.githubusercontent.com/assets/3939543/6616913/759e8504-c8b3-11e4-952e-5d6109a1cba7.jpg)

**Comment by cdujeu** [comment]
Fix: e2987e487a82c792eace18827c2de35683c24b02

**Comment by cdujeu** [comment]
i let you close

**Comment by Ellega** [comment]
All is fine now. Thx.
