### ISSUE TITLE
Password reset dialogue not appearing when accessing pw-reset link

### ISSUE THREAD

**Issue by mikerhyner** [pydio/pydio-core#863]
When trying to reset a user password, I only get the usual login screen, despite the URL witin the password reset link indicates the pw reset URI "/pydio/user/reset-password/<reset_key>"

I assume the issue appears when pydio is accessed like "/pydio/", instead of root ("/"). I've already set the  "Application Core" -> "Main Options" / "SERVER-URL" parameter to "<fqdn>/pydio", so it's at least possible to reach an existing URL. I've seen that within plugins/gui.user/class.UserGuiController.php, the requested user_access_point function is extracted out of the URI. Unfortunately, when pydio isn't installed/accessed directly beneath the document root, the $uri array will not be stripped off enough to reach the part to designate the requested function later. So I propose to shift on the URI like this:
 		while ($shiftresult != "user" ) {
                   $shiftresult = array_shift($uri);
 		}
instead of only:
                 array_shift($uri);
With this small patch, an arbitrary long leading URI path should be handled correctly (but perhaps you've better ideas to handle this...) and the page for setting the new password will then appear.

After that, a small problem remains: When setting a new password, a red error message appers, even the change seemed to be successful (see attached screenshot).
Within apache error log, this message appears:
PHP Fatal error:  Call to a member function getId() on a non-object in /usr/share/pydio/plugins/authfront.keystore/class.KeystoreAuthFrontend.php on line 82, referer: https://login.teamwulche.ch/pydio/user/reset-password/
![bildschirmfoto vom 2015-03-16 13 16 27](https://cloud.githubusercontent.com/assets/8648903/6665867/ed6825ee-cbde-11e4-9cb6-3f5675f5669c.png)
More strange is, when trying to use an old pw reset link, then a green confirmation message appears, but the password wasn't changed (because link seems to be expired/invalidated by the lastmost request). That's quite confusing for users...

**Comment by mikerhyner** [comment]
it seems when setting Authentication Frontends -> API Keystore -> PROTOCOL TYPE to "REST Only", the red error message won't appear and instead the green coloured confirmation message appears. So far, this should be solved. But there should be some hint when the password change didn't succeed (wrong/old Link, mistyped user, etc.) so one knows what's really happened...

**Comment by cdujeu** [comment]
I'll look into that. The issue is that if this is set to REST Only, the "Api Key" management panel in the users account will not appear. Not really blocking though :-)
