### ISSUE TITLE
Pydio Etherpad plugins : issue on pad naming

### ISSUE THREAD

**Issue by HubertChomette** [pydio/pydio-core#865]
Hi there,
Suppose you have a directory DIR which contains a file TEST.TXT.
If you open this file using collaborative tools (ie etherpad), it open $SESSION-DIR-TEST-TXT
Now, If I share this directory to other people (as a workspace), they can open it using etherpad but the pad name will be $SESSION-TEST-TXT
They can't work together.

**Comment by cdujeu** [comment]
Collaborating across shared workspaces will be probably quite complicated....

**Comment by HubertChomette** [comment]
maybe just remove the DIR on pad name?
But there will be a collision if someone open two files with same name on different directory.
