### ISSUE TITLE
Pydio Etherpad plugins : issue with CURL

### ISSUE THREAD

**Issue by HubertChomette** [pydio/pydio-core#868]
Hi there,

I disabled some plugins unused (dropbox, or sftp). Since the modification, I got an issue with the curl method on file etherpad-lite-client.php.
It doesn't success even if php-curl is installed.
The only solution found was to force the plain php method.

protected function call($function, array $arguments = array(), $method = 'GET')
  {
    $arguments['apikey'] = $this->apiKey;
    $arguments = http_build_query($arguments, '', '&');
    $url = $this->baseUrl."/".self::API_VERSION."/".$function;
    if ($method !== 'POST') {
      $url .=  "?".$arguments;
    }
    // use curl of it's available
    if (function_exists('curl_init')) {
      $c = curl_init($url);
      curl_setopt($c, CURLOPT_RETURNTRANSFER, true);
      curl_setopt($c, CURLOPT_TIMEOUT, 20);
      if ($method === 'POST') {
        curl_setopt($c, CURLOPT_POST, true);
        curl_setopt($c, CURLOPT_POSTFIELDS, $arguments);
      }
      $result = curl_exec($c);
      curl_close($c);
    // fallback to plain php
    } else {
      $params = array('http' => array('method' => $method, 'ignore_errors' => true, 'header' => 'Content-Type:application/x-www-form-urlencoded'));
      if ($method === 'POST') {
        $params['http']['content'] = $arguments;
      }
      $context = stream_context_create($params);
      $fp = fopen($url, 'rb', false, $context);
      $result = $fp ? stream_get_contents($fp) : null;
    }

    if (!$result) {
      throw new UnexpectedValueException("Empty or No Response from the server");
    }

**Comment by cdujeu** [comment]
That MUST be something else you did on your server. There is absolutely no reason the enable state of such pluings should have any effect on curl usage. Or can you verify that it works again if you reenable them?? It would be very strange (just tried to disable dropbox & ftp, no special issue).
-c

**Comment by HubertChomette** [comment]
I think that I have made other change on plugins (dropbox, ftp and others ...can't remember).
no change, as far as I know, on server.

**Comment by cdujeu** [comment]
I close that as it's definitely not a pydio issue

**Comment by HubertChomette** [comment]
Ok I found the issue.
Curl seem's to dislike our ssl certificat. Adding option to ignore it solve the issue.

// use curl of it's available
    if (function_exists('curl_init')) {
      $c = curl_init($url);
      curl_setopt($c, CURLOPT_RETURNTRANSFER, true);
      curl_setopt($c, CURLOPT_TIMEOUT, 20);
      curl_setopt($c, CURLOPT_SSL_VERIFYPEER, false);
      if ($method === 'POST') {
        curl_setopt($c, CURLOPT_POST, true);
        curl_setopt($c, CURLOPT_POSTFIELDS, $arguments);
      }
      $result = curl_exec($c);
      curl_close($c);

**Comment by Ellega** [comment]
Hi @cdujeu 

I had the same experience with Etherpad and Pydio with SSL

First, in all case Etherpad must be on same domaine than pydio. Right ? 
 
- Without SSL on pydio, Etherpad works very well

  host pydio : http://mydomaine/
  host etherpad : http://mydomaine:9001/

- With SSL on pydio, Etherpad works very well only with @HubertChomette fix (thank you for the time saved )  :

+++ line 53 ```  curl_setopt($c, CURLOPT_SSL_VERIFYPEER, false); ```

 host pydio : https://mydomaine/
 host etherpad : https://mydomaine:9001/
 
( same certificat SSL are used on both hosts)

that's it. Just for your information

**Comment by cdujeu** [comment]
in what file are you applying this change??

**Comment by Ellega** [comment]
sorry, in this file : 

``` plugins \ editor.etherpad \ etherpad-client \ etherpad-lite-client.php ```

**Comment by HubertChomette** [comment]
@Ellega : I use different server between pydio and etherpad.
This doesn't work directly but using a reverse proxy, it make the trick ;)

**Comment by Ellega** [comment]
@HubertChomette I m not familiar with reverse proxy :-) . But this works very well for me. 
I can now used a another server for etherpad. 

are you always use your fix if pydio with ssl ? 
without this, ertherpad don't work in pydio for me.
thanks again.

**Comment by HubertChomette** [comment]
I do.
I try last plugins version but seem's to have another issue. I'll try to make more test this week.
