### ISSUE TITLE
runTest.php protocol is not used

### ISSUE THREAD

**Issue by erixtekila** [pydio/pydio-core#871]
The correct https://github.com/pydio/pydio-core/blob/develop/core/src/runTests.php#L61 should be 

```
 $tokens = file_get_contents("${protocol}://${user}:${password}@${host}${path}/api/pydio/keystore_generate_auth_token/php_client");
```

**Comment by erixtekila** [comment]
plus 
https://github.com/pydio/pydio-core/blob/develop/core/src/runTests.php#L80
```
$client->getContent();
```
return an empty string…

**Comment by cdujeu** [comment]
Does it work once you include the proper protocol or not?

**Comment by erixtekila** [comment]
Yep. But, I didn't dig further for the getContent method…
