### ISSUE TITLE
error in DibiMySqlDriver.php

### ISSUE THREAD

**Issue by Ellega** [pydio/pydio-core#879]
Log message : 
"ERROR	admin	error l.166 (18)	DibiMySqlDriver.php	message=Illegal mix of collations (utf8_general_ci,IMPLICIT) and (utf8_unicode_ci,IMPLICIT) for operation '='"

![2015-03-24_144600](https://cloud.githubusercontent.com/assets/3939543/6803358/47262190-d237-11e4-8d56-bedbed49a55d.jpg)

**Comment by cdujeu** [comment]
closed because of .. ?

**Comment by Ellega** [comment]
Because it is append only on my Pydio Dev not production with exactely the same release same config.
I tried to track the pb in the database without success.
I think that was a very specific problem on my side.
I had to introduce this pb with all my test.
I rerun pydio with a clean install and all my settings. The pb is gone ...
I can't reproduce that.
I don't want polute you with that. Thx ;-)
