### ISSUE TITLE
Weird file size calculation

### ISSUE THREAD

**Issue by tmlmt** [pydio/pydio-core#880]
Hi,

I was trying to change the FILE SIZE option Application Parameters > Application Core > Uploaders Options. Entering 2M and saving updates the field to 2097152 but entering 2G gives -2147483648 (with a negative sign). Is this a bug ?

**Comment by cdujeu** [comment]
it's a php / 32bits limitation. I guess setting 1,8G should do the trick.
Please use the forum and do not open issues in github directly, thanks a lot!
charles
