### ISSUE TITLE
Zip Download

### ISSUE THREAD

**Issue by gmarke** [pydio/pydio-core#881]
Hi,

Thanks a lot for that nice piece of work!!

Probably not only me is facing problem with too big zip files in tmp folder and solution for this could be code like that in plugins/access.fs/class.fsAccessDriver.php in section responsible for zip creation.

The limitation for size is working properly but it would be good to have some popup message when the limit is exceeded and limit parameter in settings instead in code.

                    $size = 0;
                    foreach($selection->getFiles() as $files){
                        $files = call_user_func(array($this->wrapperClassName, "getRealFSReference"), $this->urlBase."/".$files);
                        $files = AJXP_Utils::securePath($files);
                        $d = new SplFileInfo($files);
                        if(!$d->isFile()){
                            foreach(new RecursiveIteratorIterator(new RecursiveDirectoryIterator($files)) as $file){
                                $size+=$file->getSize();
                                    if($size > 136937893){
                                        $this->LogDebug("dsfsdfsdfsdfsdfsdfsdfsd");
                                        throw new AJXP_Exception("Error while compressing");
                                        break;
                                    }
                            }
                        } else {
                            $size+=filesize($files);
                                    if($size > 136937893){
                                        throw new AJXP_Exception("Error while compressing");
                                        break;
                                    }
                            }
                        }

Please try to include this in new development version...

THanks a lot

**Comment by cdujeu** [comment]
hi gmarke
this is not a proper issue. Could you please either post in the forum and initiate a discussion there, or maybe better directly submit a github Pull Request with your code change. By the way, the accessDriver has a method directoryUsage() that you could use directly.
-c
