### ISSUE TITLE
Folder/tree view expand

### ISSUE THREAD

**Issue by nem2k** [pydio/pydio-core#883]
The expand option in the folder/tree view on the left hand side doesn't work correctly

To replicate:
1. Create a workspace with nested folders.
2. browse around in the nested folder structure in the main area
3. Click on expand and the folder view shows the expanded tree
4. refresh the page/close the browser and go back to pydio
5. click on expand again in the folder view, but this time dont do any navigation beforehand. the tree no longer expands to show the nested folders

It seems that the tree/folder view on the left hand side only correctly displays nested folders if you have opened/navigated to a nested folder at least once during your current session. The tree does not expand correctly if you havent navigated any folders yet

**Comment by cdujeu** [comment]
Hi
what's your browser? I cannot reproduce that. When i close / reload, the tree is actually already expanded, and the button says "collapse" instead of "expand" (this state is saved in the user preference).

**Comment by nem2k** [comment]
well, the tree is expanded in the sense that the button now says "collapse", but the tree doesn't default to showing me all of my nested folders after a refresh. the only way to see those nested folders is if I navigate into one of them first

I use opera and chrome and the same issue in both browsers

**Comment by cdujeu** [comment]
Ok just understood.
That's normal. The tree never loads the whole folders, they are always loaded "when needed" = when navigated. The switch just says "always show level 1 (collapsed)" or "show all folders".
-c
