### ISSUE TITLE
Quota Limit will not read from user or group when using repository templates

### ISSUE THREAD

**Issue by mikerhyner** [pydio/pydio-core#884]
I would like to use quota set on groups (or sometimes individual users), and counting space used in every group's repositories by setting "USAGE SCOPE" to "cummulative repositories". To allow a group admin to create their own repositories, I use a few repository templates and assign required parameters like path, permissions, etc. and also meta plugin "user quota", so quota computation will be in effect on every repository (but not already want to define the finite maximum usage here).

Unfortunately, this way, individual quotas set on a group or individual user will not be respected, always the quota value of the repository will be in effect, in opposite to when creating a repository directly as group admin (not deriving from a template), where the quota defined on user or group level will be in effect. 

After some hours of trying out several settings and analyzing the plugin code within ./plugins/meta.quota/class.QuotaComputer.php, I've finally seen that (beginning from a change done starting Pydio 6.0.3, when repository has a parent and owner is different than logged-in user, quota of the owner of the repository will be retrieved instead (what's fully Ok if there is actually an owner set on respective repository). But that seems not always to be the case, specially when repository has been created out of a template as group admin. I assume that because no owner can be retrieved, allowed quota value of the repository will be in effect, instead the one of current user or group (as required).

So, the long and short of it, I propose the following lines, starting on line 114, being changed within class.QuotaComputer.php:

-            $userObject = ConfService::getConfStorageImpl()->createUserObject($repo->getOwner());
+	    if ($repo->getOwner() != "") {
+              $userObject = ConfService::getConfStorageImpl()->createUserObject($repo->getOwner());
+	    }

That way, it will be assured that wen no repository owner can be retrieved (as it's the case on a repository derived from a template), quota value of current user will be in effect when set, and not the (dummy) value defined on repository template.

Perhaps that may be a bad idea (I'm not really a developer having the whole code in mind), but It's one way that solved me the problem actually. An other practicable solution could be to always set an owner for a repository, also when created out of a template (but I assume then the quota assigned to group admin will be in effect...).

**Comment by cdujeu** [comment]
hi mike
... I wonder if indeed we could simply set the owner when we create a child from template via admin. 
Can you try to change the line 1168 inside plugins/access.ajxp_conf/class.ajxp_confAccessDriver.php, from 
                   ```$newRep = $templateRepo->createTemplateChild($repDef["DISPLAY"], $repDef["DRIVER_OPTIONS"]);```
to
                   ``` $newRep = $templateRepo->createTemplateChild($repDef["DISPLAY"], $repDef["DRIVER_OPTIONS"], $loggedUser->getId());```

This may have some impact on who is allowed to administrate and assign rights on this repository... Could you do some heavy testing with this change?
-c

**Comment by mikerhyner** [comment]
Seems like a possible solution, but I assume this way, allowed quota value will be taken from (group) admin user that created the repository, instead of the current user, thus stopping individual max quota value specifically set for a single user.

**Comment by cdujeu** [comment]
ok, so instead, in the QuotaComputer, we could have
```
        if ($repo->hasParent() && $repo->getOwner() != null && $repo->getOwner() != AuthService::getLoggedUser()->getId()) {
            // Pass parent user instead of currently logged
            $userObject = ConfService::getConfStorageImpl()->createUserObject($repo->getOwner());
        }
```
is it what you suggest?

**Comment by mikerhyner** [comment]
exactly that make's most sense imho, providing most flexibility with this hierarchy:
1. fetching quota from parent user (repository onwer) when available
2. fetching quota from logged-in user when no parent repository or parent user is available
3. fetching quota as defined on the repository if no quota set on user level (current or parent) can be found

Greets, Mike

**Comment by cdujeu** [comment]
ok, I'll commit that, thx mike!
