### ISSUE TITLE
Pydio Etherpad plugins : issue on renaming or deleting a file

### ISSUE THREAD

**Issue by HubertChomette** [pydio/pydio-core#891]
In Etherpad Implementation, association between files and pad are stored on .ajxp_meta file.
If user rename a file, or delete it, .ajxp_meta aren't update.
As a consequence, after renaming a file, User lose page layout of his file. (the file only contains stored data,  layout page are stored on etherpad).
Instead of using file name, an UUID key by file could be a solution?

**Comment by cdujeu** [comment]
No the metadata must be moved directly with the file, but it's probably because you don't have the very latest version.

**Comment by cdujeu** [comment]
what file are you testing here? ".pad" files?

**Comment by HubertChomette** [comment]
.txt files
I do not use last plugin version.
Will do a whole update and see If it works. (I try to install last plugin
version but seem's to depend of other functions).


2015-04-07 18:10 GMT+02:00 Charles du Jeu <notifications@github.com>:

**Comment by cdujeu** [comment]
@HubertChomette is this one fixed?
-c

**Comment by HubertChomette** [comment]
with pad, yes.


2015-04-30 15:50 GMT+02:00 Charles du Jeu <notifications@github.com>:

**Comment by HubertChomette** [comment]
There is a new issue now.
Pad files , in pydio, are files with .pad extension and contain's pad id.
If you rename a pad file, the extension is missing and you can't open it . You can only open it with standard editor and see the pad id.

**Comment by HubertChomette** [comment]
Another one: If you copy the pad, the two files links the same pad.
