### ISSUE TITLE
add parameter in setting editor.pdfjs to enable sidebar View On Load by default

### ISSUE THREAD

**Issue by Nanomani** [pydio/pydio-core#895]
make this manually is easy

line 407 in  "plugins / editor.pdfjs / pdfjs / web / viewer.js"
change 0 to 1 like this : 

``` sidebarViewOnLoad: 1, ```

but it can be very usefull to add a parameter in editor.pdfjs for people who want this by default.

![2015-04-10_192540](https://cloud.githubusercontent.com/assets/3939543/7093262/d49151de-dfb7-11e4-905b-f1ed21a3c799.jpg)

**Comment by cdujeu** [comment]
We don't want to touch the files of the pdfjs library. 
Added some instructions in the plugin documentation.
