### ISSUE TITLE
move folder between repositories

### ISSUE THREAD

**Issue by olivierbossel** [pydio/pydio-core#898]
Hi Pydio,

First of all, thanks for your awesome work on this product. Looks clean, simple to use and not too intrusive with my data. I love it!

My question is :
Now it seems not possible to move folders between repositories. The files are ok but folders not..
Is that possible to add or repair this feature?

Thanks in advance!

Cheers!

**Comment by cdujeu** [comment]
Hi olivier, please use the forum for questions, github is used only for qualified bugs, thx!
-c
