### ISSUE TITLE
textLogDriver broken?

### ISSUE THREAD

**Issue by danielmorlock** [pydio/pydio-core#902]
The textLogDriver creates log files with correct permission, but does not write to them. I prepend a 

    var_dump(microtime(true), "__destruct()", $this->fileHandle);

to textLogDriver::__destruct() and

    var_dump(microtime(true), "write2", $level, $ip, $user, $source, $prefix, $message);

to textLogDriver::write2(). I get the following output:

    float(1430388841.1415)
    string(12) "__destruct()"
    resource(20) of type (stream)
    float(1430388841.2099)
    string(6) "write2"
    string(4) "Info"
    string(12) "79.209.97.10"
    string(4) "root"
    string(9) "access.fs"
    string(11) "Get_content"
    string(24) "files=my-files/world.txt"
    float(1430388841.21)
    string(6) "write2"
    string(5) "Error"
    string(12) "79.209.97.10"
    string(4) "root"
    string(23) "class.textLogDriver.php"
    string(11) "error l.160"
    string(51) "message=fwrite(): 20 is not a valid stream resource"

So it seems that the __destruct() is called before the write2(). 
Any ideas?

**Comment by cdujeu** [comment]
Will recheck that.
-c

**Comment by cdujeu** [comment]
Ok found the issue, it's broken indeed. Will commit a fix soon.

**Comment by cdujeu** [comment]
cf https://github.com/pydio/pydio-core/issues/902
