### ISSUE TITLE
Map Pydio group on custom LDAP field

### ISSUE THREAD

**Issue by hobgoblinsmaster** [pydio/pydio-core#903]
Using version 6.0.6, I'm trying to map user group path on a ldap field (department).
* If the group path does not already exists, it is not created.
* If I create the group manually, I can see my users (type ldap) in the group.
* When a user logs in, a "shadow" sql user is created at the root (tried with "autocreate" parameter on and off).
* If the field contains spaces or non ASCII characters, no mapping can be made (I also tried to create groups whose PATH is the base64 string sent by ldap).

If it is really not possible to use spaces or non ASCII characters, I maybe can use a custom dedicated LDAP field, but shadow sql users are a big problem.

**Comment by c12simple** [comment]
Hello,
First, Please create your question on forum pyd.io/f

Using version 6.0.6, I'm trying to map user group path on a ldap field (department).
try to map group => roleId in Pydio. groupPath is applied only for memberOf field
