### ISSUE TITLE
Pydio setup wizard: admin password strength

### ISSUE THREAD

**Issue by jbd** [pydio/pydio-core#907]
Hello,

if you copy/paste a password in the "Admin access" form of the wizard, the strength indicator is not updated. It's always "too short".

Jean-Baptiste

**Comment by cdujeu** [comment]
Hi
I cannot reproduce that, what's your OS and browser?
thx
-c

**Comment by jbd** [comment]
I'm using debian testing and Icedove (Firefox) 31.6.0.

**Comment by cdujeu** [comment]
Sorry can't really fix that, it's a specific browser issue with copy & paste.
