### ISSUE TITLE
cache folder deletion

### ISSUE THREAD

**Issue by erm3nda** [pydio/pydio-core#908]
I have deteled by a mistake the full /cache/ folder content.
I read about on the plugin made docs, but deleted more than i need.

The problem is that the full install data has gone away, asking me again to INTALL.
So, my question at this point are:

Is that the normal behavior?
If yes, why the install data is on the cache folder?

I really don't know what im missing on this, but do not sounds logical to me.
Any suggestions is highly appreciated.

**Comment by cdujeu** [comment]
please ask in the forum, not in the issues, thanks
