### ISSUE TITLE
E-Mail notification for watched shared folders is broken since 6.0.7

### ISSUE THREAD

**Issue by hnoefer** [pydio/pydio-core#912]
Hi,

change 49e44e21227095bb96bbe090c0d8d1ba67826a09 breaks the function which sends mail
when for example a file is uploaded to a shared folder where the watch modus is active.

Reproduce:
 - Install/update to 6.0.7
 - create a public shard folder
 - check that the watching mode is active
 - open the public link
 - expected behavior: a mail should be sent, behavior after update to 6.0.7: no mail is sent

Regards,
Holger

**Comment by cdujeu** [comment]
Hi Holger
We had some successful testing on our side, but maybe you have a given flavor of watches & users that we overlooked.
Will check.
-c

**Comment by cdujeu** [comment]
@hnoefer can you check that this re-fix is working? thx ;-)

**Comment by hnoefer** [comment]
the fix helped, "sending mail" for watched shared folders is working again!

Regards,
Holger
