### ISSUE TITLE
Editing shares in "My account" → "My shares" doesn't works

### ISSUE THREAD

**Issue by hobgoblinsmaster** [pydio/pydio-core#915]
When editing a share from "My account" → "My shares", the update buton is missing in the dialog box, so the share is non actualy editable.
![my-shares](https://cloud.githubusercontent.com/assets/1375255/7670520/119fa910-fca8-11e4-85ac-e6000312fc92.png)
See the dialog box when editing the share directly from is original workspace.
![edit-from-workspace](https://cloud.githubusercontent.com/assets/1375255/7670522/2f6c4eee-fca8-11e4-9d50-6eb45e8408b5.png)

Please either add the update button in the dialog box or replace all occurence of "edit" string by "view" string in "My account" → "My shares" and make fileds non editables.
Tests done with Pydio 6.0.7 (Debian package installation from repository).

**Comment by cdujeu** [comment]
Please post to the forum before creating issues on Github, thanks.
-c

**Comment by hobgoblinsmaster** [comment]
Please see
https://pyd.io/f/topic/editing-shares-in-my-account-%e2%86%92-my-shares-doesnt-works/

On Wed, Jun 3, 2015 at 10:36 AM, Charles du Jeu <notifications@github.com>
wrote:

> Closed #915 <https://github.com/pydio/pydio-core/issues/915>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pydio/pydio-core/issues/915#event-320890224>.
>



-- 
Landry MINOZA
landry.minoza@gmail.com
