### ISSUE TITLE
Auto created users from LDAP "synchronisation" have not the right group path.

### ISSUE THREAD

**Issue by hobgoblinsmaster** [pydio/pydio-core#916]
Using Pydio 6.0.7, connected to an LDAP (Active Directory), I have memberOf attibute mapped to group path.
At each user first login, a new entry is created in table ajxp_users, but group path is setted as "/" and not the real group path of the user.
Then they are viewable as "sql" users at the root of "Users & groups" setting page.
If I drag those "shadow users" from the root to their real group, I do not see them and just again, just the "ldap" user.
As a workaround, I had to schedule a system cron job that read my LDAP directory and create users in the SQL database whith the right group path (the script also allow us to change the group a users is in as pydio does not notice itself).

**Comment by cdujeu** [comment]
Please use forum first.

**Comment by hobgoblinsmaster** [comment]
Please see
https://pyd.io/f/topic/auto-created-users-from-ldap-synchronisation-have-not-the-right-group-path/

On Wed, Jun 3, 2015 at 10:35 AM, Charles du Jeu <notifications@github.com>
wrote:

> Closed #916 <https://github.com/pydio/pydio-core/issues/916>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pydio/pydio-core/issues/916#event-320889992>.
>



-- 
Landry MINOZA
landry.minoza@gmail.com
