### ISSUE TITLE
Weird LDAP search requests when typing in "create share as workspace" user search filed

### ISSUE THREAD

**Issue by hobgoblinsmaster** [pydio/pydio-core#917]
When I share a folder as workspace, LDAP users can only be searched by login.
I authentication settings, Search Users By attibute (LDAP_SEARCHUSER_ATTR) is setted as "cn,sn,givenName"
Tracing LDAP requests with wireshark, I see the LDAP query ‘(&(!(memberOf=*))(&(%LDAP_FILTER%)(|(|(cn=%SEARCH%*)(sn=%SEARCH%))(givenName=%SEARCH%*))))’ whith %SEARCH% what I typed in the search user field.
(!(memberOf=*)) means memberOf is empty on Active Directory. As my users are all in at least one group, the queries never match.
If I try ldapsearch command line with the same filter except (!(memberOf=*)), I got the expected results from my LDAP server.
I saw all sort of queries like (&(!(attibuteX=*))(attributeX=<whatever_is_searched>)) at many other situations when Pydio made requests against the LDAP directory. This queries will never match anything…

Pydio version 6.0.7 via Debian package.

**Comment by cdujeu** [comment]
can you post to the forum ? Please create issues only once they are qualified in the forum, thx

**Comment by hobgoblinsmaster** [comment]
please see
https://pyd.io/f/topic/weird-ldap-search-requests-when-typing-in-create-share-as-workspace-user-searc/

On Wed, Jun 3, 2015 at 10:35 AM, Charles du Jeu <notifications@github.com>
wrote:

> Closed #917 <https://github.com/pydio/pydio-core/issues/917>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pydio/pydio-core/issues/917#event-320889763>.
>



-- 
Landry MINOZA
landry.minoza@gmail.com
