### ISSUE TITLE
Can't download when runing on HHVM

### ISSUE THREAD

**Issue by ViolentVotan** [pydio/pydio-core#921]
Hello, 

I have been using pydio for some time now and recently switched a lot of my webapps over to HHVM. At first it seemed that pydio works fine out of the box, but I seem to be unable to download files. Here's the error in the HHVM log file:

\nFatal error: String length exceeded 2^31-2: 2147483647 in /home/www/cloud/plugins/access.fs/class.fsAccessWrapper.php on line 251
\nFatal error: String length exceeded 2^31-2: 2147483647 in /home/www/cloud/plugins/access.fs/class.fsAccessWrapper.php on line 251
\nFatal error: String length exceeded 2^31-2: 2147483647 in /home/www/cloud/plugins/access.fs/class.fsAccessWrapper.php on line 251
\nFatal error: String length exceeded 2^31-2: 2147483647 in /home/www/cloud/plugins/access.fs/class.fsAccessWrapper.php on line 251
\nFatal error: String length exceeded 2^31-2: 2147483647 in /home/www/cloud/plugins/access.fs/class.fsAccessWrapper.php on line 251
\nFatal error: String length exceeded 2^31-2: 2147483647 in /home/www/cloud/plugins/access.fs/class.fsAccessWrapper.php on line 251
\nFatal error: String length exceeded 2^31-2: 2147483647 in /home/www/cloud/plugins/access.fs/class.fsAccessWrapper.php on line 251

**Comment by cdujeu** [comment]
I did some test recently on HHVM, there was an issue with our custom wrappers mechanism...

**Comment by ViolentVotan** [comment]
Yes, for the time being I had to revert pydio back to good ol' php5.6 as not being able to download any files via web interface kind of renders it useless although hhvm did speed it up quite noticeably :)

**Comment by cdujeu** [comment]
maybe php7 will be the next step :-)
https://pages.zend.com/rs/zendtechnologies/images/PHP7-Performance%20Infographic.pdf
