### ISSUE TITLE
Show avatar on sharecenter

### ISSUE THREAD

**Issue by fbagnol** [pydio/pydio-core#923]
Hi, 

I need to add a functionality in share center.

I want to display the avatar of the user who shares.
I found where to put the code => class.ShareCenter.php, line 1004

But I have not found how to get the avatar.

Someone can help me ?

Thanks a lot in advance.
Regards
Frédéric

**Comment by cdujeu** [comment]
Hi Frédéric, please post to the forum. Github is dedicated to qualified issues only.
Charles
