### ISSUE TITLE
Can't install using a MySQL DB connection with a blank mysql password

### ISSUE THREAD

**Issue by cstaylor** [pydio/pydio-core#924]
Even through the database connection test succeeds, the "Install Pydio now" button is still disabled.

**Comment by cdujeu** [comment]
hi @cstaylor 
Please next time post to the forum before posting here. GH is only for qualified bug.
The password is required indeed.
I think it's really a very bad security policy to leave a blank pasword for the db... no way to change that on your side?

**Comment by cstaylor** [comment]
Oops, sorry about not posting to the forum first.

I agree: but the installer should say so.  I sat there wondering why the DB test worked but I couldn't install..

**Comment by cdujeu** [comment]
Added an error in connection test.
