### ISSUE TITLE
Fix for "Can not find repository id" when using access.smb module

### ISSUE THREAD

**Issue by mwehr** [pydio/pydio-core#928]
Hi,

I've found a problem when using the access.smb (smbclient) module.
I've set up a workspace with a SMB mount where the user does not have write access to SMB root path.
Recycle-bin is disable.

In case there are some SMB configuration erros and a user opens the corresponding workspace he will get "Can not find repository id".
The error persists even the configurations erros are solved.

It looks like that the problem appears at plugins/access.smb/smb.php line 312.
For some reason the $_SESSION["COUNT"]  is set to 1 but the $_SESSION["disk"] key doesn't exist.
It seems that it could happen that we detect that $_SESSION["COUNT"] == 0  -> go into the "== 0" condition of the IF part an then fail in the smb::look() call at line 317, so we never get $_SESSION["disk"] set.

A fix could be to move the $_SESSION["COUNT"] = 1;  from line 313 to line 318.
Or add "|| !isset($_SESSION["disk"]" to the IF condition at line 312.

regards 

Mario

**Comment by c12simple** [comment]
Hello,
Thank you for your infos.
Someone has had this issue since I did this commit: https://github.com/pydio/pydio-core/commit/cef1688f1e38830badefa1d147b48400cd09d7f2
Can you try to revert this commit

**Comment by mwehr** [comment]
Yeap will try to revert the changes.
I just want to mention,  I'm not using WebDav my error occurs when using the Web GUI.

**Comment by mwehr** [comment]
Hi,

It seems reverting this change fixes the problem for me.

**Comment by cdujeu** [comment]
This was already reverted
