### ISSUE TITLE
Problem with Hungarian language

### ISSUE THREAD

**Issue by csabakv** [pydio/pydio-core#930]
I tried to install Pydio 6.0.7 on my centOS 7 server. Everything worked fine, until I tried to change language to Hungarian.
I got an error message, but nothing unusual in log files, but blank white screen after that.
I tried, and if I select Hungarian language during install process, I got same blank white screen. I tried another languages as well, even chinese too, but this “blank white screen error” happened only with Hungarian.
Problem occurs even I successfully installed Pydio in English, and at login tried to change  to Hungarian.

**Comment by cdujeu** [comment]
@csabakv i cannot reproduce this locally. I switch to hungarian and have no special issue. Can you give more info : browser ? did you try to update to 6.0.8 since then?
