### ISSUE TITLE
http links fail 

### ISSUE THREAD

**Issue by gerroon** [pydio/pydio-core#934]
Hiu=

I have self signed certs which works great. I am trying to share a link but I want to share the link over http which worked perfectly fine in the past. Today it does not and it generates and error like this

Error while parsing JSON response : JSON.parse: unexpected end of data at line 1 column 1 of the JSON data

Now the same link with https works fine. I am not sure where to look for the issue.

Also my old shared links work. The issues seems to be with the newly created shares. I am not sure how the updates happened between now and then.

thanks

**Comment by cdujeu** [comment]
please post to the forum (https://pyd.io/f) instead of here in github. Thx
