### ISSUE TITLE
Fix for Expecting property name: line 1 column xxx (char xxxxx) 

### ISSUE THREAD

**Issue by mwehr** [pydio/pydio-core#937]
Hi,

This is a fix regarding the malformed JSON response send out to sync clients bulk stats requests in case the current file isn't read/write writable.
See pydio-sync [issue](https://github.com/pydio/pydio-sync/issues/102)

class.Filehasher
line 230
```php
 if(!$stat || !(($stat['mode'] & 0000400) && ($stat['mode'] & 0000200)) ) $stat = '{}';
```
and
line 200
```php
if (!$stat || !(($stat['mode'] & 0000400) && ($stat['mode'] & 0000200)) ) {
  print '{}';
} else {
```
The idea behind is to check read/write through the mod field and avoid to open a stream in the metadata extracting part.

regards

Mario

**Comment by cdujeu** [comment]
hi mario, 
thx, i'll check that

**Comment by cdujeu** [comment]
Mario
what about simply adding || !is_readable($node->getUrl()) ? Stat is cached anyway so it's not costly. We just have to check the "read" right, not necessarily "write", do we?
-c

**Comment by mwehr** [comment]
Hi,

In my case we have some folders in our CIFS share which are protected to be deleted by the user with a file within the folder which has limited rights by the user, ...(user cannot delete the file or modify the file).
I think such files should be ignored from pydio.
In this case we have to check read/write

regards,

Mario

**Comment by cdujeu** [comment]
sorry I don't understand. 
The fact is that compute filehash is a read only operation. 
Maybe if you want to prevent the sync to do anything on these files, that would be clearly at another location.

**Comment by mwehr** [comment]
Ahh yes,..sorry I did investigate this a along time ago. The problem was the the file which protects our folders inside the CIFS shares isn't accessible by the user so pydio cannot read and thus create the hash for this file.
Maybe this check for readable files has to be taken into account for other parts in pydio?
