### ISSUE TITLE
Temporary user deletion by creator not working

### ISSUE THREAD

**Issue by aleksi83** [pydio/pydio-core#941]
How to reproduce
Install pydio 6.0.8 (or use https://demo.pyd.io/)
1. Login as regular user (demo user on pydio demo site)
2. Open My Account from dashboard
3. Select Address book
4. Create new user or select existing user
5. Click Delete button
6. Error shows up on bottom screen "ajaxplorer.getUserSelection(...).getUniqueNode(...) is null "

Deleting temporary users using admin account seems to work.

**Comment by cdujeu** [comment]
Merging into #955
