### ISSUE TITLE
Better way to detect mount status for meta.mount module mounts

### ISSUE THREAD

**Issue by mwehr** [pydio/pydio-core#944]
Hi,

Maybe there is a better way do detect the mount status for the meta.mount cif mounts.
If we compare the device id from the mount folder and the parent folder we can determine if the mount folder is already mounted.
If the mount exists the device id fom parent and our mount target are different.
If it is a normal folder they are the same. This also fixes the the problem that sometimes there is the mount path left as normal directory with ".ajxp_mount" in it.
This solution works without the ".ajxp_mount" file.

... the implementation for isAlreadyMounted() could be:
```php
    protected function isAlreadyMounted()
    {
        list($user, $password) = $this->getCredentials();
        $MOUNT_POINT = $this->getOption("MOUNT_POINT", $user, $password);
        if( is_dir($MOUNT_POINT) ){
            if( stat(dirname($MOUNT_POINT))[0] == stat($MOUNT_POINT)[0] ){
                return false;
            }else{
                return true;
            }
        }else{
            return false;
        }
    }
```
..  line 189 in umountFS() should be changed to:
```php
if($this->getOption("REMOVE_MOUNTPOINT_ON_UNMOUNT") == true && $res == 0 && !$this->isAlreadyMounted() ){
```
feel free to test it.

regards,
Mario

**Comment by cdujeu** [comment]
@c12simple what do you think? Seems to me a valid option.
-c

**Comment by c12simple** [comment]
I agree that if we use .ajxp_mount to test mount point, we probably face to issue where normal folder with .ajxp_mount file has been existed.

Most of modern linux support ` mountpoint `command that give us exactly information and I re-wrote this function by using this command:

```
protected function isAlreadyMounted()
    {
        list($user, $password) = $this->getCredentials();
        $MOUNT_POINT = $this->getOption("MOUNT_POINT", $user, $password);
        $output = shell_exec("/bin/mountpoint $MOUNT_POINT");
        $regex = "/^(.*)is a mountpoint(.*)/";
        return (preg_match($regex, $output) === 1);
    }
```

However, I prefer to use mwehr's solution because *shell_exec* function may be disabled by administrator.
