### ISSUE TITLE
Issue while loading avatar

### ISSUE THREAD

**Issue by marioli** [pydio/pydio-core#946]
Hi,

first of all: great software! Pydio makes live easier - absolutely. Thank you!

I have a (less important) issue with the avatar.

I´m using pydio 6.0.8 from the ubuntu distribution. In my Workspace there appears an error icon instead of my avatar. The URL that should load the avatar is as follows:

https://pydio.local/index.php?secure_token=JMCE99HX5T7vjeaggnf5aTUno3JcqHlk&get_action=get_binary_param&binary_id=d6ace3-5881942.png&user_id=mario

However this makes my web server (nginx) bring the following error:
2015/07/23 18:04:27 [error] 40076#0: *2218 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Call to a member function getId() on a non-object in /usr/share/pydio/plugins/core.conf/class.AbstractConfDriver.php on line 1216" while reading response header from upstream, client: 10.1.1.5, server: pydio.local, request: "GET /index.php?secure_token=JMCE99HX5T7vjeaggnf5aTUno3JcqHlk&get_action=get_binary_param&binary_id=d6ace3-5881942.png&user_id=mario HTTP/1.1", upstream: "fastcgi://unix:/var/run/php_fpm.sock:", host: " pydio.local"

I took a look into the code and noticed that the $context could have been initialized if
isSet($httpVars["user_id"]) && AuthService::getLoggedUser() != null && AuthService::getLoggedUser()->isAdmin()) 

The first expression is true and as I see a security token I would guess the second is also true. But of course the user is a regular user (no admin) so the last expression will be false. So instead of simply using the user_id of the GET parameter (in case the thrid expression would be true too) this employs the method AuthService::getLoggedUser()->getId() - that actually fails at this point.

Is there anybody that shares this experience?

Thank you!

/Mario

**Comment by cdujeu** [comment]
Hi Mario
coming back to you on that: this seems actually seems to indicate that you don't have a user currently logged. Did you disable user management? Or are you logged as guest maybe?
-c

**Comment by cdujeu** [comment]
no feedback from user
