### ISSUE TITLE
Fix for nor properly encodet filenames with special chars when download with IE11

### ISSUE THREAD

**Issue by mwehr** [pydio/pydio-core#949]
Hi,

This is is a fix for not properly encodet filenames with special chars (umlaut) when downloaded with IE11.
IE11 somehow has problems with RFC 5987 so we need to change the Content-Disposition header.

class.HTMLWriter.php
line: 180

``` php
header('Content-Disposition: attachment; filename="' . $attachmentName . '"; filename*=utf-8\' \'' . rawurlencode($attachmentName));
```

class.fsAccessDriver.php
line: 1469

``` php
$filename = basename($filePathOrData);
header('Content-Disposition: attachment; filename="' . $filename . '"; filename*=utf-8\' \'' . rawurlencode($filename));
```

line: 1483:

``` php
$filename = basename($accelfile);
header('Content-Disposition: attachment; filename="' . $filename . '"; filename*=utf-8\' \'' . rawurlencode($filename));
```

regards

Mario

**Comment by cdujeu** [comment]
Mario, we'll integrate that, but for next suggestion please use Pull Request instead of issue, it will be even simpler !

**Comment by cdujeu** [comment]
Actually I cannot reproduce issues with IE11 on Windows 7. 
Can you be more specific about your current version / OS ?

**Comment by mwehr** [comment]
Hi,

We had this Problem with files from a meta mount workspace -> cifs
I've tested this on several different PCs, all Windows 7 (German) with IE11.

**Comment by cdujeu** [comment]
Mario, I can't commit that. A simple test gives the following result for me: 
![capture d ecran 2015-10-24 a 12 41 48](https://cloud.githubusercontent.com/assets/2465057/10710179/17d1aebe-7a4d-11e5-94d1-760061a035b7.png)
(same with the more simple case Universität). 
Whereas the previous version of the code is displaying a correct name.
It's IE Edge. Maybe your code should be introduced with specific browser detection...

**Comment by mwehr** [comment]
Hi,

maybe my boostrap_conf.php localization part is of interest:
```php
setlocale(LC_CTYPE, "de_AT.UTF-8");
putenv('LC_ALL=de_AT.UTF-8');
define("AJXP_LOCALE", "de_AT.UTF-8");
```

OS standart locale config is also "de_AT.UTF-8"

by the way, if I want to update my 6.0.x pydio to the latest 6.2dev what  should i use for
```php
##VERSION_NUMBER##__##VERSION_DATE##__##REVISION##__##DB_VERSION##
```

**Comment by cdujeu** [comment]
@mwehr you should not update yet :-)

**Comment by mwehr** [comment]
okidoki :-)

**Comment by cdujeu** [comment]
hi mario, it's time to update everything and start re-testing i18n issues :-). See the main README in the develop branch.

**Comment by cdujeu** [comment]
no news on that one, reopen if needed
