### ISSUE TITLE
Maybe replace mycrypt

### ISSUE THREAD

**Issue by TobiasScheinert** [pydio/pydio-core#962]
Hi,

its not a real issue, but not every operating system is maintaining mcrypt for php, Solaris for example will remove the support for mcrypt in Solaris 11.3. And another reason is, that not every OS that has mcrypt installed has MCRYPT_RIJNDAEL_256 support. For example Solaris only has MCRYPT_RIJNDAEL_192.

The last update from mcrypt was in the year 2012, so in my mind mcrypt is outdated. Please think about switching to a different solution, maybe OpenSSL.

https://paragonie.com/blog/2015/05/if-you-re-typing-word-mcrypt-into-your-code-you-re-doing-it-wrong

Greeting Tobias

**Comment by cdujeu** [comment]
We'll definitely remove that, as mcrypt will be dropped in php 7.1

**Comment by cdujeu** [comment]
Removed dependency to mcrypt, use phpseclib pure-php implementation for decyphering legacy encoded strings.
