### ISSUE TITLE
WebDAV no access to subdirectories and files

### ISSUE THREAD

**Issue by ChuckDaniels87** [pydio/pydio-core#963]
I can't access to listed<em> WebDAV</em> subdirectories nor files from browser (<em>Browser Access</em> activated) or client. 

I've tried both <strong>Nautilus</strong> and directly <strong>Firefox</strong> that can show list of files and folders but can't access to them (<em>HTTP error message without any information</em>). <strong>Cadaver</strong> and <strong>Cyberduck</strong> doesn't even access to WebDAV server.

I've activated <em>WebDAV</em> from <em>Core</em> and User and tried with <em>Basic Auth</em>. I also test <strong>http</strong> and <strong>https</strong>.

My server configuration is the following:

- <strong>Pydio path:</strong> <em>https://[...]/pydio</em>
- <strong>WebDAV path:</strong> <em>https://[...]/pydio/shares</em>
- <strong>Authentication:</strong> <em>LDAP </em>
- <strong>Digest Realm:</strong><em> ajxp_webdav_realm</em>
- <strong>Workspaces:</strong>
     - FS: <em>/home/pydio_share/$AJXP_USER</em>
     - SFTP: <em>/home/$AJXP_USER </em>
- <strong>SSL</strong>

My <em>.htaccess</em> file:

```
<IfModule mod_rewrite.c>
# You must set the correct values here if you want
# to enable webDAV sharing. The values assume that your 
# Pydio installation is at http://yourdomain/
# and that you want the webDAV shares to be accessible via 
# http://yourdomain/shares/repository_id/
RewriteEngine on
RewriteBase /pydio
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^shares ./dav.php [L]
RewriteRule ^api ./rest.php [L]
RewriteRule ^user ./index.php?get_action=user_access_point [L]
RewriteCond %{REQUEST_URI} !^/pydio/index
RewriteCond %{REQUEST_URI} !^/pydio/plugins
RewriteCond %{REQUEST_URI} ^/pydio/dashboard|^/pydio/welcome|^/pydio/settings|^/pydio/ws-
RewriteRule (.*) index.php [L]

#Following lines seem to be necessary if PHP is working
#with apache as CGI or FCGI. Just remove the #
#See http://doc.tiki.org/WebDAV#Note_about_Apache_with_PHP_as_fcgi_or_cgi

RewriteCond %{HTTP:Authorization} ^(.*)
RewriteRule ^(.*) - [E=HTTP_AUTHORIZATION:%1]

#Following lines may be necessary for a PHP-FPM setup
# to make sure that authorization is transmitted.
# Just remove the # at the beginning of the line

SetEnvIf Authorization "(.*)" HTTP_AUTHORIZATION=$1

</IfModule>

AddType application/json .json                                      
```

I'll gladly run some tests in my server and share needed logs.

Thanks,
Ismael

_PD: I tried to post a new thread with this error in Pydio Forum first but I am not able to._

**Comment by cdujeu** [comment]
hi
what url do you exactly use for connecting to the webdav?

**Comment by ChuckDaniels87** [comment]
I am using: *https://[...]/pydio/shares/name-of-the-ws*

**Comment by cdujeu** [comment]
hi @ChuckDaniels87 could you retry to post in Forum now? This must be a config issue, not a qualified bug. Thx

**Comment by ChuckDaniels87** [comment]
I've updated Pydio to 6.2.1. WebDAV seems to work now without any configuration change. 
@cdujeu, thank you very much for your attention. You have made a great piece of software!! :wink:
