### ISSUE TITLE
When using remote auth, "default repository" setting is not  saved

### ISSUE THREAD

**Issue by zephrax** [pydio/pydio-core#965]
I'm using remote authentication in my site. I configured pydio yo auto-generate the user when logging in.

After I login, when I access to pydio filemanager, the first page I see is "My Profile" instead the repository I checked as default.

If I go to the dashboard page, and check the "default repository" and then save, I got success message, but when I logout and login (remotely) again Pydio takes me to "My Profile" page again.

More information:

I created a new role "Role-A"
I created a new Repository "Role-A-Files"
For the "Role-A" I deny access to every repository but "Role-A-Files"

**Comment by zephrax** [comment]
I did some more tests.

The only way to reproduce this issue is, under Role-A  -> ACL (Configuration), denying access to every repository but Role-A-Files. 

It seems that the only way to get to a respository after logging in, is to use the Default Files repo.

**Comment by cdujeu** [comment]
Did you retest that on 6.2.1 ?

**Comment by cdujeu** [comment]
no feedback
