### ISSUE TITLE
Power FS + password-protected minisite

### ISSUE THREAD

**Issue by ytzelf** [pydio/pydio-core#966]
Zip creation enabled / Power FS disabled
=> Archive download in Pydio works
=> Archive download in password-free minisite works
=> Archive download in password-protected minisite works

Zip creation enabled / Power FS enabled
=> Archive download in Pydio works (light blue bottom popup with %)
=> Archive download in password-free minisite works (light blue bottom popup with %)
**=> Archive download in password-protected minisite crashes : in the password-protected minisite I get the light blue bottom popup with visual % indication and once it reaches 100% nothing happens. Pydio log says nothing.**

Zip creation disabled / Power FS enabled
=> Archive download in Pydio works (light blue bottom popup with %)
=> Archive download in password-free minisite does not work (Download does not show)
=> Archive download in password-protected minisite does not work (Download does not show)

**Comment by cdujeu** [comment]
Hi, 
I cannot reproduce that. Could you test the latest dev build (pyd.io/build/pydio-latest.zip) ? 
thx
-c

**Comment by ytzelf** [comment]
Thanks Charles, I will have a look as soon as possible. Is there any specific step to manual updating I should be aware of or is it just a matter of copying the new source to my nginx root and overriding the previous files?

Thanks again

**Comment by ytzelf** [comment]
Or even better, can I do that from the app itself? I've set my update channel to development with no  update found. With testing an update is found pydii-update.0.0.0.0 but fails to download

**Comment by cdujeu** [comment]
to be rechecked, @ytzelf did you ever retest that?

**Comment by ytzelf** [comment]
I believe it's working now. Sorry for not mentioning it
