### ISSUE TITLE
Syncable doesn't work on repo created from template with AJXP_ALLOW_SUB_PATH

### ISSUE THREAD

**Issue by hobgoblinsmaster** [pydio/pydio-core#967]
Just created 2 workspace template one with path set as : AJXP_DATA_PATH/groupes/AJXP_GROUP_PATH, the second with AJXP_DATA_PATH/services/AJXP_GROUP_PATH/AJXP_ALLOW_SUB_PATH both with feature “Syncable Workspace” and “Syncable workspace” set to yes.

I have an error in the second (with AJXP_ALLOW_SUB_PATH) when creating a new folder in any workspace created from the template:
![erreur_pydio_syncable](https://cloud.githubusercontent.com/assets/1375255/10423972/7434b2fe-70cb-11e5-9a58-3f602940e535.png)

The log:
```
date	ip	level	user	action	source	params	

05-20-15 11:39:41	10.2.42.1	INFO	lminoza	Switch Repository	conf.sql	rep. id=4ab5fc1e9dfb2659b35161b7f399c8b4	
05-20-15 11:39:49	10.2.42.1	INFO	lminoza	Create Dir	access.fs	dir=projet-xxx//test6	
05-20-15 11:39:50	10.2.42.1	ERROR	lminoza	error l.460	class.ChangesTracker.php	message=stat(): stat failed for ajxp.fs://0c2c7d52493fe147e05149f787263e55/test6
```
When disabling “syncable workspace” on the template with AJXP_ALLOW_SUB_PATH, I have no more errors on folder creation.

The form of node_path seams to be different in the table ajxp_index :
– for the workspaces made from the first template, node_path is /<group_path>/<folder_name>
– fot the workspaces made from the template with AJXP_ALLOW_SUB_PATH, node_path is /<folder_name>

Pydio 6.0.7 on Debian 7 installed from package.

**Comment by hobgoblinsmaster** [comment]
From: https://pyd.io/f/topic/syncable-doesnt-work-on-repo-created-from-template-with-ajxp_allow_sub_path/#post-95369

**Comment by cdujeu** [comment]
to be reproduced

**Comment by cdujeu** [comment]
not reproduced in last branch. Please re-open if required
