### ISSUE TITLE
Can't create a folder with a substring of an existing folder

### ISSUE THREAD

**Issue by hobeika** [pydio/pydio-core#971]
Hi,

When I try to create a new folder named with a substring of an already existing folder I encounter an error and the folder is not created.

Example:
- Create the folder "EXPERIMENTAL 4.1.0"
- Create the folder "4.1.0"
- You have the following error message:"A file/folder with that name already exists (names are case insensitive). Please choose another one!"

It seems the space between the two words of the first folder is the culprit. Replacing it with an underscore allows me to create the second substring folder.

**Comment by c12simple** [comment]
What is your Webserver and OS? and webbrowser ?
(For next question, please post in forum)
THank you

**Comment by hobeika** [comment]
Thanks for your feedback. Sorry about the forum I didn't know.
webserver: Pydio Version 6.0.8 - 2015-06-29 on debian squeeze
Browser: Iceweasel 38.3.0 on debian jessie

**Comment by c12simple** [comment]
I think this issue is caused by Iceweasel. I tested on firefox or chrome and have no issue
(Pydio does not support Iceweasel :D  )

**Comment by hobeika** [comment]
iceweasel = firefox. It is just the rebranded version of firefox on debian.

**Comment by cdujeu** [comment]
Hi guys, is this issue qualified or not?

**Comment by hobeika** [comment]
I think it is not. I still have the problem. What can I do to help resolve this issue?

**Comment by cdujeu** [comment]
did you try in other browser?

**Comment by hobeika** [comment]
Just now with chromium (aka chrome on debian jessie) version 45.0.2454.85 Built on 8.1, running on Debian 8.2 (64-bit).

Same behaviour.

**Comment by hobeika** [comment]
I have just tried on another computer. Still the same.
