### ISSUE TITLE
PHP Fatal error after upgrade to 6.2.0

### ISSUE THREAD

**Issue by colideum** [pydio/pydio-core#983]
After upgrade i'm receiving error:
PHP Fatal error:  Call to a member function rolesLastUpdated() on a non-object in /ajaxplorer/web/plugins/core.conf/class.AbstractAjxpUser.php on line 615
After cookies were cleared it happens just after login credentials were entered.

**Comment by cdujeu** [comment]
HI Colideum, 
that should normally go away after clearing cookies... Can you make sure to clear the cache as well (rm /ajaxplorer/web/data/cache/plugins_*) ?

**Comment by adrianbj** [comment]
I am also getting this error on an older installation of pydio - one that was initially installed without a database for storing config settings etc. My newer pydio installation is fine. I have cleared cookies and the pydio plugins_* files.

**Comment by colideum** [comment]
Hi,
cookies cleared, cache deleted, but rrror remains the same :(

**Comment by cdujeu** [comment]
Hi again,  

First step: there's a last cache to clear to make sure, in data/cache/i18n/*.ser. 
Second step: if still no differences, maybe the upgrade failed and the classes are not all up-to-date. Can you try to get the full package for the last version, then backup and replace the core/ and plugins/ folders from your install with the new ones?

Now the Forum should be functionnal on the new website, can you try to post there for the next messages? If still not working use github.

-c

**Comment by raubv0gel** [comment]
Same and further problems here :-( Logs:

Got error 'PHP message: PHP Fatal error:  Call to a member function filterParameterValue() on a non-object in ajaxplorer/plugins/core.conf/class.AbstractAjxpUser.php on line 274\n'

Got error 'PHP message: PHP Fatal error:  Call to a member function rolesLastUpdated() on a non-object in ajaxplorer/plugins/core.conf/class.AbstractAjxpUser.php on line 615\n',

ajaxplorer\plugins\conf.serial\class.AJXP_SerialUser.php:200
if(isSet($filteredRights["ajxp.roles"])) $filteredRights["ajxp.roles"] = $this->filterRolesForSaving($filteredRights["ajxp.roles"]); <- 2nd argument missing!

**Comment by cdujeu** [comment]
Please USE THE FORUM. https://pydio.com/en/community
thx
Charles

**Comment by adrianbj** [comment]
Made a post here: https://pydio.com/forum/f/topic/php-fatal-error-after-upgrade-to-6-2-0/
