### ISSUE TITLE
Can't login after upgrade to 6.2

### ISSUE THREAD

**Issue by adrianbj** [pydio/pydio-core#984]
Not sure what the reason is - seems like my password is incorrect, but definitely entering the correct one. Any chance there were some hash/salt changes or something?

Anyone else having problems?

**Comment by adrianbj** [comment]
Managed to reset my password and it seems fine now. Not sure what happened though :)

**Comment by adrianbj** [comment]
Not positive, but I feel like it might have been a password length issue. My old PW was 7 characters - it worked until the upgrade. I am not certain that I changed the length limit from 8 to 7 previously, but it is definitely at 8 now - is it possible this was overridden in the this update? Do passwords get rejected at login if they are too short, or only when setting them up initially/changing them?

**Comment by cdujeu** [comment]
hi adrian, normally passwords are not rejected if at login if they are too short, just when setting them. FYI you should now be able to post in the new forum.
