### ISSUE TITLE
problem when creating folder and generating public link

### ISSUE THREAD

**Issue by sim1st** [pydio/pydio-core#985]
Congratulation for opening new HOMEPAGE!!!

But I failed to post on forum, that's way I am posing here.

I have two problems.

First one is showing 'Unknown parsing error' when creating folder. 

I have found another forum but I couldn't solve yet.

Second problem is showing red bar error with no message(empty message) when generating public link.

But When I press 'f5' button(refresh), generating link and creating folder is done normally.

It means these functions are working well, but I just want to not to be shown error message.

* Environment
- OS: CentOS 7
- Pydio Version: 6.0.x

If you need any information, Let me know.

Thanks!

**Comment by cdujeu** [comment]
Hi @sim1st  can you try to post in forum now? It should be fixed!

**Comment by sim1st** [comment]
Thanks.

I solved this problem.

I traced Apache(httpd) log and I found that occurred php memory limitation in php.ini file.

So I changed php memory limitation parameter and restart httpd service.

And all problems are solved and working well.
