### ISSUE TITLE
Cannot type all letters in advance search

### ISSUE THREAD

**Issue by xtream1101** [pydio/pydio-core#994]
Using Pydio 6.2.0

I can type all letters in the search box, but if I open the advance search and try and type in the advance textboxes it trys to trigger other actions. Even though I am focused in the textbox and I can type other letters.

i.e. if I type the letter 'd' it pops up a notification asking if I want to delete the file even though I am focused in the textbox

**Comment by cdujeu** [comment]
Hello
What browser are you using? This can sometimes happen in very specific context, but generally a simple page refresh is enough.
-c

**Comment by cdujeu** [comment]
I can confirm. Urgent. :-( Sorry.
