### ISSUE TITLE
6.2 : User Last repository preference not saved anymore

### ISSUE THREAD

**Issue by cdujeu** [pydio/pydio-core#996]

**Comment by cdujeu** [comment]
?goto=repo_alias/path/to/folder is broken as well

**Comment by leprince** [comment]
@isma91 Hi, Did this issue get resolved? I do not see any commits related to it.

@cdujeu Please reopen this ticket if the issue is not resolved.

**Comment by cdujeu** [comment]
@isma91 closed it because he verified it was fixed in the trunk indeed :-)
Will be in the next release.
